# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Type stubs for the dev-only _smlib_dev extension module."""

from typing import Any

import _omni_solid as sm

class Loop:
    def edgeuses(self) -> list[Edgeuse]: ...
    def edges(self) -> list[sm.Edge]: ...
    def vertices(self) -> list[sm.Vertex]: ...
    def loopuse(self) -> Loopuse: ...
    def loopuses(self) -> tuple[Loopuse | None, Loopuse | None]: ...
    def face(self) -> sm.Face: ...
    def brep(self) -> sm.Brep: ...
    def is_outer_loop(self) -> bool: ...

class Loopuse:
    def edgeuses(self) -> list[Edgeuse]: ...
    def edges(self) -> list[sm.Edge]: ...
    def loop(self) -> Loop: ...
    def face(self) -> sm.Face: ...
    def brep(self) -> sm.Brep: ...
    def other_loopuse(self) -> Loopuse: ...
    def is_edge_loopuse(self) -> bool: ...
    def is_vertex_loopuse(self) -> bool: ...
    def orientation(self) -> str: ...

class Edgeuse:
    def edge(self) -> sm.Edge: ...
    def face(self) -> sm.Face: ...
    def loopuse(self) -> Loopuse: ...
    def loop(self) -> Loop: ...
    def mate(self) -> Edgeuse: ...
    def cw_edgeuse(self) -> Edgeuse | None: ...
    def ccw_edgeuse(self) -> Edgeuse | None: ...
    def edge_parameter(self, normalized: float) -> float: ...
    def point_at_normalized(self, normalized: float) -> tuple[float, float, float]: ...
    def uv_point_at_normalized(self, normalized: float) -> tuple[float, float]: ...
    def orientation(self) -> str: ...
    def brep(self) -> sm.Brep: ...

def edgeuses(edge: sm.Edge) -> list[Edgeuse]: ...
def loopuses(edge: sm.Edge) -> list[Loopuse]: ...
def loops(edge: sm.Edge) -> list[Loop]: ...
def edgeuse_of_face(edge: sm.Edge, face: sm.Face) -> Edgeuse | None: ...
def loop_of_face(edge: sm.Edge, face: sm.Face) -> Loop | None: ...
def face_loops(face: sm.Face) -> list[Loop]: ...
def topology_counts(brep: sm.Brep) -> dict[str, int]: ...
def kernel_create_box(origin: tuple[float, float, float], length: float, width: float, height: float) -> sm.Brep: ...
def user_test() -> sm.Brep | None: ...
def user_test_example() -> sm.Brep: ...
def poly_face_original_face_index(poly_face: sm.PolyFace) -> int: ...
def topology_pick_ray(
    brep: sm.Brep,
    ray_point: tuple[float, float, float],
    ray_direction: tuple[float, float, float],
    tolerance: float,
    line_padding: float = ...,
) -> list[dict[str, Any]]: ...
def assert_valid(
    object: sm.Brep | sm.Face | sm.Edge | sm.Vertex | Edgeuse | Loop | Loopuse | sm.Curve | sm.Surface,
    level: int = ...,
    walk: bool = ...,
) -> bool: ...
def assert_valid_reports(
    object: sm.Brep | sm.Face | sm.Edge | sm.Vertex | Edgeuse | Loop | Loopuse | sm.Curve | sm.Surface,
    level: int = ...,
    walk: bool = ...,
) -> tuple[bool, list[str]]: ...
def dump(
    object: sm.Brep | sm.Face | sm.Edge | sm.Vertex | Edgeuse | Loop | Loopuse | sm.Curve | sm.Surface,
    abbreviated: bool = ...,
) -> None: ...

class _DrawModule:
    def extract_draw_batches(
        self,
        object: sm.Brep | sm.Face | sm.Edge | sm.Vertex | Edgeuse | Loop | Loopuse | sm.Curve | sm.Surface,
        variant: str = ...,
    ) -> list[dict[str, Any]]:
        """Raises RuntimeError when SMLib was built without SM_GFX_OUTPUT_CODE."""
    def viewport_draw_brep(
        self,
        brep: sm.Brep,
        color: tuple[float, float, float] | None = ...,
        clear_first: bool = ...,
        center: bool = ...,
    ) -> None: ...

class _TestsModule:
    def available(self) -> bool: ...
    def list_prog_test_suites(self) -> list[str]: ...
    def run_prog_test_suite(
        self,
        name: str,
        working_directory: str = ...,
        do_graphics: bool = ...,
    ) -> dict[str, Any]: ...
    def debug_runtime_info(self) -> dict[str, Any]: ...

draw: _DrawModule
tests: _TestsModule

def extract_draw_batches(
    object: sm.Brep | sm.Face | sm.Edge | sm.Vertex | Edgeuse | Loop | Loopuse | sm.Curve | sm.Surface,
    variant: str = ...,
) -> list[dict[str, Any]]:
    """Raises RuntimeError when SMLib was built without SM_GFX_OUTPUT_CODE."""
