# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Opening a stage with pxr before and after importing usd_brep. Each case needs a fresh interpreter."""

import json
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path

CUBE = Path(__file__).resolve().parents[3] / "TestFiles" / "brep_validator" / "CubeBrepArray.usda"

# Windows loads extension DLLs from added directories only, as in test_heal_file.py.
PROLOGUE = """
import os
import sys
dll_directories = []
if sys.platform == "win32":
    for path in os.environ.get("PATH", "").split(";"):
        if path and os.path.isdir(path):
            dll_directories.append(os.add_dll_directory(path))
"""


def run(body):
    """Run body in a fresh interpreter with the cube as sys.argv[1]; return stdout."""
    script = PROLOGUE + textwrap.dedent(body)
    result = subprocess.run([sys.executable, "-c", script, str(CUBE)], capture_output=True, text=True, timeout=300)
    assert result.returncode == 0, result.stderr
    return result.stdout


class TestSchemaRegistrationOrder(unittest.TestCase):
    def test_stage_opened_after_importing_usd_brep(self):
        stdout = run(
            """
            import usd_brep
            from pxr import Usd
            Usd.Stage.Open(sys.argv[1])
            print("breps:", len(usd_brep.usd.import_breps(sys.argv[1])))
            """
        )
        self.assertIn("breps: 2", stdout)

    def test_stage_opened_before_importing_usd_brep(self):
        stdout = run(
            """
            from pxr import Usd
            Usd.Stage.Open(sys.argv[1])
            import usd_brep
            try:
                usd_brep.usd.import_breps(sys.argv[1])
            except RuntimeError as exc:
                print(exc)
            """
        )
        self.assertIn("registered after a USD stage was opened", stdout)

    def test_import_leaves_schema_types_open(self):
        """Importing usd_brep must not fix OpenUSD's schema types against plugins registered after it."""
        info = {"Types": {"TestFakeFooAPI": {"alias": {"UsdSchemaBase": "FakeFooAPI"}, "autoGenerated": True,
                                             "bases": ["UsdAPISchemaBase"], "schemaKind": "singleApplyAPI"}}}
        plugin = {"Info": info, "LibraryPath": "", "Name": "testFakeFoo", "ResourcePath": ".", "Root": ".",
                  "Type": "resource"}
        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "plugInfo.json").write_text(json.dumps({"Plugins": [plugin]}))
            stdout = run(
                f"""
                import usd_brep
                from pxr import Plug, Usd
                Plug.Registry().RegisterPlugins({tmp!r})
                print("known:", not Usd.SchemaRegistry.GetTypeFromSchemaTypeName("FakeFooAPI").isUnknown)
                """
            )
        self.assertIn("known: True", stdout)


if __name__ == "__main__":
    unittest.main()
