# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Operation modules for the SMLib GUI."""

from .booleans import apply_boolean_operation, boolean_source_line
from .file_io import (
    LOAD_FILE_FILTER,
    SAVE_FILE_FILTER,
    occt_brep_io_available,
    brep_usd_io_available,
    brep_usd_io_unavailable_reason,
    ensure_extension_for_filter,
    export_native_brep,
    export_occt_brep,
    export_usd_objects,
    extension_for_filter,
    file_kind_for_path,
    import_native_brep_object,
    import_occt_brep_objects,
    import_usd_objects,
    native_brep_file_is_ascii,
    native_brep_load_unavailable_reason,
    omnisolid_plugin_path,
)
from .modify import ModifyResult, apply_modify_operation
from .overlays import (
    BoxOverlay,
    CurveSampleOverlay,
    DrawBatchOverlay,
    LineOverlay,
    NormalOverlay,
    PickOverlay,
    PointOverlay,
    PolylineOverlay,
    SectionOverlay,
    SurfaceSampleOverlay,
    TopologyOverlay,
    brep_edge_highlight,
    brep_edge_polylines,
    brep_face_highlight,
    brep_face_normals,
    brep_vertex_highlight,
    make_overlay_object,
    sample_curve_overlay,
    sample_surface_overlay,
    section_overlay,
)
from .test_runner import (
    DEBUG_GUIDANCE,
    PROG_TEST_SUITES,
    SMLIB_TESTS_UNAVAILABLE_HINT,
    draw_events_to_overlays,
    list_prog_test_suites,
    run_prog_test_suite,
    tests_available,
    unavailable_reason,
)

__all__ = [
    "BoxOverlay",
    "CurveSampleOverlay",
    "DEBUG_GUIDANCE",
    "DrawBatchOverlay",
    "LOAD_FILE_FILTER",
    "LineOverlay",
    "ModifyResult",
    "NormalOverlay",
    "PROG_TEST_SUITES",
    "PickOverlay",
    "PointOverlay",
    "PolylineOverlay",
    "SAVE_FILE_FILTER",
    "SMLIB_TESTS_UNAVAILABLE_HINT",
    "SectionOverlay",
    "SurfaceSampleOverlay",
    "TopologyOverlay",
    "apply_boolean_operation",
    "apply_modify_operation",
    "boolean_source_line",
    "occt_brep_io_available",
    "brep_edge_highlight",
    "brep_edge_polylines",
    "brep_face_highlight",
    "brep_face_normals",
    "brep_usd_io_available",
    "brep_usd_io_unavailable_reason",
    "brep_vertex_highlight",
    "draw_events_to_overlays",
    "ensure_extension_for_filter",
    "export_native_brep",
    "export_occt_brep",
    "export_usd_objects",
    "extension_for_filter",
    "file_kind_for_path",
    "import_native_brep_object",
    "import_occt_brep_objects",
    "import_usd_objects",
    "list_prog_test_suites",
    "make_overlay_object",
    "native_brep_file_is_ascii",
    "native_brep_load_unavailable_reason",
    "omnisolid_plugin_path",
    "run_prog_test_suite",
    "sample_curve_overlay",
    "sample_surface_overlay",
    "section_overlay",
    "tests_available",
    "unavailable_reason",
]
