# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Type stubs for _omni_solid — Python bindings for the SMLib solid modeling kernel."""

from __future__ import annotations

from typing import Literal, Sequence, TypeVar, TypedDict, overload

from numpy import float32, int32
from numpy.typing import NDArray

# ---------------------------------------------------------------------------
#  Point / Vector shorthands used throughout the API.
# ---------------------------------------------------------------------------
_Point3 = tuple[float, float, float]
_Vec3 = tuple[float, float, float]
_BBox = tuple[_Point3, _Point3]

class TessellationFailure(TypedDict):
    face_index: int
    stage: Literal["boundary_preparation", "face_tessellation", "polygon_output"]
    status: int
    status_name: str

class TessellationReport(TypedDict):
    failures: list[TessellationFailure]
    lamina_edge_count: int
    spine_edge_count: int
    input_manifold: bool
    output_manifold: bool
    has_mesh: bool

class TessellationDefaults(TypedDict):
    chord_height_tolerance: float
    curve_angle_tolerance_deg: float
    surface_angle_tolerance_deg: float
    max_edge_length: float
    max_aspect_ratio: float

class TessellationError(RuntimeError):
    report: TessellationReport
    failures: list[TessellationFailure]
    status: int
    status_name: str

# Loop / Loopuse / Edgeuse topology, topology_pick_ray, and kernel Draw extraction
# live in the separate _smlib_dev module. See
# source/SmPyDevLib/stubs/smlib_dev/__init__.pyi.

# ===================================================================
#  Enums
# ===================================================================

class BooleanOp:
    UNION: BooleanOp
    DIFFERENCE: BooleanOp
    INTERSECTION: BooleanOp
    MERGE: BooleanOp

class BooleanOp2D:
    UNION: BooleanOp2D
    INTERSECTION: BooleanOp2D
    DIFFERENCE: BooleanOp2D
    EXCLUSIVE_OR: BooleanOp2D
    MERGE: BooleanOp2D

class FilletXSect:
    LINEAR: FilletXSect
    CIRCULAR: FilletXSect
    BLEND: FilletXSect

class TrimType:
    KEEP_POINT: TrimType
    DELETE_POINT: TrimType
    SPLIT: TrimType

class ContinuityType:
    UNDEFINED: ContinuityType
    DISCONTINUOUS: ContinuityType
    C0: ContinuityType
    G1: ContinuityType
    G1R: ContinuityType
    G1_G2: ContinuityType
    G1_G2_G3: ContinuityType
    C1: ContinuityType
    C1_G2: ContinuityType
    C1_G2_G3: ContinuityType
    C1_C2: ContinuityType
    C1_C2_G3: ContinuityType
    C1_C2_C3: ContinuityType
    C_INFINITY: ContinuityType

class BSplineCurveForm:
    POLYLINE: BSplineCurveForm
    CIRCULAR_ARC: BSplineCurveForm
    ELLIPTIC_ARC: BSplineCurveForm
    PARABOLIC_ARC: BSplineCurveForm
    HYPERBOLIC_ARC: BSplineCurveForm
    HELICAL_ARC: BSplineCurveForm
    UNSPECIFIED: BSplineCurveForm

class CurveParameterization:
    UNIFORM: CurveParameterization
    CHORD_LENGTH: CurveParameterization
    CENTRIPETAL: CurveParameterization

class PolyBooleanOp:
    UNION: PolyBooleanOp
    INTERSECTION: PolyBooleanOp
    DIFFERENCE: PolyBooleanOp
    MERGE: PolyBooleanOp
    PARTIAL_MERGE: PolyBooleanOp

class CapEnds:
    NONE: CapEnds
    START: CapEnds
    END: CapEnds
    BOTH: CapEnds

class OffsetType:
    LEFT: OffsetType
    RIGHT: OffsetType
    BOTH: OffsetType

# ===================================================================
#  Value types
# ===================================================================

class Vec3:
    x: float
    y: float
    z: float
    @overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @overload
    def __init__(self, t: _Vec3) -> None: ...

class Vec2:
    x: float
    y: float
    def __init__(self, x: float, y: float) -> None: ...

class Axis2Placement:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, origin: _Point3, x_axis: _Vec3, y_axis: _Vec3) -> None: ...

# ===================================================================
#  Kernel types
# ===================================================================

class Object: ...

_TObject = TypeVar("_TObject", bound=Object)

class Brep(Object):
    def faces(self) -> list[Face]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def bounding_box(self, tight: bool = False) -> _BBox: ...
    def center(self) -> _Point3: ...
    def volume(self, relative_accuracy: float = 1e-3) -> float: ...
    def area(self, relative_accuracy: float = 1e-3) -> float: ...
    def relationship_to(self, other: Brep) -> dict[str, object]: ...
    def distance_to(self, other: Brep) -> float: ...
    def mass_properties(self, relative_accuracy: float = 1e-3, density: float = 1.0, origin: _Point3 | None = None) -> dict[str, object]: ...
    def is_manifold_solid(self) -> bool: ...
    def material_census(self) -> dict[str, int]: ...
    def copy(self) -> Brep:
        """Deep-copy without promoting NURBS geometry to analytics."""
        ...
    def __copy__(self) -> Brep: ...
    def __deepcopy__(self, memo: dict[int, object]) -> Brep: ...
    def face_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def vertex_count(self) -> int: ...
    def info(self) -> dict[str, object]: ...
    @staticmethod
    def read_from_file(
        filename: str,
        ascii: bool | None = None,
        rebuild_uv_trim_curves: bool = False,
    ) -> Brep: ...
    def write_to_file(self, filename: str, ascii: bool = True) -> None: ...
    @overload
    def tessellate(
        self,
        *,
        chord_height_tolerance: float = 0.0,
        curve_angle_tolerance_deg: float = 25.0,
        surface_angle_tolerance_deg: float = 25.0,
        max_edge_length: float = 0.0,
        max_aspect_ratio: float = 0.0,
        allow_partial: bool = False,
        return_failures: bool = False,
        return_report: Literal[True],
    ) -> tuple[PolyBrep, TessellationReport]: ...
    @overload
    def tessellate(
        self,
        *,
        chord_height_tolerance: float = 0.0,
        curve_angle_tolerance_deg: float = 25.0,
        surface_angle_tolerance_deg: float = 25.0,
        max_edge_length: float = 0.0,
        max_aspect_ratio: float = 0.0,
        allow_partial: Literal[False] = False,
        return_failures: Literal[False] = False,
        return_report: Literal[False] = False,
    ) -> PolyBrep: ...
    @overload
    def tessellate(
        self,
        *,
        chord_height_tolerance: float = 0.0,
        curve_angle_tolerance_deg: float = 25.0,
        surface_angle_tolerance_deg: float = 25.0,
        max_edge_length: float = 0.0,
        max_aspect_ratio: float = 0.0,
        allow_partial: bool = False,
        return_failures: Literal[True],
        return_report: Literal[False] = False,
    ) -> tuple[PolyBrep, list[TessellationFailure]]: ...
    @overload
    def tessellate(
        self,
        *,
        chord_height_tolerance: float = 0.0,
        curve_angle_tolerance_deg: float = 25.0,
        surface_angle_tolerance_deg: float = 25.0,
        max_edge_length: float = 0.0,
        max_aspect_ratio: float = 0.0,
        allow_partial: Literal[False] = False,
        return_failures: bool = False,
        return_report: bool = False,
    ) -> PolyBrep | tuple[PolyBrep, list[TessellationFailure]] | tuple[PolyBrep, TessellationReport]: ...

class Face:
    def bounding_box(self, tight: bool = False) -> _BBox: ...
    def area(self, relative_accuracy: float = 1e-3) -> float: ...
    def surface(self) -> Surface: ...
    def uv_domain(self) -> tuple[tuple[float, float], tuple[float, float]]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def outer_loop_edges(self) -> list[Edge]: ...
    def boundary_loops(self) -> list[list[tuple[Edge, bool]]]: ...
    def boundary_outer_loop(self) -> list[tuple[Edge, bool]]: ...
    def point_at_uv(self, u: float, v: float) -> _Point3: ...
    def normal_at_uv(self, u: float, v: float) -> _Vec3: ...
    def outward_normal_at_uv(self, u: float, v: float) -> _Vec3: ...
    def interior_point(self) -> _Point3: ...
    def classify_uv(self, u: float, v: float) -> str: ...
    def closest_point(self, point: _Point3) -> tuple[_Point3, float]: ...
    def centroid(self, relative_accuracy: float = 1e-3) -> _Point3: ...
    def brep(self) -> Brep: ...

class Edge:
    def bounding_box(self, tight: bool = False) -> _BBox: ...
    def length(self, desired_accuracy: float = 1e-6) -> float: ...
    def curve(self) -> Curve: ...
    def start_vertex(self) -> Vertex: ...
    def end_vertex(self) -> Vertex: ...
    def vertices(self) -> tuple[Vertex, Vertex]: ...
    def other_vertex(self, vertex: Vertex) -> Vertex | None: ...
    def faces(self) -> list[Face]: ...
    def point_at(self, t: float) -> _Point3: ...
    def closest_point(self, point: _Point3) -> tuple[_Point3, float, float]: ...
    def parameter_range(self) -> tuple[float, float]: ...
    def classify_parameter(self, t: float) -> str: ...
    def tangent_at(self, t: float) -> _Vec3: ...  # follows the curve's direction, not the edge's start->end sense
    def brep(self) -> Brep: ...

class Vertex:
    def point(self) -> _Point3: ...
    def edges(self) -> list[Edge]: ...
    def faces(self) -> list[Face]: ...
    def brep(self) -> Brep: ...

class Curve(Object):
    def parameter_range(self) -> tuple[float, float]: ...
    def start_point(self) -> _Point3: ...
    def end_point(self) -> _Point3: ...
    def evaluate(self, t: float) -> _Point3: ...
    def length(self, desired_accuracy: float = 1e-6) -> float: ...
    def is_closed(self, tolerance: float = 0.0) -> bool: ...
    def is_planar(self, tolerance: float = ...) -> bool: ...

class BSplineCurve(Curve): ...
class Line(BSplineCurve): ...

class Circle(BSplineCurve):
    def center(self) -> _Point3: ...
    def radius(self) -> float: ...
    def normal(self) -> _Vec3: ...
    def x_axis(self) -> _Vec3: ...
    def y_axis(self) -> _Vec3: ...

class Surface(Object):
    def u_domain(self) -> tuple[float, float]: ...
    def v_domain(self) -> tuple[float, float]: ...
    def uv_domain(self) -> tuple[tuple[float, float], tuple[float, float]]: ...
    def evaluate(self, u: float, v: float) -> _Point3: ...
    def normal(self, u: float, v: float) -> _Vec3: ...
    def derivatives(self, u: float, v: float) -> tuple[_Point3, _Vec3, _Vec3]: ...
    def is_planar(self, tolerance: float = ...) -> bool: ...
    def is_periodic_u(self) -> bool: ...
    def is_periodic_v(self) -> bool: ...

# ===================================================================
#  PolyBrep types
# ===================================================================

class PolyVertex:
    def get_point(self) -> _Point3: ...
    def get_poly_brep(self) -> PolyBrep: ...

class PolyFace:
    def get_poly_brep(self) -> PolyBrep: ...
    def get_normal(self) -> _Vec3: ...

class PolyEdge:
    def get_poly_brep(self) -> PolyBrep: ...
    def get_start_vertex(self) -> PolyVertex: ...
    def get_end_vertex(self) -> PolyVertex: ...

class PolyBrep(Object):
    def get_faces(self) -> list[PolyFace]: ...
    def get_vertices(self) -> list[PolyVertex]: ...
    def get_edges(self) -> list[PolyEdge]: ...
    def get_points(self) -> list[_Point3]: ...
    def to_mesh_arrays(self, face_varying_normals: bool = False) -> dict[str, list[object]]: ...
    def to_numpy_arrays(self, face_varying_normals: bool = False) -> dict[str, NDArray[float32] | NDArray[int32]]: ...
    def calculate_bounding_box(self) -> _BBox: ...
    def is_manifold_solid(self) -> bool: ...
    def get_tolerance(self) -> float: ...
    def copy(self) -> PolyBrep: ...
    def __copy__(self) -> PolyBrep: ...
    def __deepcopy__(self, memo: dict[int, object]) -> PolyBrep: ...
    def compute_area_centroid(self) -> tuple[float, _Point3]: ...
    def compute_properties(self, origin: _Point3) -> dict[str, object]: ...
    def mass_properties(self, density: float = 1.0, origin: _Point3 | None = None) -> dict[str, object]: ...
    def section_plane(
        self, plane_origin: _Point3, plane_normal: _Vec3, zone_tolerance: float
    ) -> list[tuple[_Point3, _Point3]]: ...
    def ray_intersection(
        self,
        ray_point: _Point3,
        ray_direction: _Vec3 | None,
        ray_tolerance: float,
        ray_stepoff: float,
    ) -> list[dict[str, object]]: ...

# ===================================================================
#  Tessellation
# ===================================================================

def tessellation_defaults() -> TessellationDefaults: ...

def tessellate_boundaries(
    brep: Brep,
    *,
    angle_tolerance_deg: float = 5.0,
    allow_partial: bool = False,
) -> tuple[list[_Point3], list[int], list[Edge]]: ...

@overload
def tessellate(
    brep: Brep,
    *,
    chord_height_tolerance: float = 0.0,
    curve_angle_tolerance_deg: float = 25.0,
    surface_angle_tolerance_deg: float = 25.0,
    max_edge_length: float = 0.0,
    max_aspect_ratio: float = 0.0,
    allow_partial: bool = False,
    return_failures: bool = False,
    return_report: Literal[True],
) -> tuple[PolyBrep, TessellationReport]: ...
@overload
def tessellate(
    brep: Brep,
    *,
    chord_height_tolerance: float = 0.0,
    curve_angle_tolerance_deg: float = 25.0,
    surface_angle_tolerance_deg: float = 25.0,
    max_edge_length: float = 0.0,
    max_aspect_ratio: float = 0.0,
    allow_partial: Literal[False] = False,
    return_failures: Literal[False] = False,
    return_report: Literal[False] = False,
) -> PolyBrep: ...
@overload
def tessellate(
    brep: Brep,
    *,
    chord_height_tolerance: float = 0.0,
    curve_angle_tolerance_deg: float = 25.0,
    surface_angle_tolerance_deg: float = 25.0,
    max_edge_length: float = 0.0,
    max_aspect_ratio: float = 0.0,
    allow_partial: bool = False,
    return_failures: Literal[True],
    return_report: Literal[False] = False,
) -> tuple[PolyBrep, list[TessellationFailure]]: ...
@overload
def tessellate(
    brep: Brep,
    *,
    chord_height_tolerance: float = 0.0,
    curve_angle_tolerance_deg: float = 25.0,
    surface_angle_tolerance_deg: float = 25.0,
    max_edge_length: float = 0.0,
    max_aspect_ratio: float = 0.0,
    allow_partial: Literal[False] = False,
    return_failures: bool = False,
    return_report: bool = False,
) -> PolyBrep | tuple[PolyBrep, list[TessellationFailure]] | tuple[PolyBrep, TessellationReport]: ...

def read_brep_from_file(
    filename: str,
    ascii: bool | None = None,
    rebuild_uv_trim_curves: bool = False,
) -> Brep: ...

def read_part_from_file(
    filename: str,
    ascii: bool = True,
) -> tuple[list[Curve], list[Surface], list[int], list[Brep]]: ...

# ===================================================================
#  Primitives  (sm.primitives.*)
# ===================================================================

def create_box(origin: _Point3, length: float, width: float, height: float) -> Brep: ...
def create_sphere(origin: _Point3, radius: float) -> Brep: ...
def create_cone(origin: _Point3, radius_base: float, radius_top: float, height: float) -> Brep: ...
def create_cylinder(origin: _Point3, radius: float, height: float) -> Brep: ...
def create_torus(origin: _Point3, radius_major: float, radius_minor: float) -> Brep: ...
def create_plane(origin: _Point3, length: float, width: float) -> Brep: ...
def create_planar_circle(origin: _Point3, radius: float) -> Brep: ...
def create_pyramid(origin: _Point3, length: float, height: float) -> Brep: ...
def create_cylindrical_box(origin: _Point3, length: float, inside_radius: float, outside_radius: float, start_angle_deg: float, end_angle_deg: float) -> Brep: ...
def create_partial_sphere(origin: _Point3, radius: float, start_angle_deg: float, end_angle_deg: float) -> Brep: ...
def create_sphere_no_pole(center: _Point3, radius: float) -> Brep: ...
def create_partial_cone(origin: _Point3, radius_base: float, radius_top: float, height: float, start_angle_deg: float, end_angle_deg: float) -> Brep: ...
def create_cone_elliptic_ends(front_radius: float, rear_radius: float, height: float, front_tilt_about_x_deg: float = 0.0, rear_tilt_about_x_deg: float = 0.0, front_tilt_about_y_deg: float = 0.0, rear_tilt_about_y_deg: float = 0.0, end_caps: bool = True) -> Brep: ...
def create_partial_cylinder(origin: _Point3, radius: float, height: float, start_angle_deg: float, end_angle_deg: float) -> Brep: ...
def create_partial_torus(origin: _Point3, radius_major: float, radius_minor: float, start_angle_deg: float, end_angle_deg: float) -> Brep: ...
def create_swung_primitive(xy_curves: Sequence[Curve], xz_curves: Sequence[Curve], scale: float = 1.0) -> Brep: ...
def create_blend_primitive(
    brep: Brep,
    edge1: Edge,
    face1: Face,
    edge2: Edge,
    face2: Face,
    same_dir_curves: bool = True,
) -> Face: ...
def create_skin_primitive(curves_per_profile: Sequence[int], curves: Sequence[Curve], degree: int = 1, cap_ends: bool = True) -> Brep: ...
def create_skin_from_faces(faces: Sequence[Face], degree: int = 1) -> tuple[list[Face], Brep]: ...

# ===================================================================
#  Curves  (sm.curves.*)
# ===================================================================

def create_line_segment(start: _Point3, end: _Point3) -> Curve: ...
def create_line(start: _Point3, direction: _Vec3) -> Curve: ...
def create_circle(center: _Point3, radius: float) -> Circle: ...  # type: ignore[no-redef]
def create_arc(center: _Point3, radius: float, start_angle_deg: float, end_angle_deg: float) -> Curve: ...
def create_helix(origin: _Point3, height: float, radius_start: float, radius_end: float, turns: float, *, right_handed: bool = True, tolerance: float = 0.0001) -> BSplineCurve: ...
def create_ellipse(origin: _Point3, radius1: float, radius2: float) -> Curve: ...
def create_curve(points: Sequence[_Point3]) -> Curve: ...
def create_canonical_curve(points: Sequence[_Point3], knots: Sequence[float], knot_multiplicities: Sequence[int], weights: Sequence[float] | None = None, degree: int = 3, form: BSplineCurveForm = ...) -> Curve: ...
def create_rectangle(center: _Point3, length: float, width: float) -> list[Curve]: ...
def create_regular_polygon(center: _Point3, sides: int, radius: float) -> list[Curve]: ...
def create_curve_approx_points(points: Sequence[_Point3]) -> Curve: ...
def create_curve_interp_points(points: Sequence[_Point3], *, parameterization: CurveParameterization = ...) -> Curve: ...
def offset_curve(curve: BSplineCurve, distance: float) -> Curve: ...
def evaluate_curve(curve: Curve, parameter: float) -> dict[str, _Point3]: ...
def evaluate_continuity(curve: Curve, parameter: float) -> ContinuityType: ...
def drop_curve_to_surface(curve: BSplineCurve, surface: Surface) -> list[Curve]: ...
def convert_to_lines_and_arcs(curve: BSplineCurve) -> list[Curve]: ...
def project_curve_to_surface(curve: BSplineCurve, surface: Surface) -> list[Curve]: ...
def lift_uv_curve(uv_curve: BSplineCurve, surface: Surface) -> list[Curve]: ...
def remove_curve_knots(curve: Curve) -> Curve: ...
def make_curves_compatible(curves: Sequence[BSplineCurve]) -> None: ...
def order_curves(curves: Sequence[BSplineCurve]) -> list[BSplineCurve]: ...

# ===================================================================
#  Surfaces  (sm.surfaces.*)
# ===================================================================

def create_surface_from_points(control_points: Sequence[_Point3], rows: int, cols: int) -> Surface: ...
def create_surface_from_corner_points(corner_umin_vmin: _Point3, corner_umax_vmin: _Point3, corner_umin_vmax: _Point3, corner_umax_vmax: _Point3) -> Surface: ...
def create_surface_from_ordered_points(points: Sequence[_Point3], rows: int, cols: int) -> Surface: ...
def create_surface_from_random_points(points: Sequence[_Point3]) -> Surface: ...
def create_ruled_surface(curve1: BSplineCurve, curve2: BSplineCurve) -> Surface: ...
def create_surface_revolution(curve: BSplineCurve, origin: _Point3, axis: _Vec3, angle_deg: float) -> Surface: ...
def create_offset_surface(surface: Surface, distance: float) -> Surface: ...
def create_extrude_surface(curve: BSplineCurve, sweep_vector: _Vec3) -> Surface: ...
def create_sweep_surface(curve: BSplineCurve, path: BSplineCurve) -> Surface: ...
def create_skin_surface(profiles: Sequence[BSplineCurve]) -> Surface: ...
def create_planar_faces(curves: Sequence[Curve]) -> Brep: ...

# ===================================================================
#  Booleans  (sm.booleans.*)
# ===================================================================

def boolean(brep1: Brep, brep2: Brep, *, operation: BooleanOp) -> Brep: ...
def boolean_union(brep1: Brep, brep2: Brep) -> Brep: ...
def boolean_difference(brep1: Brep, brep2: Brep) -> Brep: ...
def boolean_intersection(brep1: Brep, brep2: Brep) -> Brep: ...
def boolean_merge(brep1: Brep, brep2: Brep) -> Brep: ...
def merge_breps(breps: Sequence[Brep], *, operation: BooleanOp) -> Brep: ...
def boolean_with_options(brep1: Brep, brep2: Brep, *, operation: BooleanOp, cookie_cutter: bool = False, imprinting: bool = False, post_process: bool = True, imprint_and_classify: bool = False, keep_other_brep: bool = False) -> Brep: ...
def boolean_2d(brep1: Brep, brep2: Brep, *, operation: BooleanOp2D) -> Brep: ...
def boolean_lists(breps1: Sequence[Brep], surfaces1: Sequence[Surface], breps2: Sequence[Brep], surfaces2: Sequence[Surface], *, operation: int) -> tuple[list[Brep], list[Surface]]: ...
def evaluate_csg_tree(breps: Sequence[Brep], postfix_tree: Sequence[int]) -> list[Brep]: ...
def boolean_with_curves(brep1: Brep, brep2: Brep, *, operation: BooleanOp) -> tuple[Brep, list[Edge]]: ...
def non_manifold_boolean(brep1: Brep, brep2: Brep, *, operation: BooleanOp) -> Brep: ...
def piecewise_merge(brep1: Brep, brep2: Brep, create_new_breps_for_faces: bool = False) -> Brep: ...

# ===================================================================
#  Sweeps  (sm.sweeps.*)
# ===================================================================

def linear_sweep(curves: Sequence[Curve], direction: _Vec3, distance: float, *, cap_ends: bool = True) -> Brep: ...
def rotational_sweep(curves: Sequence[Curve], base_point: _Point3, axis: _Vec3, angle_deg: float, *, cap_ends: bool = True) -> Brep: ...
def draft_sweep(curves: Sequence[Curve], height: float, angle_deg: float, *, fillet_corners: bool = False, cap_ends: CapEnds = ...) -> Brep: ...
def pipe_sweep(path: Curve, *, radius: float, cap_ends: bool = True) -> Brep: ...
def taper_extrude(curves: Sequence[Curve], height: float, draft_angle_deg: float, *, cap_ends: CapEnds = ..., fillet_corner: bool = False) -> Brep: ...
def sweep_along_planar_path(profile_curves: Sequence[Curve], path_curves: Sequence[Curve], *, move_profile: bool = True, cap_ends: CapEnds = ...) -> Brep: ...
def linear_sweep_with_repetitions(curves: Sequence[Curve], direction: _Vec3, distance: float, *, repetitions: int, cap_ends: bool = True) -> Brep: ...
def rotational_sweep_with_repetitions(curves: Sequence[Curve], base_point: _Point3, axis: _Vec3, angle_deg: float, *, repetitions: int, cap_ends: bool = True) -> Brep: ...
def curve_sweep(profile_curves: Sequence[Curve], path_curve: BSplineCurve, scale_reference: BSplineCurve | None = None, scale_curve: BSplineCurve | None = None, *, cap_ends: bool = True) -> Brep: ...
def curve_sweep_from_faces(faces: Sequence[Face], path_curve: BSplineCurve, scale_reference: BSplineCurve | None = None, scale_curve: BSplineCurve | None = None, *, cap_ends: bool = True) -> Brep: ...
def curve_sweep_from_edges(edges: Sequence[Edge], path_curve: BSplineCurve, scale_reference: BSplineCurve | None = None, scale_curve: BSplineCurve | None = None, *, cap_ends: bool = True) -> Brep: ...
def non_manifold_linear_sweep(brep_to_sweep: Brep, direction: _Vec3, distance: float, *, region_brep: Brep | None = None, do_stitching: bool = True, do_merge: bool = False, faces: Sequence[Face] | None = None, edges: Sequence[Edge] | None = None, vertices: Sequence[Vertex] | None = None) -> Brep: ...
def non_manifold_rotational_sweep(brep_to_sweep: Brep, base_point: _Point3, axis: _Vec3, angle_deg: float, *, region_brep: Brep | None = None, do_stitching: bool = True, do_merge: bool = False, faces: Sequence[Face] | None = None, edges: Sequence[Edge] | None = None, vertices: Sequence[Vertex] | None = None) -> Brep: ...

# ===================================================================
#  Fillets  (sm.fillets.*)
# ===================================================================

def chamfer_fillet(brep: Brep, radius: float) -> Brep: ...
def circular_fillet(brep: Brep, radius: float) -> Brep: ...
def fillet_edges(brep: Brep, edges: Sequence[Edge], *, radius: float, xsect_type: int = 1, continuity: int = 1, thumbweight: float = 1.0) -> Brep: ...
def variable_radius_fillet(brep: Brep, edges: Sequence[Edge], *, start_radius: float, end_radius: float, xsect_type: int = 1, continuity: int = 1) -> Brep: ...
def remove_fillet(brep: Brep) -> Brep: ...
def fillet_edges_per_edge(brep: Brep, edges: Sequence[Edge], radii: Sequence[float], xsect_types: Sequence[FilletXSect], *, continuity: int = 1, thumbweight: float = 1.0) -> Brep: ...
def surface_surface_fillet(surface1: Surface, surface2: Surface, *, radius1: float, radius2: float, tolerance: float, xsect_type: int = 1, mirror: bool = False, complement: bool = False) -> Brep: ...
def fillet_preview(brep: Brep, edges: Sequence[Edge], *, radius: float) -> list[Surface]: ...
def set_bevel_corners(brep: Brep, *, edges: Sequence[Edge], vertices: Sequence[Vertex], radius: float) -> Brep: ...

# ===================================================================
#  Offset  (sm.offset.*)
# ===================================================================

def shell_brep(brep: Brep, distance: float, *, extended_offset: bool = True, self_intersection: bool = True, create_solid: bool = True, faces_to_shell: Sequence[Face] = ...) -> Brep: ...
def offset_brep(brep: Brep, distance: float, *, extended_offset: bool = True, self_intersection: bool = True) -> Brep: ...
def create_offset_profile(curves: Sequence[Curve], distance: float, *, offset_type: OffsetType = ..., round_corners: bool = True, shell_result: bool = False) -> Brep: ...

# ===================================================================
#  Brep ops  (sm.brep_ops.*)
# ===================================================================

def turn_to_nurbs(brep: Brep) -> Brep: ...

# ===================================================================
#  Stitching  (sm.stitching.*)
# ===================================================================

def stitch_brep(brep: Brep) -> Brep: ...
def stitch_brep_with_face(brep: Brep, face: Face) -> Brep: ...
def simple_face_stitch(brep: Brep, faces_to_keep: Sequence[Face], faces_to_delete: Sequence[Face]) -> tuple[Brep, int, float, float]: ...
def stitch_into_solid(brep: Brep) -> tuple[Brep, bool, int, float, float]: ...
def stitch_into_shell(brep: Brep, max_stitching_ratio: float = 1.0, *, shell_is_well_formed: bool = False) -> tuple[Brep, bool, int, float, float]: ...
def unify_normals(brep: Brep, start_face: Face, num_samples: int = 100) -> tuple[Brep, list[Face]]: ...
def stitch_advanced(brep: Brep, tolerance_3d: float, squeeze_small_edges: bool = True, split_edges_with_vertices: bool = True, making_manifold_solid: bool = True, remove_laminar_slivers: bool = False) -> tuple[Brep, int, int, float, float]: ...

# ===================================================================
#  Intersectors  (sm.intersect.*)
# ===================================================================

def intersect_breps(brep1: Brep, brep2: Brep) -> tuple[list[Curve], list[object]]: ...
def intersect_brep_with_plane(brep: Brep, plane_point: _Point3, plane_normal: _Vec3) -> list[Curve]: ...
def intersect_curves(curve1: Curve, curve2: Curve) -> tuple[list[_Point3], list[float], list[float]]: ...
def intersect_surfaces(surface1: Surface, surface2: Surface) -> list[Curve]: ...
def intersect_faces(face1: Face, face2: Face) -> tuple[list[Curve], list[_Point3]]: ...
def intersect_curve_surface(curve: Curve, surface: Surface) -> tuple[list[Curve], list[_Point3]]: ...
def intersect_curve_brep(curve: Curve, brep: Brep) -> tuple[list[Curve], list[_Point3]]: ...
def intersect_curve_face(curve: Curve, face: Face) -> tuple[list[Curve], list[_Point3]]: ...

# ===================================================================
#  Transforms  (sm.transforms.*)
# ===================================================================

def translate(target: _TObject, translation: _Vec3) -> _TObject: ...
def rotate(target: _TObject, ref_point: _Point3, axis: _Vec3, angle_deg: float) -> _TObject: ...
def scale(target: _TObject, scale: _Vec3) -> _TObject: ...
def scale_about_point(target: _TObject, ref_point: _Point3, scale: _Vec3) -> _TObject: ...
def transform(target: _TObject, placement: Axis2Placement) -> _TObject: ...

# ===================================================================
#  Queries  (sm.queries.*)
# ===================================================================

def brep_closest_point(brep: Brep, point: _Point3) -> tuple[object, float]: ...
def brep_closest_point_all(brep: Brep, point: _Point3) -> tuple[list[_Point3], list[float]]: ...
def curve_closest_point(curve: Curve, point: _Point3) -> tuple[object, float, float]: ...
def curve_closest_point_all(curve: Curve, point: _Point3) -> tuple[list[_Point3], list[float], list[float]]: ...
def surface_closest_point(surface: Surface, point: _Point3) -> tuple[Vec3, list[Vec2], float]: ...
def is_manifold_solid(brep: Brep) -> bool: ...
def material_census(brep: Brep) -> dict[str, int]: ...
def compute_volume(brep: Brep, relative_accuracy: float = 1e-3) -> float: ...
def brep_relationship(a: Brep, b: Brep) -> dict[str, object]: ...
def brep_distance(a: Brep, b: Brep) -> float: ...
def get_closest_point(brep: Brep, point: _Point3) -> tuple[_Point3, float]: ...
def find_edge(brep: Brep, point: _Point3) -> tuple[int, float]: ...
def find_face(brep: Brep, point: _Point3) -> Face: ...
def get_faces_via_api(brep: Brep) -> list[Face]: ...
def get_edges_via_api(brep: Brep) -> list[Edge]: ...
def brep_bounding_box(brep: Brep, tight: bool = False) -> _BBox: ...
def brep_copy(brep: Brep) -> Brep:
    """Deep-copy without promoting NURBS geometry to analytics."""
    ...
def face_bounding_box(face: Face, tight: bool = False) -> _BBox: ...
def face_area(face: Face, relative_accuracy: float = 1e-3) -> float: ...
def edge_bounding_box(edge: Edge, tight: bool = False) -> _BBox: ...
def edge_length(edge: Edge, desired_accuracy: float = 1e-6) -> float: ...
def vertex_point(vertex: Vertex) -> _Point3: ...
def evaluate_surface_point(surface: Surface, u: float, v: float) -> _Point3: ...
def evaluate_surface_normal(surface: Surface, u: float, v: float) -> _Vec3: ...
def evaluate_surface_derivatives(surface: Surface, u: float, v: float) -> tuple[_Point3, _Vec3, _Vec3]: ...

# ===================================================================
#  Cut / Project / Trim  (sm.cutting.*)
# ===================================================================

def cut(brep: Brep, plane_point: _Point3, plane_normal: _Vec3) -> Brep: ...
def project_brep_onto_plane(brep: Brep, plane_point: _Point3, plane_normal: _Vec3) -> list[Curve]: ...
def project_and_trim(brep: Brep, curve: BSplineCurve, projection_dir: _Vec3, ref_point: _Point3) -> Brep: ...
def create_silhouette_curves(brep: Brep, plane_point: _Point3, plane_normal: _Vec3) -> list[Curve]: ...
def project_curve(brep: Brep, curve: BSplineCurve, projection_vector: _Vec3) -> list[Curve]: ...
def trim_surface_with_3d_curves(surface: Surface, curve_loops: Sequence[int], curves: Sequence[Curve]) -> Brep: ...
def trim_project_parallel(object: Brep | Surface, curve: BSplineCurve, projection_dir: _Vec3, ref_point: _Point3, trim_type: TrimType = ...) -> Brep: ...

# ===================================================================
#  Heal  (sm.heal.*)
# ===================================================================

def heal_brep(brep: Brep) -> Brep: ...

# ===================================================================
#  Polygon mesh ops  (sm.poly.*)
# ===================================================================

def poly_boolean(poly_brep1: PolyBrep, poly_brep2: PolyBrep, operation: PolyBooleanOp) -> PolyBrep: ...
def poly_boolean_union(poly_brep1: PolyBrep, poly_brep2: PolyBrep) -> PolyBrep: ...
def poly_boolean_difference(poly_brep1: PolyBrep, poly_brep2: PolyBrep) -> PolyBrep: ...
def poly_boolean_intersection(poly_brep1: PolyBrep, poly_brep2: PolyBrep) -> PolyBrep: ...
def poly_boolean_merge(poly_brep1: PolyBrep, poly_brep2: PolyBrep) -> PolyBrep: ...
def poly_brep_is_manifold_via_api(poly_brep: PolyBrep) -> bool: ...
def poly_brep_volume_via_api(poly_brep: PolyBrep) -> float: ...

# Kernel Draw extraction (extract_draw_batches) and viewport_draw_* helpers now
# live in the _smlib_dev module; see source/SmPyDevLib/stubs/smlib_dev/__init__.pyi.

# ===================================================================
#  USD submodule
# ===================================================================

from . import usd as usd
