# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Type stubs for _omni_solid.usd — USD import/export for BRep and PolyBrep meshes."""

from __future__ import annotations

from typing import Literal, Sequence, overload

from . import Brep, PolyBrep


class BrepArrayHealResult:
    @property
    def prim_path(self) -> str | None: ...
    @property
    def layer(self) -> str: ...
    @property
    def status_code(self) -> int: ...
    @property
    def status_name(self) -> str: ...
    @property
    def ok(self) -> bool: ...
    @property
    def brep_count(self) -> int: ...
    @property
    def message(self) -> str: ...

class MeshTessellationResult:
    @property
    def prim_path(self) -> str: ...
    @property
    def packed_index(self) -> int | None: ...
    @property
    def mesh_path(self) -> str | None: ...
    @property
    def status_code(self) -> int: ...
    @property
    def status_name(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def ok(self) -> bool: ...
    @property
    def failed_face_count(self) -> int: ...
    @property
    def point_count(self) -> int: ...

class BrepImportResult:
    @property
    def prim_path(self) -> str: ...
    @property
    def packed_index(self) -> int | None: ...
    @property
    def brep(self) -> Brep | None: ...
    @property
    def status_code(self) -> int: ...
    @property
    def status_name(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def ok(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


class BrepImportReport:
    @property
    def breps(self) -> list[Brep]: ...
    @property
    def items(self) -> list[BrepImportResult]: ...
    @property
    def failures(self) -> list[BrepImportResult]: ...
    @property
    def complete(self) -> bool: ...


def ensure_plugin_registered() -> None: ...


@overload
def import_breps(filename: str, heal: bool = False, *, allow_partial: Literal[False] = False) -> list[Brep]: ...


@overload
def import_breps(filename: str, heal: bool = False, *, allow_partial: Literal[True]) -> BrepImportReport: ...


@overload
def import_breps(filename: str, heal: bool = False, *, allow_partial: bool) -> list[Brep] | BrepImportReport: ...


def import_brep(filename: str, prim_path: str, heal: bool = False) -> Brep: ...
def export_brep(brep: Brep, filename: str, *, export_uv_curves: bool = True, shrink_face_domains: bool = True) -> None:
    """Export directly, retaining generated UV trims, caches, and the USD-path attribute on brep.

    Geometry types and source face domains are preserved. Export brep.copy()
    to isolate these side effects. Do not use the same Brep concurrently.
    """
    ...
def export_breps(breps: Sequence[Brep], filename: str, *, export_uv_curves: bool = True, shrink_face_domains: bool = True) -> None:
    """Export directly with the same input-side effects as export_brep."""
    ...
def append_breps(breps: Sequence[Brep], filename: str, *, export_uv_curves: bool = True, shrink_face_domains: bool = True) -> None:
    """Append directly with the same input-side effects as export_brep."""
    ...
def import_meshes(filename: str) -> list[PolyBrep]: ...
def import_mesh(filename: str, prim_path: str) -> PolyBrep: ...
def export_mesh(mesh: PolyBrep, filename: str) -> None: ...
def export_meshes(meshes: Sequence[PolyBrep], filename: str) -> None: ...
def append_meshes(meshes: Sequence[PolyBrep], filename: str) -> None: ...
def tessellate_file(
    input: str,
    output: str,
    *,
    chord_height_tolerance: float = 0.0,
    curve_angle_tolerance_deg: float = 25.0,
    surface_angle_tolerance_deg: float = 25.0,
    max_edge_length: float = 0.0,
    max_aspect_ratio: float = 0.0,
    heal: bool = False,
    threads: int = 0,
) -> list[MeshTessellationResult]: ...
def heal_file(input: str, output: str, *, threads: int = 0) -> list[BrepArrayHealResult]: ...
