// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/***************************************************************************/
/* NL_Bezier.h: Bezier Function Declarations                               */
/***************************************************************************/

#ifndef _NL_BEZIER_H
#define _NL_BEZIER_H

GW_EXPORT NL_FLAG N_BezGetDegreeElevationMatrix( NL_DEGREE, NL_INDEX, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_BezFuncMultiplyBezCrvMatrix( NL_DEGREE, NL_DEGREE, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_BezElevateDegree( NL_CPOINT *, NL_DEGREE, NL_INDEX, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_CPOINT * );
GW_EXPORT NL_FLAG N_BezFuncDegreeElevate( NL_REAL *, NL_DEGREE, NL_INDEX, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_REAL * );
GW_EXPORT NL_FLAG N_BezFuncMultiplyBezFunc( NL_REAL *, NL_DEGREE, NL_REAL *, NL_DEGREE, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_REAL * );
GW_EXPORT NL_FLAG N_BezSrfFuncMultiply( NL_REAL **, NL_DEGREE, NL_DEGREE, NL_REAL **, NL_DEGREE, NL_DEGREE, NL_RMATRIX *, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_REAL ** );
GW_EXPORT NL_FLAG N_BezFuncMultiplyBezCrv( NL_REAL *, NL_DEGREE, NL_CPOINT *, NL_DEGREE, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_CPOINT * );
GW_EXPORT NL_FLAG N_BezSrfMultiplySrfFunc( NL_REAL **, NL_DEGREE, NL_DEGREE, NL_CPOINT **, NL_DEGREE, NL_DEGREE, NL_RMATRIX *, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_CPOINT ** );
GW_EXPORT NL_FLAG N_BezCrvDotProduct( NL_CPOINT *, NL_DEGREE, NL_CPOINT *, NL_DEGREE, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_BezCrossProduct( NL_CPOINT *, NL_DEGREE, NL_CPOINT *, NL_DEGREE, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_CPOINT * );
GW_EXPORT NL_FLAG N_BezSrfDotProduct( NL_CPOINT **, NL_DEGREE, NL_DEGREE, NL_CPOINT **, NL_DEGREE, NL_DEGREE, NL_RMATRIX *, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_REAL **, NL_REAL ** );
GW_EXPORT NL_FLAG N_BezSrfCrossProduct( NL_CPOINT **, NL_DEGREE, NL_DEGREE, NL_CPOINT **, NL_DEGREE, NL_DEGREE, NL_RMATRIX *, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_CPOINT ** );
GW_EXPORT NL_FLAG N_BezSrfElevateDegree( NL_CPOINT **, NL_DEGREE, NL_INDEX, NL_RMATRIX *, NL_FLAG, NL_INDEX, NL_INDEX, NL_INDEX, NL_CPOINT ** );
GW_EXPORT NL_FLAG N_BezVolumeDegreeElevate( NL_CPOINT ***, NL_DEGREE, NL_INDEX, NL_RMATRIX *, NL_FLAG, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_CPOINT *** );
GW_EXPORT NL_FLAG N_BezSrfFuncElevateDegree( NL_REAL **, NL_DEGREE, NL_INDEX, NL_RMATRIX *, NL_FLAG, NL_INDEX, NL_INDEX, NL_INDEX, NL_REAL ** );
GW_EXPORT NL_FLAG N_BezEvalOneBasis( NL_DEGREE, NL_INDEX, NL_PARAMETER, NL_REAL * );
GW_EXPORT NL_FLAG N_BezEvalBasis( NL_DEGREE, NL_PARAMETER, NL_REAL * );
GW_EXPORT NL_FLAG N_BezCrvEvalPt( NL_CPOINT *, NL_DEGREE, NL_PARAMETER, NL_POINT * );
GW_EXPORT NL_FLAG N_BezFuncEvalPt( NL_REAL *, NL_DEGREE, NL_PARAMETER, NL_REAL * );
GW_EXPORT NL_FLAG N_BezSrfEvalPt( NL_CPOINT **, NL_DEGREE, NL_DEGREE, NL_PARAMETER, NL_PARAMETER, NL_POINT * );
GW_EXPORT NL_FLAG N_BezSrfFuncEvalPt( NL_REAL **, NL_DEGREE, NL_DEGREE, NL_PARAMETER, NL_PARAMETER, NL_REAL * );
GW_EXPORT NL_VOID N_BezDegreeReduceCoefs( NL_DEGREE, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_BezReduceDegree( NL_CPOINT *, NL_DEGREE, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL *, NL_CPOINT *, NL_REAL * );
GW_EXPORT NL_FLAG N_BezSrfReduceDegree( NL_CPOINT **, NL_DEGREE, NL_DEGREE, NL_FLAG, NL_INDEX, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL *, NL_CPOINT **, NL_REAL * );
GW_EXPORT NL_FLAG N_BezConicArcFromPtsAndTangents( NL_POINT, NL_VECTOR, NL_POINT, NL_VECTOR, NL_POINT, NL_POINT *, NL_REAL * );
GW_EXPORT NL_FLAG N_BezCircArcFromPtsAndTangents( NL_POINT, NL_VECTOR, NL_POINT, NL_VECTOR, NL_CPOINT *, NL_INDEX * );
GW_EXPORT NL_VOID N_BezSetConicWeight( NL_POINT, NL_POINT, NL_POINT, NL_REAL * );
GW_EXPORT NL_VOID N_BezConicSplit( NL_POINT *, NL_REAL, NL_POINT *, NL_REAL *, NL_POINT *, NL_REAL * );
GW_EXPORT NL_FLAG N_BezGetPowerConversionMatrix( NL_DEGREE, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_BezGetReparamMatrix( NL_DEGREE, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_BezInversePowerMatrix( NL_DEGREE, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_BezInverseReparamMatrix( NL_DEGREE, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_BezToPowerBasis( NL_CPOINT *, NL_DEGREE, NL_RMATRIX *, NL_PARAMETER, NL_PARAMETER, NL_CPOINT * );
GW_EXPORT NL_FLAG N_PowerBasisToBez( NL_CPOINT *, NL_DEGREE, NL_RMATRIX *, NL_PARAMETER, NL_PARAMETER, NL_CPOINT * );
GW_EXPORT NL_FLAG N_BezSrfToPower( NL_CPOINT **, NL_DEGREE, NL_DEGREE, NL_RMATRIX *, NL_RMATRIX *, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_CPOINT ** );
GW_EXPORT NL_FLAG N_BezSrfPowerToBez( NL_CPOINT **, NL_DEGREE, NL_DEGREE, NL_RMATRIX *, NL_RMATRIX *, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_CPOINT **);
GW_EXPORT NL_FLAG N_BezReparam( NL_CPOINT *, NL_DEGREE, NL_REAL *, NL_DEGREE, NL_INTEGER **, NL_CPOINT * );
GW_EXPORT NL_FLAG N_BezSplit( NL_CPOINT *, NL_DEGREE, NL_PARAMETER, NL_CPOINT *, NL_CPOINT * );
GW_EXPORT NL_FLAG N_BezCalcArcLength( NL_CPOINT *, NL_DEGREE, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_BezCalcLength( NL_CPOINT *, NL_DEGREE, NL_REAL, NL_REAL * );
GW_EXPORT NL_FLAG N_BezCubicFromPtsAndTangents( NL_POINT, NL_VECTOR, NL_POINT, NL_VECTOR, NL_POINT, NL_VECTOR, NL_POINT *, NL_POINT * );
GW_EXPORT NL_FLAG N_BezInterpNPts( NL_POINT *, NL_INDEX, NL_CPOINT * );
GW_EXPORT NL_FLAG N_BezInterp4Pts( NL_POINT *, NL_CPOINT * );
GW_EXPORT NL_FLAG N_BezFuncMultiplyBezCrv4D( NL_REAL *, NL_DEGREE, NL_CPOINT *, NL_DEGREE, NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_CPOINT * );
GW_EXPORT NL_FLAG N_BezCrvExtend( NL_CPOINT *, NL_DEGREE, NL_FLAG, NL_FLAG, NL_CPOINT * );
GW_EXPORT NL_FLAG N_BezSrfExtend4D( NL_SURFACE *, NL_FLAG, NL_FLAG, NL_FLAG, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_BezCenterRadiusFrom3CPts( NL_CPOINT, NL_CPOINT, NL_CPOINT, NL_POINT *, NL_REAL *, NL_REAL *, NL_REAL *, NL_POINT *, NL_POINT * );
GW_EXPORT NL_VOID N_BezCircArcFrom3Pts( NL_POINT, NL_POINT, NL_POINT, NL_CPOINT * );

#endif /* _NL_BEZIER_H */
