// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/**********************************************************************/
/* CrvShape.h: Curve Shape related funcitons                          */
/**********************************************************************/

#ifndef _CRVSHAPE_H
#define _CRVSHAPE_H

GW_EXPORT NL_FLAG N_CrvShapeModifyCPts( NL_CURVE *, NL_INDEX *, NL_REAL *, NL_INDEX, NL_PARAMETER, NL_VECTOR, NL_REAL, NL_REAL *, NL_FLAG );

GW_EXPORT NL_FLAG N_CrvShapeModifyWeight( NL_CURVE *, NL_INDEX, NL_PARAMETER, NL_REAL, NL_REAL *, NL_REAL *, NL_REAL *, NL_FLAG );

GW_EXPORT NL_FLAG N_CrvShapeRemoveKnots( NL_CURVE *, NL_REAL, NL_INDEX, NL_INDEX, NL_STACKS * );

GW_EXPORT NL_FLAG N_CrvShapeCreateBasis( NL_REAL, NL_DEGREE, NL_CFUN *, NL_FLAG, NL_STACKS * );

GW_EXPORT NL_FLAG N_CrvShapeWarp( NL_CURVE *, NL_PARAMETER, NL_PARAMETER, NL_INDEX, NL_INDEX, NL_INDEX, NL_CURVE *, NL_VECTOR, NL_CFUN *, NL_REAL, NL_REAL, NL_FLAG, NL_FLAG, NL_REAL **, NL_INDEX *, NL_INDEX *, NL_CURVE *, NL_STACKS *, NL_STACKS * );

GW_EXPORT NL_FLAG N_CrvShapeFlatten( NL_CURVE *, NL_PARAMETER, NL_PARAMETER, NL_INDEX, NL_INDEX, NL_INDEX, NL_LINESEG *, NL_PLANE *, NL_VECTOR, NL_REAL, NL_FLAG, NL_FLAG, NL_FLAG, NL_CURVE *, NL_STACKS *, NL_STACKS * );

GW_EXPORT NL_FLAG N_IsectCrvShapeLineCrv( NL_CURVE *, NL_LINESEG *, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_FLAG, NL_REAL, NL_POINT *, NL_PARAMETER *, NL_FLAG * );

GW_EXPORT NL_FLAG N_CrvShapeBend( NL_CURVE *, NL_PARAMETER, NL_PARAMETER, NL_INDEX, NL_CURVE *, NL_POINT, NL_REAL, NL_REAL, NL_FLAG, NL_FLAG, NL_INDEX *, NL_INDEX *, NL_CURVE *, NL_STACKS *, NL_STACKS * );

GW_EXPORT NL_FLAG N_CrvShapeDerivConstraints( NL_CURVE *, NL_PARAMETER *, NL_INDEX, NL_INDEX *, NL_VECTOR **, NL_INDEX **, NL_INDEX *, NL_FLAG, NL_RMATRIX *, NL_FLAG *, NL_STACKS * );

GW_EXPORT NL_FLAG N_CrvShapeAxialDeform( NL_CURVE *, NL_CFUN *, NL_REAL, NL_FLAG, NL_FLAG, NL_FLAG );

GW_EXPORT NL_FLAG N_CrvShapeInterp( NL_CURVE *, NL_POINT *, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_CURVE *, NL_STACKS * );

GW_EXPORT NL_FLAG N_CrvShapeApproxPts( NL_CURVE *, NL_POINT *, NL_INDEX, NL_INDEX, NL_INDEX, NL_REAL, NL_CURVE *, NL_FLAG *, NL_STACKS * );

GW_EXPORT NL_FLAG N_CrvShapeApproxPtsUpdate( NL_CURVE *, NL_POINT *, NL_INDEX, NL_INDEX, NL_INDEX, NL_REAL, NL_CURVE *, NL_FLAG *, NL_STACKS * );

GW_EXPORT NL_FLAG N_CrvShapeDerivConstraintsOver( NL_CURVE *, NL_PARAMETER *, NL_INDEX, NL_INDEX *, NL_VECTOR **, NL_INDEX **, NL_INDEX *, NL_FLAG, NL_RMATRIX *, NL_STACKS * );

#endif /* _CRVSHAPE_H */
