// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/********************************************************************************/
/* CrvCommon.h: Common Curve Function Declarations that act on NL_CURVE objects */
/********************************************************************************/

#ifndef _CRVCOMMON_H
#define _CRVCOMMON_H

/* Conics */

GW_EXPORT NL_FLAG N_CreateQuadraticArc( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateQuadraticArcTol( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateQuarticArc( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateQuarticArcTol( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateQuinticArc( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateQuinticArcTol( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateCircArc( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_FLAG, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateCircArcTol( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_FLAG, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CalcCircWeights( NL_REAL, NL_REAL, NL_FLAG, NL_REAL *, NL_INDEX * );
GW_EXPORT NL_FLAG N_CreateEllipticalArc( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_FLAG, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateEllipticalArcTol( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_FLAG, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateEllipticalArcAngType( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_FLAG, NL_FLAG, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateEllipticalArcAngTypeTol( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_FLAG, NL_FLAG, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateConicArc( NL_POINT, NL_VECTOR, NL_POINT, NL_VECTOR, NL_POINT, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CalcConicShapeFactor( NL_CURVE *, NL_REAL * );
GW_EXPORT NL_FLAG N_CalcConicImplicitEq( NL_CURVE *, NL_REAL * );
GW_EXPORT NL_FLAG N_ConicGetType( NL_CURVE *, NL_FLAG * );
GW_EXPORT NL_FLAG N_ConicCalcGeomDef( NL_CURVE *, NL_POINT *, NL_VECTOR *, NL_VECTOR *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_CreateCubicSemiCircle( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateBoundedCircArc( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_REAL, NL_FLAG, NL_CURVE *, NL_STACKS * );

#endif /* _CRVCOMMON_H */
