// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/**********************************************************************/
/* NL_Defines2.h: Routine Name Conversion from NLib to NLib2          */
/* convert old 8 letter names into new long name format               */
/**********************************************************************/

/* WARNING  DO NOT RUN THE NAME CHANGE MACRO AGAINST THIS FILE  */
/* IT WILL CHANGE THE DEFINE TO BE THE SAME FOR BOTH  */

#ifndef _NLIB2DEFINES_H
#define _NLIB2DEFINES_H

#define A_bilcpt  N_Combine4CPts
#define A_bilpoi  N_Combine4Pts
#define A_circpt  N_TranslateSum2CPts
#define A_cirpoi  N_TranslateSum2Pts
#define A_comcpt  N_Combine2CPts
#define A_compoi  N_Combine2Pts
#define A_cptpoi  N_CPtToPt
#define A_crocpo  N_Cross2CPts
#define A_difcpt  N_Diff2CPts
#define A_difpcp  N_DiffCPtPt
#define A_difpoi  N_Diff2Pts
#define A_dotcpo  N_Dot2CPts
#define A_dotcpt  N_Dot2CPtsIn4D
#define A_dotpoi  N_Dot2Pts
#define A_euccpt  N_CPtToPtNoW
#define A_euclid  N_CPtToPtEuclid
#define A_extcpc  N_CPtToWxWyWz
#define A_exteco  N_CPtToXYZ
#define A_extpoc  N_PtToXYZ
#define A_extwei  N_CPtGetW
#define A_extzco  N_CPtGetZ
#define A_getcpt  N_CPtFromWxWyWz
#define A_getpoi  N_PtFromXYZ
#define A_initcp  N_CopyCPt
#define A_initpo  N_CopyPt
#define A_magcpt  N_CPtMagnitude
#define A_magpoi  N_PtMagnitude
#define A_mapcpt  N_CPtToPtAndW
#define A_poicpt  N_PtToCPt
#define A_ratder  N_CPtRatDeriv
#define A_rewecp  N_CPtResetW
#define A_scacpo  N_ScaleCPtXYZ
#define A_scacpt  N_ScaleCPt
#define A_scapoi  N_ScalePt
#define A_sclcpt  N_ScaleCPtWithPtAndVector
#define A_setcpw  N_CPtSetW
#define A_setcpx  N_CPtSetX
#define A_setcpy  N_CPtSetY
#define A_setcpz  N_CPtSetZ
#define A_sumcpt  N_Sum2CPts
#define A_sumpcp  N_SumCPtAndPt
#define A_sumpoi  N_Sum2Pts
#define E_parval  N_KnotVectorIsParamOutOfBounds
#define E_endpar  N_KnotVectorIsEndParam
#define E_kntdef  N_KnotVectorIsValid
#define E_cursto  N_CrvIsSized
#define E_cfnsto  N_CrvIsFuncSized
#define E_curdef  N_CrvCountsAreValid
#define E_curwei  N_CrvWeightsAreValid
#define E_curinp  N_CrvIsValid
#define E_currev  N_CrvIsNotReversed
#define E_curcpd  N_CrvHasEqualCPts
#define E_curcpf  N_CrvReplaceEqualCPts
#define E_sursto  N_SrfIsSized
#define E_sfnsto  N_SrfIsFuncSized
#define E_surdef  N_SrfCountsAreValid
#define E_surwei  N_SrfWeightsAreValid
#define E_surinp  N_SrfIsValid
#define E_surcpd  N_SrfHasEqualCPts
#define G_ispgpg  N_PtsAreInPolygonGravityField
#define G_ispgpl  N_PtsAreInPolygon
#define G_ispplc  N_EPolygonIsClosed
#define G_isntlc  N_ENetIsClosed
#define G_ispppl  N_PtIsContainedByEPolygon
#define G_dolsin  N_LineSegs2dAreIntersecting
#define G_arecpl  N_CPtsAreColinear
#define G_arepos  N_PtsAreEqual
#define G_aretrl  N_PtsAreColinear
#define G_arevps  N_VectorsAreParallel
#define G_netbox  N_ENetGetBBox
#define G_makntl  N_ENetFromPts
#define G_makppl  N_EPolygonFromPts
#define G_ntlbre  N_ENetGetPts
#define G_pplbre  N_EPolygonGetPts
#define M_chkfop  N_FloatOpIsBad
#define M_iscman  N_CPtMatrixIsNULL
#define M_isiman  N_IntMatrixIsNULL
#define M_isrman  N_RealMatrixIsNULL
#define M_ispman  N_PtMatrixIsNULL
#define N_kntfsp  N_BasisFindSpan
#define N_kntfsm  N_BasisFindSpanAndMult
#define N_kntnsp  N_BasisGetSpanCount
#define N_kntmax  N_BasisFindGlobalMax
#define N_kntmma  N_BasisFindAllSpanMaxima
#define N_kntsls  N_BasisGetLongestAndShortestSpans
#define N_kntdkm  N_BasisGetKnotsAndMults
#define N_kntsca  N_BasisReparam
#define N_kntmer  N_GetCompatibleKnotArray
#define N_kntkvm  N_GetCompatibleKnotArrayMult
#define N_kntmik  N_GetCompatibleKnotVector
#define N_kntmrt  N_GetCompatibleKnotVectorToTol
#define N_kntref  N_BasisInsertKnots
#define N_kntadd  N_BasisSplitLongestSpan
#define N_kntrki  N_BasisSplitNLongestSpans
#define N_kntiml  N_BasisIncreaseKnotMult
#define N_kntcnd  N_BasisFindIndexNode
#define N_kntand  N_BasisFindIndexNodeArray
#define N_kntnds  N_BasisFindNodeSpan
#define N_kntikn  N_BasisFindKnotToTurnParamIntoNode
#define N_kntalb  N_BasisEval
#define N_kntadb  N_BasisDerivs
#define N_kntabu  N_BasisEvalArray
#define N_kntadu  N_BasisDerivsArray
#define N_kntbas  N_BasisIEval
#define N_kntbad  N_BasisIDerivs
#define N_kntbdk  N_BasisIKnotDeriv
#define N_kntadk  N_BasisKnotDerivs
#define N_kntask  N_BiBasisKnotDeriv
#define N_kntcad  N_CrvBasisDerivs
#define N_kntcbf  N_CrvBasisIEval
#define N_kntacd  N_CrvRatBasisDerivs
#define N_kntrcb  N_CrvRatBasisIEval
#define N_kntrcd  N_CrvRatBasisIDerivs
#define N_kntakr  N_CrvRatBasisKnotDeriv
#define N_kntrck  N_CrvRatBasisIKnotDeriv
#define N_curbox  N_CrvGetBBox
#define N_kntsad  N_SrfBasisDerivs
#define N_kntsbf  N_SrfBasisIEval
#define N_kntabd  N_SrfNonRatBasisDerivs
#define N_kntasd  N_SrfRatBasisDerivs
#define N_kntrsb  N_SrfRatBasisIEval
#define N_kntrsd  N_SrfRatBasisIDerivs
#define N_kntasr  N_SrfRatBasisKnotDeriv
#define N_kntrsk  N_SrfRatBasisIKnotDeriv
#define N_surbox  N_SrfGetBBox
#define N_curevn  N_CrvEval
#define N_curder  N_CrvDerivs
#define N_curtra  N_CrvTransform
#define N_cursca  N_CrvScale
#define N_curtrl  N_CrvTranslate
#define N_currot  N_CrvRotateAboutAxis
#define N_curkts  N_CrvReparam
#define N_toocki  N_CrvInsertKnot
#define N_toocde  N_CrvElevateDegree
#define N_surevn  N_SrfEvalPt
#define N_surder  N_SrfDerivs
#define N_surevg  N_SrfEvalPtGrid
#define N_sfnevg  N_SFuncEvalGrid
#define N_surtra  N_SrfTransform
#define N_sursca  N_SrfScale
#define N_surtrl  N_SrfTranslate
#define N_surrot  N_SrfRotateAtPt
#define N_surkts  N_SrfReparam
#define N_tooski  N_SrfInsertKnot
#define N_tooscx  N_SrfExtractIsoCrv
#define N_toosde  N_SrfElevateDegree
#define N_toosbc  N_SrfExtractBoundaryCrvs
#define N_sfnevn  N_SFuncEval
#define N_sfnder  N_SFuncDerivs
#define N_cfnevn  N_CFuncEval
#define N_cfnder  N_CFuncDerivs
#define S_getnes  N_AllocCNet
#define S_getnet  N_AllocCNetAndArrays
#define S_getkns  N_AllocKnotVector
#define S_getknt  N_AllocKnotVectorAndArray
#define S_getc2d  N_AllocCPt2dArray
#define S_getc1d  N_AllocCPt1dArray
#define S_getc2p  N_AllocCPtPtr2dArray
#define S_getc1p  N_AllocCPtPtr1dArray
#define S_getp2d  N_AllocPt2dArray
#define S_getp1d  N_AllocPt1dArray
#define S_getp2p  N_AllocPtPtr2dArray
#define S_getp1p  N_AllocPtPtr1dArray
#define S_getr1d  N_AllocReal1dArray
#define S_getr2d  N_AllocReal2dArray
#define S_getr3d  N_AllocReal3dArray
#define S_getr1p  N_AllocRealPtr1dArray
#define S_getr2p  N_AllocRealPtr2dArray
#define S_getsus  N_AllocSrf
#define S_getsur  N_AllocSrfAndArrays
#define S_getcus  N_AllocCrv
#define S_getcur  N_AllocCrvAndArrays
#define S_getpos  N_AllocCPolygon
#define S_getpol  N_AllocCPolygonAndArray
#define S_getcvs  N_AllocCValueAndArray
#define S_getcvl  N_AllocCValue
#define S_getsvs  N_AllocSValueAndArray
#define S_getsvl  N_AllocSValue
#define U_makcu1  N_CrvFromCPolygonAndKnotVector
#define U_makcu2  N_CrvFromCPtsAndKnots
#define U_makcu3  N_CrvFromCPtCoordsAndKnots
#define U_makknt  N_KnotVectorFromRealArray
#define U_maksu1  N_SrfFromCNetAndKnotVectors
#define U_maksu2  N_SrfFromCPtsAndKnots
#define U_maksu3  N_SrfFromCPtCoordsAndKnots
#define U_maknt1  N_CNetFromCPts
#define U_maknt2  N_CNetFromCPtCoords
#define U_makpl1  N_CPolygonFromCPts
#define U_makpl2  N_CPolygonFromCPtCoords
#define U_maksvl  N_SValueFromArray
#define U_makcvl  N_CValueFromArray
#define U_maksf1  N_SFuncFromKnotVectors
#define U_maksf2  N_SFuncFromKnots
#define U_makcf1  N_CFuncFromKnotVector
#define U_makcf2  N_CFuncFromKnots
#define U_kilsur  N_FreeSrf
#define U_kilcur  N_FreeCrv
#define U_kilsus  N_FreeSrfStruct
#define U_kilcus  N_FreeCrvStruct
#define U_kilnet  N_FreeCNet
#define U_kilc2d  N_FreeCPt2dArray
#define U_kilc1d  N_FreeCPt1dArray
#define U_kilknt  N_FreeKnotVector
#define U_kilr1d  N_FreeReal1dArray
#define U_kilr2d  N_FreeReal2dArray
#define U_kilr3d  N_FreeReal3dArray
#define U_kilsvl  N_FreeSValue
#define U_kilcvl  N_FreeCValue
#define U_issurn  N_SrfAreArraysNULL
#define U_iscurn  N_CrvAreArraysNULL
#define U_issurr  N_IsSrfRat
#define U_iscurr  N_IsCrvRat
#define U_iscfnn  N_CrvAreFuncArraysNULL
#define U_issfnn  N_SrfAreFuncArraysNULL
#define U_issurp  N_SrfIsDegen
#define U_iscur3  N_CrvIs3d
#define U_iscurc  N_CrvIsClosed
#define U_iscurl  N_CrvIsLine
#define U_issurc  N_SrfIsClosed
#define U_isp1dc  N_1dPtSetIsClosed
#define U_isp2dc  N_2dPtSetIsClosed
#define U_arecuc  N_CrvsAreCoincident
#define U_aresuc  N_SrfsAreCoincident
#define U_arecco  N_CrvsAreCombatible
#define U_dssupl  N_SrfIsSingular
#define U_iscurp  N_CrvIsDegen
#define U_arecpe  N_CPtsAreEqual
#define U_arecwe  N_CrvAreWeightsEqual
#define U_areswe  N_SrfAreWeightsEqual
#define U_iscup4  N_Crv4dIsDegen
#define U_iscuz0  N_CrvIsInZ0Plane
#define U_iscurf  N_CrvIsPlanar
#define U_issflt  N_SrfIsFlatCheap
#define U_issurf  N_SrfIsFlat
#define U_kntbre  N_KnotVectorGetKnots
#define U_curcop  N_CrvCopy
#define U_inicur  N_CrvInitArrays
#define U_curchk  N_CrvSizeArrays
#define U_curbre  N_CrvGetCPtsDegreeAndKnots
#define U_curdeg  N_CrvGetDegree
#define U_mapcpl  N_CrvGetEPolygon
#define U_curknp  N_CrvGetKnotVector
#define U_curpar  N_CrvGetParamBounds
#define U_curknt  N_CrvGetKnots
#define U_curpol  N_CrvGetCPts
#define U_curpwu  N_CrvGetCPtsAndKnots
#define U_curpku  N_CrvGetCPtsKnotVectorAndKnots
#define U_curspu  N_CrvSetCPtsAndKnots
#define U_getcur  N_AllocCrvArrays
#define U_curind  N_CrvGetArraySizes
#define U_defcur  N_CrvSetSizeIndices
#define U_curkts  N_CrvReparamToInterval
#define U_curcmp  N_CrvCompress
#define U_outcur  N_CrvWriteToFile
#define U_inpcur  N_CrvReadFromFile
#define U_currpr  N_CrvPruneRat
#define U_cureuc  N_CrvMakeNonRat
#define U_surnpk  N_SrfGetNetAndKnotVectors
#define U_surpwu  N_SrfGetCPtsAndKnots
#define U_surbre  N_SrfGetCPtsDegreesAndKnots
#define U_surdeg  N_SrfGetDegrees
#define U_mapcnt  N_SrfGetENet
#define U_surknp  N_SrfGetKnotVectors
#define U_surpar  N_SrfGetParameterBounds
#define U_surknt  N_SrfGetKnots
#define U_surnet  N_SrfGetCPts
#define U_surpku  N_SrfGetCPtsKnotVectorAndKnots
#define U_surspu  N_SrfSetCPtsAndKnots
#define U_surcop  N_SrfCopy
#define U_inisur  N_SrfInitArrays
#define U_surchk  N_SrfSizeArrays
#define U_getsur  N_AllocSrfArrays
#define U_surind  N_SrfGetArraySizes
#define U_defsur  N_SrfSetSizeIndices
#define U_exsden  N_SrfGetDenominatorFunc
#define U_surkts  N_SrfReparamToInterval
#define U_surcmp  N_SrfCompress
#define U_outsup  N_SrfWriteToFile
#define U_inpsup  N_SrfReadFromFile
#define U_surrpr  N_SrfPruneRat
#define U_sureuc  N_SrfMakeNonRat
#define U_sfnbre  N_SFuncGetCPts
#define U_inisfn  N_SFuncInitArrays
#define U_sfnchk  N_SFuncSizeArrays
#define U_sfnfuv  N_SFuncGetKnots
#define U_getsfn  N_AllocSFuncArrays
#define U_sfnind  N_SFuncGetArraySizes
#define U_defsfn  N_SFuncSetSizeIndices
#define U_sfndeg  N_SFuncGetDegrees
#define U_sfnknp  N_SFuncGetKnotVectors
#define U_sfnspk  N_SFuncGetArrayAndKnotVectors
#define U_inicfn  N_CFuncInitArrays
#define U_cfnchk  N_CFuncSizeArrays
#define U_cfnknt  N_CFuncGetKnots
#define U_getcfn  N_AllocCFuncArrays
#define U_cfnind  N_CFuncGetArraySizes
#define U_defcfn  N_CFuncSetSizeIndices
#define U_cfndeg  N_CFuncGetDegree
#define U_cfnknp  N_CFuncGetKnotVector
#define U_cfncpk  N_CFuncGetArrayAndKnotVector
#define U_inigcp  N_CrvProjectionInitArrays
#define U_polbre  N_CPolygonGetCPts
#define U_netbre  N_CNetGetCPts

/************************************************/
/* THIS LINE SEPARATES OLD NLIB2 FROM NEW NLIB2 */
/************************************************/

/* CrvFit.h and CrvFit.c */
#define N_fitbca  N_FitArcToPts
#define N_fitbia  N_FitArcToEndPtsAndTangents
#define N_fitcrd  N_FitRemoveKnotsAndDerivs
#define N_fitcpa  N_FitCalcCrvParamValues
#define N_fitfpa  N_FitCalcFuncParamValues
#define N_fitgfi  N_FitFuncInterp
#define N_fitgfu  N_FitFuncInterpGivenParams
#define N_fitkni  N_FitCrvCalcKnotVector
#define N_fitgci  N_FitCrvInterp
#define N_fitciu  N_FitCrvInterpGivenParams
#define N_fitknd  N_FitCalcKnotVectorEndDerivs
#define N_fitknt  N_FitCalcKnotVectorDeriv
#define N_fitgcd  N_FitCrvDerivs
#define N_fitgct  N_FitCrvTangents
#define N_fitcdu  N_FitCrvKnotsAndDerivs
#define N_fitctu  N_FitCrvKnotsAndDeriv
#define N_fitcsp  N_FitCubicSplineInterp
#define N_fitcfs  N_FitCrvCPtsFromSrfData
#define N_fitkna  N_FitCalcKnotVectorCrvApprox
#define N_fitgca  N_FitCrvApproxLstSq
#define N_fitcae  N_FitCrvApprox
#define N_fitcak  N_FitCrvApproxKnotsTangents
#define N_fitcat  N_FitCrvApproxTangents
#define N_fitcau  N_FitCrvApproxKnots
#define N_fitcba  N_FitCrvArcApprox
#define N_fitcca  N_FitCrvCubicApprox
#define N_fitcdm  N_FitCrvDerivsMatrix
#define N_fitcek  N_FitCrvApproxKnotsTol
#define N_fitcet  N_FitCrvApproxKnotsAndTangentsTol
#define N_fitcfd  N_FitCrvFirstDeriv
#define N_fitcfu  N_FitCrvFirstDerivAndKnots
#define N_fitcik  N_FitCrvKnotsAndTangents
#define N_fitcim  N_FitCrvMatrix
#define N_fitcir  N_FitCrvArcs
#define N_fitcis  N_FitCrvShape
#define N_fitclc  N_FitCrvCubic
#define N_fitclt  N_FitCrvCubicTangents
#define N_fitcon  N_FitCrvConics
#define N_fitcqa  N_FitCrvConicsApprox
#define N_fitcra  N_FitRemoveKnots
#define N_fitcrp  N_FitRemoveKnotsPriorities
#define N_fitctm  N_FitCrvDerivMatrix
#define N_fitcwl  N_FitCrvWeightedLstSq
#define N_fitcwp  N_FitCrvWeightedLstSqPeriodic
#define N_fitcwu  N_FitCrvWeightedLstSqKnots
#define N_fitgac  N_FitCrvApproxClosed
#define N_fitgah  N_FitCrvApproxDerivs
#define N_fitgcc  N_FitCrvApproxClosedConditions
#define N_fitgch  N_FitCrvHighDerivs
#define N_fitgcu  N_FitCrvClosedDerivsParamsKnots
#define N_fitghu  N_FitCrvDerivsKnots
#define N_fither  N_FitHermite
#define N_fitkad  N_FitCalcKnotsDerivs
#define N_fitkah  N_FitCalcKnotsEndDerivs
#define N_fitknf  N_FitCalcKnotsRandom
#define N_fitknh  N_FitCalcKnotsHighEndDerivs
#define N_fitlca  N_FitLocalCubicApprox
#define N_fitlin  N_FitLineToPts
#define N_fitlqa  N_FitConicToPts
#define N_fitpar  N_FitCrvParabArcs
#define N_fitpte  N_FitCrvLstSqEnds
#define N_fitptn  N_FitCrvPtsNormals
#define N_fitrma  N_FitCalcMatrix
#define N_fitscp  N_FitSmoothPts
#define N_fittau  N_FitCrvTangentsKnotsParams
#define N_fitCurveApproxPoints N_FitCrvApproxPts

/* SrfFit.h and SrfFit.cpp */
#define N_fitspa  N_FitCalcSrfParamValues
#define N_fitgsi  N_FitSrfToPts
#define N_fitsiu  N_FitSrfToPtsKnots
#define N_fitgsa  N_FitSrfLstSqApprox
#define N_fitknr  N_FitSrfCalcKnotVectors
#define N_fitpln  N_FitPlaneToPts
#define N_fitrp1  N_FitSrfCalcParams
#define N_fitrp2  N_FitCalcSrfParamsBoundary
#define N_fitrp3  N_FitCalcSrfParamsBoundarySrf
#define N_fitsab  N_FitSrfToPtsAndBoundary
#define N_fitsae  N_FitSrfApproxTol
#define N_fitsap  N_FitSrfToVariablePts
#define N_fitsas  N_FitSrfApproxShape
#define N_fitsat  N_FitSrfApproxTangentsTol
#define N_fitsau  N_FitSrfLstSqKnots
#define N_fitsfi  N_FitSrfFuncInterp
#define N_fitsib  N_FitSrfInterpBoundary
#define N_fitsis  N_FitSrfInterpShape
#define N_fitsit  N_FitSrfInterpTangents
#define N_fitslb  N_FitSrfInterpBicubic
#define N_fitspg  N_FitSphereToPtsGlobal
#define N_fitspl  N_FitSphereToPtsLocal
#define N_fitspr  N_FitSrfInterpParams
#define N_fitsra  N_FitSrfApproxRemoveKnots
#define N_fitsrb  N_FitSrfRemovalBoundary
#define N_fitsrc  N_FitSrfInterpRemoveKnots
#define N_fitsrt  N_FitSrfApproxRemoveKnotsTangents
#define N_fitste  N_FitSrfTangentError
#define N_fitsvp  N_FitSrfInterpVariablePts
#define N_fitPointsNormals N_FitPtsNormals

/* SrfLstSqFit.h and SrfLstSqFit.cpp */
#define N_fitsr1  N_FitSrfLstSqBoundary
#define N_fitsr2  N_FitSrfLstSqDerivs
#define N_fitsr3  N_FitSrfLstSqPeriodic

/* CrvApprox.h and CrvApprox.cpp */
#define N_appbca  N_ApproxCrvWithArcs
#define N_appbcw  N_ApproxContinuousCrvWithArcs
#define N_appber  N_CrvArePtsWithinTol
#define N_appbpe  N_CrvIsPolygonWithinTol
#define N_appcir  N_ApproxCircArcWithCrv
#define N_appcos  N_ApproxCrvOnSrfWithCrv
#define N_appcra  N_ApproxArcWithCrv
#define N_appcu1  N_CalcNumCPtsToApproxArc
#define N_appcu2  N_ApproxCircArcWithCrvData
#define N_appgca  N_ApproxNurbsWithNonRatCrv
#define N_appgck  N_ApproxNurbsWithCrvKnots
#define N_appnca  N_ApproxG1CrvWithCrv
#define N_appncp  N_GetPtsForCrvApprox
#define N_apppca  N_ApproxProcCrvWithCrv
#define N_apppcp  N_GetPtsForCrvApproxProc
#define N_apppcf  N_ApproxProcCrvWithCrvFit

/* SrfApprox.h and SrfApprox.cpp */
#define N_appccp  N_ApproxConeWithSrf
#define N_appgsa  N_ApproxNurbsWithNonRatSrf
#define N_apprev  N_ApproxRevolvedSrfWithSrf
#define N_appsbs  N_ApproxSubSrfWithSrf
#define N_appsun  N_ApproxNormalSrfWithSrf
#define N_appsph  N_ApproxSphereWithSrf
#define N_apptor  N_ApproxTorusWithSrf

/* CrvShape.h and CrvShape.cpp */
#define N_shacab  N_CrvShapeApproxPts
#define N_shacap  N_CrvShapeApproxPtsUpdate
#define N_shacax  N_CrvShapeAxialDeform
#define N_shacbe  N_CrvShapeBend
#define N_shacca  N_CrvShapeDerivConstraintsOver
#define N_shaccb  N_CrvShapeDerivConstraints
#define N_shacfl  N_CrvShapeFlatten
#define N_shacin  N_CrvShapeInterp
#define N_shacmw  N_CrvShapeModifyWeight
#define N_shacra  N_CrvShapeRemoveKnots
#define N_shacrb  N_CrvShapeCreateBasis
#define N_shacrp  N_CrvShapeModifyCPts
#define N_shacwa  N_CrvShapeWarp
#define N_shalci  N_IsectCrvShapeLineCrv

/* SrfShape.h and SrfShape.cpp */
#define N_shasab  N_SrfShapeAxialBend
#define N_shasap  N_SrfShapeApproxPts
#define N_shasax  N_SrfShapeAxialDeform
#define N_shasca  N_SrfShapeDerivConstraints
#define N_shascb  N_SrfShapeCentralBend
#define N_shascd  N_SrfShapeConstraints
#define N_shasfl  N_SrfShapeFlatten
#define N_shasin  N_SrfShapeInterp
#define N_shasmw  N_SrfShapeModifyWeight
#define N_shaspw  N_SrfShapePolylineWarp
#define N_shasra  N_SrfShapeRemoveKnots
#define N_shasrb  N_SrfShapeCreateRatBasis
#define N_shasrp  N_SrfShapeModifyCPts
#define N_shasrw  N_SrfShapeRegionWarp

/* CrvOffset.h and CrvOffset.cpp */
#define N_appfoc  N_CrvOffsetFuncVariableDir
#define N_appfocN N_CrvOffsetFuncConstantDir
#define N_appoca  N_CrvOffsetApprox
#define N_appocp  N_CrvOffset
#define N_appocs  N_CrvOffsetPtSampling

/* SrfOffset.h and SrfOffset.cpp */
#define N_appfos  N_SrfOffsetFunc
#define N_apposs  N_SrfOffset

/* Spiral.h and Spiral.cpp */
#define N_appcSpiral N_CrvApproxSpiral
#define N_appsSpiral N_SrfApproxSpiral
#define N_SrfApproxSpiral N_CreateSpiralSrf

/* SrfTool.h and SrfTool.cpp */
#define N_toossp  N_SrfSplit
#define N_toosik  N_SrfInsertKnotPt
#define N_toosdc  N_SrfDecomposeToBez
#define N_toosrf  N_SrfInsertKnots
#define N_SrfReplaceKnotVector  N_SrfInsertKnots
#define N_toossg  N_SrfExtractPatch
#define N_toosrm  N_SrfRemoveKnotConditional
#define N_toosrb  N_SrfRemoveOneKnot
#define N_toosra  N_SrfRemoveAllKnots
#define N_tooscl  N_SrfRemoveAllKnotsArcLen
#define N_toosdr  N_SrfReduceDegree
#define N_toosda  N_SrfReduceDegreeToTol
#define N_toosco  N_MakeSrfsCompatibleUV
#define N_tooMakeSrfsCompatible  N_MakeSrfsCompatible
#define N_toosct  N_SrfReparmAndRemoveKnotsKeepBoundaries
#define N_toojts  N_SrfJoin
#define N_toordp  N_SrfRemoveDegenPatch

#define N_toosrp  N_SrfRemoveKnotMultiple
#define N_toosrr  N_SrfRemoveKnots
#define N_toosrd  N_SrfRemoveKnot
#define N_toosrt  N_SrfRemoveKnotsKeepBoundaries
#define N_tooste  N_SrfCrossBoundaryDerivErr
#define N_toosrk  N_SrfRemoveKnotsConstraints
#define N_toosnt  N_SrfNetworkTopology

/* SrfSymbol.h and SrfSymbol.cpp */
#define N_symbsf  N_SrfMaxFirstDeriv
#define N_symbss  N_SrfMax2ndDeriv
#define N_sympsd  N_DotProductTwoSrfs
#define N_sympcs  N_CrossProductTwoSrfs
#define N_symsss  N_SumDiffTwoSrfs
#define N_sympks  N_ConstantMultiplySrf
#define N_symcms  N_CombineTwoSrfs
#define N_symspc  N_SumDiffSrfVector
#define N_symsnd  N_FirstDerivSrfNonRatSrf
#define N_symsrd  N_FirstDerivSrfRatSrf
#define N_symsdk  N_KDerivSrf
#define N_symsna  N_AllDerivSrfNonRatSrf
#define N_symsda  N_AllDerivSrfNurbsSrf
#define N_symnor  N_NormalSrfNurbsSrf_UU
#define N_symsuu  N_SecondDerivSrfRatSrf
#define N_symsuv  N_MixedPartialDerivSrfRatSrf_UV
#define N_symsvv  N_SecondDerivSrfRatSrf_VV
#define N_symcbn  N_CrossBoundDerivCrvNonRatSrf
#define N_symcbr  N_CrossBoundDerivCrvNurbsSrf
#define N_symbsd  N_MaxDiffTwoSrfs
#define N_symbsk  N_SrfMaxChangeMovingKnot
#define N_symskd  N_DerivSrfNonRatSrfKnot
#define N_symskr  N_DerivSrfRatSrfKnot

/* SrfPoly.h and SrfPoly.cpp */
#define N_splevn  N_SrfPowerBasisEvalPt
#define N_splrep  N_SrfPowerBasisReparam
#define N_splder  N_SrfPowerBasisEvalDerivs

/* SrfNurb.h and SrfNurb.cpp */
#define N_surcrv  N_SrfEvalPtCurvature
#define N_suresc  N_SrfEvalPtCrvOnSrf
#define N_surmpv  N_SrfMaxMagnitudePosVectors
#define N_surmwp  N_SrfMinMaxWeightPosVectors
#define N_surnor  N_SrfEvalPtPtDerivNormal
#define N_surnor1 N_SrfEvalPtPtDerivNormalFast
#define N_surunc  N_SrfUnclamp
#define N_suruuv  N_SrfUnclampKnotVector
#define N_surprj  N_SrfProjectOntoPlane
#define N_surrev  N_SrfReverse
#define N_surxscCMAX  N_SrfLargeExtendToCrv
#define N_surtyp  N_SrfType
#define N_surgdp  N_SrfFindDegenPatch
#define N_surcgc  N_SrfIsClosedSmooth
#define N_surnrp  N_SrfEvalPtPtDerivNormalPole
#define N_surnrp1 N_SrfEvalPtNormalAtPole
#define N_surext  N_SrfMaxDiagDistBBox
#define N_surdcp  N_SrfEvalPtDerivCPt

#define N_surswe  N_SrfScaleWeights
#define N_suresp  N_SrfEvenSpacedPts
#define N_surxsd  N_SrfExtendByDist
#define N_surxsc  N_SrfExtendToCrv
#define N_surdrk  N_SrfDerivKnot
#define N_surmbc  N_SrfModifyBoundaryCrv
#define N_surrdr  N_SrfEvalPtDerivs
#define N_surbsd  N_SrfMaxSecondDeriv
#define N_surndr  N_SrfEvalPtNormalDeriv
#define N_surbod  N_SrfOffsetGetMaxDeriv
#define N_surngp  N_SrfGetGridPtsNormals
#define N_surbnd  N_SrfGetMaxSecondDeriv
#define N_surfod  N_SrfOffsetGetFirstSecondDerivs
#define N_sureve  N_SrfEvalPtDerivsUnbounded
#define N_surxsr  N_SrfExtendByParamDist

/* SrfGeom.h and SrfGeom.cpp */
#define N_gprsin  N_SrfGetClosestPt
#define N_gprsin1 N_GetClosestPtOnSrf
#define N_gprsti  N_InvertTangentSrfCrv
#define N_gprsnp  N_ConvertNurbsToPowerBasis
#define N_gprspn  N_ConvertPiecesToNurbs
#define N_gprsme  N_SrfGetAverageLen
#define N_gprsla  N_ApproxSrfWithQuadSrf
#define N_gprsrr  N_SrfReparmRat
#define N_gprsap  N_SrfReparamArcLength
#define N_gprpsp  N_SrfProjectPts

/* SrfCommon.h and SrfCommon.cpp */
#define N_cmsbil  N_CreateSrfCornerPts
#define N_cmsgcl  N_CreateSrfExtrudeCrv
#define N_cmsccp  N_CreateCylCone
#define N_cmselp  N_CreateEllipticalCylCone
#define N_cmsrls  N_CreateRuledSrf
#define N_cmsrul  N_CreateRuledSrfFromBoundaryCrvs
#define N_cmsrev  N_CreateRevolvedSrf
#define N_cmssph  N_CreateSphere
#define N_cmstor  N_CreateTorus
#define N_cmspar  N_CreateParaboloid
#define N_cmsell  N_CreateEllipsoid
#define N_cmshyp  N_CreateHyperboloid
#define N_cmsgco  N_CreateRuledSrfBetweenCrvAndPt

/* SrfBasic.h and SrfBasic.cpp */
#define S_getsua  N_AllocArraySrfPtrs
#define S_getsu1  N_AllocArraySrfPtrsInit
#define S_getss3  N_Alloc2dArraySrfPtrs
#define S_getsu3  N_Alloc2dArraySrfPtrsParameters
#define U_corsur  N_CreateSrfFromCoordFuncs
#define U_makspl  N_CreateSplineSrf
#define U_nadsur  N_CreateSrfFromNumAndDen
#define U_surcor  N_SrfGetCoordFuncs
#define U_surnad  N_SrfGetNumAndDen
#define U_surpcl  N_ClampSrfAtParams
#define U_swapuv  N_SwapUV
#define U_surrnr  N_SrfRatToNonRat
#define U_surnrr  N_SrfNonRatToRat
#define U_maksco  N_MakeSrfsRatCompatible
#define U_inpsur  N_CreateSrfFromDataFile
#define U_outsur  N_WriteSrf
#define U_outsrs  N_WriteSrfArray
#define U_prtsur  N_PrintSrfData
#define U_sutigs  N_WriteSrfToIgesFile
#define U_inpsrs  N_ReadSrfArray

/* SrfAdv.h and SrfAdv.cpp */
#define N_asccpg  N_ReparmCrvsIsectPt
#define N_ascswu  N_CreateSwungSrf
#define N_ascgsk  N_CreateSkinSrf
#define N_ascask  N_CreateSkinSrfApprox
#define N_ascgsu  N_CreateSkinSrfParams
#define N_ascasu  N_CreateSkinSrfApproxParams
#define N_ascase  N_CreateSkinSrfApproxTol
#define N_ascici  N_GetIsoCrvClosestCrv
#define N_ascssk  N_CreateSkinSpine
#define N_asctsw  N_CreateTransSweepSrf
#define N_asccbv  N_CreateBVectors
#define N_ascswe  N_CreateSweepSrf
#define N_ascgor  N_CreateGordonSrf
#define N_ascblc  N_CreateCoonsSrf
#define N_ascbcc  N_CreateCoonsSrfTwist
#define N_ascdfs  N_CreateDataBoundaryDerivs
#define N_ascdfv  N_CreateSkinSrfBoundaryDerivs
#define N_asckim  N_MergeKnotVectors
#define N_ascsbc  N_CreateSkinSrfBoundaryContinuity
#define N_ascsws  N_CreateSweepScale
#define N_ascSweepCrossTangentCurve  N_SweepCrossTangentCrv
#define N_ascadf  N_AdjustDerivSrf
#define N_ascgws  N_AdjustWeightScale
#define N_ascacb  N_ApproxCrossBoundaryDerivs
#define N_ascbbc  N_CreateCoonsBoundaryCrvs
#define N_asccbd  N_CreateCrossBoundaryDerivCrv
#define N_ascnpi  N_FillNSidedHole
#define N_ascgt1  N_Get4CornerTwistVectors
#define N_asccd2  N_CrossBoundaryDerivCrv
#define N_asccd3  N_Create4CrossBoundaryDerivCrvs
#define N_ascgtn  N_CreateTensorProductSrf
#define N_ascbc3  N_CreateCoonsSrfCrossBoundaryDerivs
#define N_ascske  N_CreateSkinSrfInterp
#define N_ascdvf  N_CrossBoundaryDerivsVectorField
#define N_ascdfb  N_CreateDerivField

/* FrameBasic.h and FrameBasic.cpp */
#define U_kilpol  N_FreeCPolygon
#define S_getpps  N_AllocPtPolygonStruct
#define S_getppl  N_AllocPtPolygon
#define S_getpp2  N_Alloc1dPtPolygon
#define S_getppa  N_Alloc1dPtPolygonPtrs
#define G_intcpl  N_IsectLinePolygon
#define G_polbox  N_PolygonGetBBox
#define G_polleg  N_PolygonGetClosestLegIndex
#define G_pyarea  N_PolygonGetArea
#define G_defppl  N_PolygonSetIndex
#define G_poloff  N_PolygonOffset
#define G_netleg  N_NetGetClosestLegIndex

/* FuncsBasic.h and FuncsBasic.cpp */
#define S_getcf2  N_AllocCrvFuncArray
#define S_getcfn  N_AllocCrvFunc
#define S_getcfs  N_AllocCrvFuncStack
#define U_kilcfn  N_FreeCrvFunc
#define U_cfncmp  N_CrvFuncCompact
#define U_cfncop  N_CrvFuncCopy
#define U_prtcfn  N_CrvFuncPrint
#define U_cfnkts  N_CrvFuncReparam
#define U_cfncvl  N_CrvFuncCntrlVal
#define U_cfnfku  N_CrvFuncCntrlValKnotVector
#define U_cfnfuu  N_CrvFuncCntrlValKnots
#define U_cfnbre  N_CFuncGetData
#define U_cfnsfu  N_CrvFuncSetPtrs
#define S_getsf3  N_Alloc2dArraySrfFunc
#define S_getsfn  N_AllocSrfFunc
#define S_getsfs  N_AllocSrfFuncData
#define U_kilsfn  N_FreeSrfFuncData
#define U_sfncmp  N_SrfFuncCompact
#define U_sfncop  N_SrfFuncCopy
#define U_prtsfn  N_SrfFuncPrint
#define U_sfnsvl  N_SrfFuncCntrlVal
#define U_sfnknt  N_SrfFuncGetKnots
#define U_sfnkts  N_SrfFuncScale
#define U_sfnsfu  N_SrfFuncSetPtrs
#define N_SFuncEval N_SrfFuncEvalPt

/* FuncsAdv.h  and FuncsAdv.cpp */
#define N_cfnrbf  N_CrvFuncEvalRatBasis
#define N_cfndrk  N_CrvFuncEvalDerivsAtKnot
#define N_gprcfi  N_CrvFuncEvalInvertPt
#define N_gprkvm  N_MapKnotsBetweenCrvFuncAndKnotVector

#define N_toocfr  N_CrvFuncRefine
#define N_toocfe  N_CrvFuncDegreeElevate
#define N_toocfi  N_CrvFuncInsertKnot
#define N_toocfd  N_CrvFuncDecompose

#define N_sympff  N_CrvFuncMultiplyCrvFunc
#define N_sympfc  N_CrvFuncMultiplyCrv
#define N_symscf  N_CrvFuncSumDiffCrvFunc
#define N_symfdr  N_CrvFuncDeriv
#define N_symfkd  N_CrvFuncDerivKnot
#define N_symfkh  N_CrvFuncHigherDerivKnot
#define N_sympf4  N_CrvFuncMultiplyCrv4d
#define N_sympkf  N_CrvFuncMultiplyConstant

#define N_sfnrbf  N_SrfFuncEvalRatBasis
#define N_sfndrk  N_SrfFuncDerivFuncAtKnot

#define N_toosfr  N_SrfFuncRefine
#define N_toosfm  N_SrfFuncRemoveKnot
#define N_toosfe  N_SrfFuncDegreeElevate
#define N_toosfi  N_SrfFuncInsertKnot
#define N_toosfd  N_SrfFuncDecompose
#define N_symksf  N_SrfFuncMultiplyConstant
#define N_sympsf  N_SrfFuncMultiplySrfFunc
#define N_sympfs  N_SrfFuncMultiplySrf
#define N_symssf  N_SrfFuncSumDiffSrfFunc
#define N_symsfd  N_SrfFuncDerivFunc
#define N_symsfk  N_SrfFuncFuncDerivFuncAtKnot

/* CrvTool.h and CrvTool.cpp */
#define N_toocsp  N_CrvSplit
#define N_toocik  N_CrvInverseKnotInsert
#define N_toocdc  N_CrvDecomposeBez
#define N_tooccp  N_CrvDecomposeContinuity
#define N_toocrf  N_CrvRefine
#define N_toocsg  N_CrvExtractCrvSeg
#define N_toocrm  N_CrvRemoveKnot
#define N_toocrb  N_CrvRemoveKnotMaxErr
#define N_toocra  N_CrvRemoveKnots
#define N_toocac  N_CrvRemoveKnotsParams
#define N_toocdr  N_CrvReduceDegreeOnce
#define N_toocda  N_CrvReduceDegree
#define N_toocco  N_CrvsMakeCompatible
#define N_toocco1 N_CrvsMakeCompatibleKnotTol
#define N_toocct  N_CrvsMakeCompatibleAdjKnots
#define N_toords  N_CrvRemoveDegenSegs
#define N_tooccc  N_CrvExtractSegClosed

/* CrvPoly.h and CrvPoly.cpp */
#define N_cplevn  N_CrvPowerBasisEvalPt
#define N_cplrep  N_CrvPowerBasisReparam
#define N_cplder  N_CrvPowerBasisEvalDerivs

/* CrvNurb.h and CrvNurb.cpp */
#define N_curcrv  N_CrvEvalCurvature
#define N_curtan  N_CrvEvalTangent
#define N_curfre  N_CrvEvalFrenetFrame
#define N_curmwp  N_CrvGetMinMaxWeightsAndPts
#define N_curunc  N_CrvUnclamp
#define N_curunu  N_CrvUnclampKnots
#define N_curpoi  N_CrvDegenFromPt
#define N_curlin  N_CrvLineFromPtAndVector
#define N_curprj  N_CrvProjectOntoPlane
#define N_currev  N_CrvReverse
#define N_curext  N_CrvGetBBoxMaxDiagDist
#define N_curmpv  N_CrvGetMaxPosVector
#define N_curipv  N_CrvGetMinPosVector
#define N_curg1s  N_CrvGetG1Segs
#define N_curglc  N_CrvGetLinearSegs
#define N_curgds  N_CrvGetDegenSegs
#define N_curtyp  N_CrvGetType
#define N_curcdr  N_CrvGetCurvatureDeriv
#define N_curcgc  N_CrvIsClosedContinuity
#define N_curln2  N_CrvLineFrom2Pts
#define N_curtrn  N_CrvFromCrvTranslation
#define N_CrvScaleWeights  N_CrvScaleCPts

/* CrvGeom.h and CrvGeom.cpp */
#define N_gprpin  N_CrvClosestPt
#define N_gprcnp  N_CrvNurbsToPiecewise
#define N_gprcpn  N_CrvPiecewiseToNurbs
#define N_gprcle  N_CrvArcLength
#define N_gprgcp  N_CrvClosestPtMultiple
#define N_gprcla  N_ApproxCrvWithPolyline
#define N_gprpal  N_CrvPercentageAlongPt
#define N_gprpcp  N_CrvProjectPts

/* CrvCommon.h and CrvCommon.cpp */
#define N_conci2  N_CreateQuadraticArc
#define N_conci4  N_CreateQuarticArc
#define N_conci5  N_CreateQuinticArc
#define N_concir  N_CreateCircArc
#define N_conciw  N_CalcCircWeights
#define N_conell  N_CreateEllipticalArc
#define N_Ellipse N_CreateEllipticalArcAngType
#define N_conarc  N_CreateConicArc
#define N_consha  N_CalcConicShapeFactor
#define N_conimp  N_CalcConicImplicitEq
#define N_contyp  N_ConicGetType
#define N_congeo  N_ConicCalcGeomDef
#define N_concsc  N_CreateCubicSemiCircle
#define N_conbca  N_CreateBoundedCircArc

/* CrvBasic.h and CrvBasic.cpp */
#define S_getcu2  N_Alloc1dArrayCrvs
#define S_getcua  N_AllocArrayCrvPtrs
#define S_getcu1  N_AllocArrayCrvPtrsAndData
#define S_getcub  N_AllocArrayRealCrvPtrs
#define S_getcuc  N_AllocArrayTripleCrvPtrs
#define S_getcs3  N_Alloc2dArrayCrvPtrs

#define U_makcpl  N_CreateCrvFromPowerBasis
#define U_nadcur  N_CreateCrvFromNumAndDenom
#define U_corcur  N_CreateCrvFromCoordFuncs

#define U_curppk  N_CrvDetachPolygonKnot
#define U_curnad  N_CrvGetNumAndDenom
#define U_curcor  N_CrvGetCoordFuncs
#define U_excden  N_CrvGetDenomCrvFunc
#define U_curpcl  N_CrvClampKnot
#define U_cur3t2  N_Crv3dTo2d
#define U_cur2t3  N_Crv2dTo3d
#define U_currnr  N_CrvRatToNonRat
#define U_curnrr  N_CrvNonRatToRat
#define U_makcco  N_CrvsMakeRatCompatible
#define U_outcua  N_CrvArrayWriteToFile
#define U_prtcur  N_CrvPrint
#define U_inpcua  N_CrvArrayReadFromFile
#define U_inpcup  N_CrvReadFromFilePtr
#define U_outcup  N_CrvWriteToFilePtr
#define U_cpligs  N_CrvWriteIgesCPolygon
#define U_cutigs  N_CrvWriteIges

/* BasisBasic.h and BasisBasic.cpp */
#define S_getkn2  N_Alloc1dArrayKnotVectors
#define S_getkpa  N_Alloc1dArrayKnotVectPtrs
#define U_defknt  N_SetKnotIndex
#define U_prtknt  N_KnotsPrint
#define U_kntcop  N_KnotsCopy
#define U_kntchk  N_KnotsCheck
#define U_kntref  N_KnotsRefine
#define U_kntadd  N_KnotsAdd

#define N_symkvm  N_MakeKnotsCompatible

/* CrvAdv.h and CrvAdv.cpp */
#define N_curevr  N_CrvEvalPt
#define N_currdr  N_CrvDerivsAtKnot
#define N_curali  N_CrvAlign
#define N_curswe  N_CrvScaleCPts
#define N_curesp  N_CrvEvalEvenSpacedPts
#define N_curxcd  N_CrvExtendByDist
#define N_curxcp  N_CrvExtendToPt
// #define N_curmep  N_CrvModifyEndPt
#define N_curdrk  N_CrvEvalDerivAtKnot
#define N_curbsd  N_CrvGetMax2ndDeriv
#define N_curodr  N_CrvPlanarOffsetGetDeriv
#define N_curbod  N_CrvOffsetGetMax2ndDeriv
#define N_curfod  N_CrvOffsetGetDeriv
#define N_curxcr  N_CrvExtendByParamDist
#define N_cureve  N_CrvEvalUnboundedPtsAndDerivs
#define N_curadm  N_CrvGetAveragePosMag

#define N_tooccl  N_CrvRemoveAllKnotsArcLen
#define N_toocrr  N_CrvRemoveAllKnots
#define N_toocrc  N_CrvRemoveAllKnotsConstraints
#define N_tooacc  N_CrvsMakeCompatibleApprox
#define N_tooacr  N_CrvsMakeCompatibleKnotRemove
#define N_tooatc  N_CrvsMakeCompatibleConstraints
#define N_tooatr  N_CrvsMakeCompatibleFast
#define N_tooclt  N_CrvRemoveKnotsTangentConstraints
#define N_toocrd  N_CrvRemoveKnotsDerivConstraints
#define N_toocsc  N_CrvMakeCompatibleWithSrf
#define N_toocrp  N_CrvRefineToKnotVector

#define N_symbcp  N_CrvGetMaxFirstDeriv
#define N_symcpp  N_CrvGetMaxSecondDeriv
#define N_symcr2  N_CrvGetRatSecondDeriv
#define N_sympcd  N_CrvDotCrv
#define N_symscc  N_CrvSumDiffCrv
#define N_sympcc  N_CrvCrossMultiplyCrv
#define N_symcpc  N_CrvSumDiffVector
#define N_symcnd  N_CrvNonRatGetFirstDeriv
#define N_symcrd  N_CrvRatGetFirstDeriv
#define N_symcna  N_CrvNonRatGetDerivCrvsAll
#define N_symcda  N_CrvGetDerivCrvsAll
#define N_symcdk  N_CrvMakeDerivCrv
#define N_symbcd  N_CrvDiffCrvGetMaxChange
#define N_symbkd  N_CrvMoveKnotGetMaxChange
#define N_symckd  N_CrvNonRatEvalDeriv
#define N_symckh  N_CrvEvalHighDerivsKnot
#define N_symckr  N_CrvEvalFirstDerivKnot
#define N_symrk2  N_CrvEvalSecondDerivKnot
#define N_sympkc  N_ConstantMultiplyCrv
#define N_symcmc  N_CrvCombine
#define N_sympk4  N_ConstantMultiplyCrv4d

#define N_gprcrr  N_CrvReparamRat
#define N_gprcew  N_CrvReparamWeights

#define N_gprcrp  N_SrfReparamFunc
#define N_gprcap  N_SrfReparamMultKnots
#define N_gprsew  N_SrfReparamWeights

/* NL_Geom.h and NL_Geom.cpp */
#define G_vecdot  N_VectorDot
#define G_vecdop  N_VectorDotRef
#define G_veccro  N_VectorCross
#define G_veccrp  N_VectorCrossRef
#define G_vecsca  N_VectorScale
#define G_vecrev  N_VectorReverse
#define G_vecrvp  N_VectorReverseInPlace
#define G_vecrwv  N_VectorReverseVector
#define G_vecrwp  N_VectorReverseVectorInPlace
#define G_vecscp  N_VectorScaleRef
#define G_vecsum  N_VectorSum
#define G_veccmb  N_VectorCombine
#define G_vecdif  N_VectorDiff
#define G_vecdcp  N_VectorDiffCPts
#define G_vecdir  N_VectorDir
#define G_vecmak  N_VectorCreate
#define G_veccop  N_VectorCopy
#define G_vecmix  N_VectorMixMultiply
#define G_vecmag  N_VectorMagnitude
#define G_vecmap  N_VectorMagnitudeRef
#define G_vecnor  N_VectorNormalize
#define G_vecnip  N_VectorNormalizeRef
#define G_vecper  N_VectorPerpendicular
#define G_vecpfv  N_VectorPtAlongVector
#define G_veccos  N_VectorsCosAngle
#define G_vecang  N_VectorsAngle
#define G_vecdan  N_VectorDirectedAngle

#define G_intlnl  N_IsectLineLine
#define G_intlsg  N_IsectLineSegs
#define G_2dLineSegmentsAreIntersecting  N_LineSegs2dAreIntersecting
#define G_intlnp  N_IsectLinePlane
#define G_intplp  N_IsectPlanePlane

#define G_prjpln  N_ProjectPtLine
#define G_prjpab  N_ProjectPtLineParam
#define G_prjppl  N_ProjectPtPlane
#define G_prjphp  N_ProjectPtQuad
#define G_polppr  N_ProjectPtClosePolyPt

#define G_dispop  N_DistPtPt
#define G_dispp2  N_DistPtPt2d
#define G_disqpp  N_DistSqPtPt
#define G_disqp2  N_DistSqPtPt2d
#define G_dispab  N_DistPtLineSeg
#define G_disqab  N_DistPerpPtLineSeg
#define G_dispol  N_DistPolygon
#define G_discpl  N_DistCPolygon
#define G_discpp  N_DistCptCpt
#define G_discpo  N_DistCptCptHomo
#define G_displn  N_DistPtInfLine
#define G_disppl  N_DistPtPlane
#define G_dispnp  N_DistSignedPtPlane
#define G_dispnl  N_DistSignedPtLine
#define G_dispca  N_DistPtArc
#define G_dislci  N_DistMaxLineArc
#define G_discpw  N_DistCPolygonHomo

#define G_linbox  N_LineCalcBBox
#define G_linsfl  N_LineSetBoundingFlag
#define G_lindir  N_LineGetDir
#define G_linbre  N_LineGetData

#define G_po1ext  N_Pts1dGetMaxExtent
#define G_po1box  N_Pts1dCalcBBox
#define G_po2ext  N_Pts2dGetMaxExtent
#define G_po2box  N_Pts2dCalcBBox

#define G_boxdia  N_BBoxGetDiagonal
#define G_boxcen  N_BBoxGetCenter
#define G_boxdim  N_BBoxGetDimensions
#define G_bx2ovl  N_BBox2dCalcOverlap

#define G_makln1  N_CreateLinePtPt
#define G_makln2  N_CreateLineStartDirVector
#define G_makpln  N_CreatePlanePtNormal
#define G_makitv  N_CreateInterval
#define G_itvbre  N_IntervalGetData
#define G_makrct  N_CreateRectangle
#define G_rctbre  N_RectangleGetData

#define G_boxbre  N_GetBBoxData
#define G_boxdef  N_BBoxDefine

#define G_plnbre  N_PlaneGetData
#define G_plnnor  N_PlaneGetNormal

#define G_tragnr  N_CreateRotationMatrixAboutAxis
#define G_traort  N_CreateTransformMatrixFromAxes
#define G_tratrl  N_CreateTranslationMatrixFromPts
#define G_travec  N_CreateTransformMatrixFromVectors
#define G_traaxl  N_TransformPtWithShapeFuncAndScale
#define G_traxyz  N_CreateTransformMatrixFromVector

#define G_lipost  N_PtGetSideOfLine
#define G_plpost  N_PtGetSideOfPlane

#define G_rctitv  N_RectToTwoIntervals
#define G_lsqpln  N_FitPlanePts
#define G_polpln  N_PlaneFitOrdered3dPts
#define G_lsqdpl  N_PlaneFit3dPts
#define G_reflcp  N_CptReflect
#define G_gweabc  N_CPtCalcWeightColinear

#define G_imppln  N_PlaneImplicitToPtNormal
#define G_plnimp  N_PlanePtNormalToImplicit
#define G_impln2  N_LineImplicitToPtVector
#define G_ln2imp  N_LinePtVectorToImplicit

#define G_lsqln2  N_LineFit2dPts
#define G_lsqln3  N_LineFit3dPts
#define G_lsqdln  N_LineFitPts

#define G_traro2  N_Rotate2dPts
#define G_trasc2  N_Scale2dPts
#define G_trash2  N_Shear2dPts
#define G_tratr2  N_Translate2dPts
#define G_tra3da  N_TetraCalcMatrix

#define G_mxapln  N_MaxAreaPlane3dPts
#define G_poicln  N_PairSelected2dPts
#define G_poiord  N_Order3dPts
#define G_cirder  N_CalcCircArcDerivs
#define G_araspl  N_AreaSpherePolygon
#define G_araspt  N_AreaSpherePatch
#define G_circer  N_CalcCircCenterAndRadius
#define G_lsqcir  N_CreateCircFrom2dPts
#define G_lsqsph  N_SphereFit3dPts
#define G_poirct  N_BoundRect2dPts
#define G_sphcer  N_SphereCenterRadius

/* NL_iges.h and NL_iges.cpp */
#define N_igs126  N_Iges126Crv
#define N_igsccp  N_IgesClampCrv
#define N_igscsk  N_IgesCorrectCrvKnots
#define N_igsvkb  N_IgesValidate
#define N_igs128  N_Iges128Srf
#define N_igsscp  N_IgesClampSrf
#define N_igsssk  N_IgesCorrectSrfKnots
#define N_igs112  N_Iges112CrvNonRat
#define N_igs100  N_Iges100Arc
#define N_igs110  N_Iges100Line
#define N_igs124  N_Iges124Matrix
#define N_igs102  N_Iges102CompositeCrv
#define N_igs108  N_Iges108Plane
#define N_igs122  N_Iges122ExtrudedSrf
#define N_igs118  N_Iges118RuledSrf
#define N_igs114  N_Iges114NonRatSrf
#define N_igs120  N_Iges120RevolvedSrf
#define N_igs106  N_Iges106LinearCrv
#define N_igs104  N_Iges104ConicArc
#define N_igspnc  N_IgesNonPeriodicCPts
#define N_igspnk  N_IgesNonPeriodicKnots
#define N_igspcn  N_IgesNonPeriodicCrv
#define N_igspsn  N_IgesNonPeriodicSrf

/* NL_Math.h and NL_Math.cpp */
#define M_quades  N_SolveQuadraticEq
#define M_inswap  N_SwapIntegers
#define M_reswap  N_SwapReals
#define M_rshell  N_ShellSortReal
#define M_rinsch  N_SearchInsertReal
#define M_i1mima  N_MinMax1dIntArray
#define M_i2mima  N_MinMax2dIntArray
#define M_r1mima  N_MinMax1dRealArray
#define M_r2mima  N_MinMax2dRealArray
#define M_poswap  N_SwapPts
#define M_cpswap  N_SwapCPts
#define M_pascal  N_PascalTriIndex
#define M_pastri  N_PascalTriRow
#define M_iniima  N_InitIntMatrix
#define M_inirma  N_InitRealMatrix
#define M_inipma  N_InitPtMatrix
#define M_inicma  N_InitCPtMatrix
#define M_makima  N_CreateIntMatrix
#define M_makrma  N_CreateRealMatrix
#define M_makpma  N_CreatePtMatrix
#define M_makcma  N_CreateCPtMatrix
#define M_imadef  N_IntMatrixDefine
#define M_rmadef  N_RealMatrixDefine
#define M_pmadef  N_PtMatrixDefine
#define M_cmadef  N_CPtMatrixDefine
#define M_imabre  N_GetIntMatrixData
#define M_rmabre  N_GetRealMatrixData
#define M_pmabre  N_GetPtMatrixData
#define M_cmabre  N_GetCPtMatrixData
#define M_imaind  N_GetMaxIndexIntMatrix
#define M_rmaind  N_GetMaxIndexRealMatrix
#define M_pmaind  N_GetMaxIndexPtMatrix
#define M_cmaind  N_GetMaxIndexCPtMatrix
#define M_imaimp  N_GetIntMatrixPtr
#define M_rmarmp  N_GetRealMatrixPtr
#define M_pmapmp  N_GetPtMatrixPtr
#define M_cmacmp  N_GetCPtMatrixPtr
#define M_prtrma  N_PrintRealMatrix
#define M_inrhas  N_InitRealHash
#define M_uprhas  N_UpdateRealHash
#define M_rerhas  N_RetrieveRealHash
#define M_getima  N_SetIntMatrix
#define M_getrma  N_SetRealMatrix
#define M_getpma  N_SetPtMatrix
#define M_getcma  N_SetCPtMatrix
#define M_imachk  N_CheckMemIntMatrix
#define M_rmachk  N_CheckMemRealMatrix
#define M_pmachk  N_CheckMemPtMatrix
#define M_cmachk  N_CheckMemCPtMatrix
#define M_rmamul  N_RealMatrixMultiply
#define M_rmamtr  N_RealMatrixMultiplyTranspose
#define M_rmamtm  N_RealMatrixTransposeMultiply
#define M_rmatrp  N_RealMatrixTranspose
#define M_rmapoi  N_RealMatrixMultiplyPtArray
#define M_rmacpt  N_RealMatrixMultiplyCPtArray
#define M_rmcprm  N_RealMatrixMultiplyRealMatrixTranspose
#define M_cplevn  N_PowerBasisCrvEvalPts
#define M_splevn  N_PowerBasisSrfEvalPts
#define M_polder  N_PowerBasisEvalDerivs
#define M_polnew  N_PowerBasisRootNewton
#define M_ludcmp  N_RealMatrixLuDecompose
#define M_ludpiv  N_RealMatrixLuDecomposePivot
#define M_forbac  N_RealMatrixForBack
#define M_rafoba  N_RealMatrixRightForBack
#define M_rafbpv  N_RealMatrixForBackPivot
#define M_rmainv  N_RealMatrixInverse
#define M_rmaivp  N_RealMatrixInversePivot
#define M_lsslsy  N_RealMatrixLstSqSolve
#define M_svdsbf  N_SingleValueDecomposeSolve
#define M_svdcpf  N_RealMatrixSingleValueDecompose
#define M_pofbpv  N_RealMatrixRightForBackPivot
#define M_rshel2  N_SortRealArray
#define M_ishel2  N_SortIndexArrayMap
#define M_ishell  N_SortIndexArray
#define M_minfun  N_FuncFindMinima
#define M_espsur  N_EvenSpacePtsSrf
#define M_espcur  N_EvenSpacePtsCrv
#define M_svdinv  N_Real2dArrayInverseSVD
#define M_rmaivs  N_RealMatrixInverseSVD
#define M_inrand  N_GenerateRandomNumber
#define M_fliflo  N_RandomFlipsFlops
#define M_intfel  N_FindElemIntArray
#define M_intfsp  N_FindIntervalIntArray
#define M_reafsp  N_FindIntervalRealArray
#define M_tanbes  N_TangentVectorBessel
#define M_tanaki  N_TangentVectorAkima
#define M_rmaevv  N_RealMatrixEigenValuesVectors
#define M_reaclu  N_FindClustersRealArray
#define M_rishel  N_SortRealIndexArrays
#define M_rrshel  N_SortRealRealArrays

/* NL_Util.h and NL_Util.cpp */
#define N_inurbs  N_InitNurbs
#define N_enurbs  N_EndNurbs

#define S_getf1d  N_AllocFlag1dArray
#define S_getf2d  N_AllocFlag2dArray
#define S_getf1p  N_AllocFlagPtr1dArray
#define S_geti1d  N_AllocInt1dArray
#define S_geti2d  N_AllocInt2dArray
#define S_geti1p  N_AllocIntPtr1dArray
#define S_geti2p  N_AllocIntPtr2dArray
#define S_getr12  N_AllocRealPtr3dArray
#define S_getr4d  N_AllocReal4dArray

#define S_Point3dArrayAlloc   N_AllocPt3dArray
#define S_CPoint3dArrayAlloc  N_AllocCPt3dArray

#define S_getpoa  N_XYZToPtArray
#define S_getpom  N_XYZTo2dPtArray
#define S_getcpa  N_XYZToCPtArray
#define S_getcpm  N_XYZTo2dCPtArray

#define S_getima  N_AllocIntMatrix
#define S_getrma  N_AllocRealMatrix
#define S_getpma  N_AllocPtMatrix
#define S_getcma  N_AllocCPtMatrix
#define S_getp2v  N_AllocVariable2dPtArray

#define U_inpp1d  N_Read1dPtFromFile
#define U_outp1d  N_Write1dPtToFile
#define U_inpp2d  N_Read2dPtFromFile
#define U_outp2d  N_Write2dPtToFile
#define U_kilf2d  N_FreeFlag2dArray
#define U_kilf1d  N_FreeFlag1dArray
#define U_kili1d  N_FreeInt1dArray
#define U_kili2d  N_FreeInt2dArray
#define U_kili1p  N_FreeIntPtr1dArray
#define U_kili2p  N_FreeIntPtr2dArray
#define U_kilp1d  N_FreePt1dArray
#define U_kilp2d  N_FreePt2dArray
#define U_ralf1d  N_Realloc1dFlagArray
#define U_ralf2d  N_Realloc2dFlagArray
#define U_rali1d  N_Realloc1dIntArray
#define U_rali1p  N_Realloc1dIntPtrArray
#define U_rali2d  N_Realloc2dIntArray
#define U_rali2p  N_Realloc2dIntPtrArray
#define U_ralr1d  N_Realloc1dRealArray
#define U_ralr2d  N_Realloc2dRealArray
#define U_ralp1d  N_Realloc1dPtArray
#define U_ralp2d  N_Realloc2dPtArray
#define U_ralc1d  N_Realloc1dCPtArray
#define U_ralc2d  N_Realloc2dCPtArray
#define U_shwstk  N_PrintStack

#define U_CPoint3dArrayFree N_FreeCPt3dArray

#define U_lcsigs  N_WriteLineCrvSrfIges
#define U_p1digs  N_WritePtsIges
#define U_spligs  N_WriteSrfIges
#define U_isp1ci  N_IsPtSet1dCircular
#define U_isp1li  N_IsPtSet1dColinear
#define U_isp1pl  N_IsPtSet1dCoplanar
#define U_isp1sp  N_IsPtSet1dSpherical

#define E_seterr  N_ErrSet
#define E_clrerr  N_ErrClear
#define E_imasto  N_CheckIntMatStorage
#define E_rmasto  N_CheckRealMatStorage
#define E_pmasto  N_CheckPtMatStorage
#define E_cmasto  N_CheckCPtMatStorage
#define E_errtyp  N_ErrGetType

/* NL_Math.h and NL_Math.c */
#define A_vcocpt  N_VectorCombineCPts
#define A_vcopoi  N_VectorCombinePts
#define A_updcpt  N_VectorBlendCPt
#define A_updpoi  N_VectorBlendPt
#define A_tracpt  N_TransformCPt
#define A_trapoi  N_TransformPt
#define A_trlcpt  N_TranslateCPt

/* NL_Bezier.h and NL_Bezier.c */
#define B_allber  N_BezEvalBasis
#define B_arclen  N_BezCalcLength
#define B_bernst  N_BezEvalOneBasis
#define B_cbepow  N_BezToPowerBasis
#define B_cdegel  N_BezElevateDegree
#define B_cdegre  N_BezReduceDegree
#define B_cdemat  N_BezGetDegreeElevationMatrix
#define B_cextsd  N_BezCrvExtend
#define B_cfncu4  N_BezFuncMultiplyBezCrv4D
#define B_cfncur  N_BezFuncMultiplyBezCrv
#define B_cfnevn  N_BezFuncEvalPt
#define B_cfnprt  N_BezFuncMultiplyBezFunc
#define B_circpt  N_BezCircArcFrom3Pts
#define B_circra  N_BezCenterRadiusFrom3CPts
#define B_cpobez  N_PowerBasisToBez
#define B_cprmat  N_BezFuncMultiplyBezCrvMatrix
#define B_crepar  N_BezReparam
#define B_csplit  N_BezSplit
#define B_cubapt  N_BezCubicFromPtsAndTangents
#define B_curcro  N_BezCrossProduct
#define B_curevn  N_BezCrvEvalPt
#define B_curprt  N_BezCrvDotProduct
#define B_degrco  N_BezDegreeReduceCoefs
#define B_fdegel  N_BezFuncDegreeElevate
#define B_gcubin  N_BezInterp4Pts
#define B_gcurin  N_BezInterpNPts
#define B_getciw  N_BezSetConicWeight
#define B_ipomat  N_BezInversePowerMatrix
#define B_iremat  N_BezInverseReparamMatrix
#define B_makcir  N_BezCircArcFromPtsAndTangents
#define B_makcon  N_BezConicArcFromPtsAndTangents
#define B_powmat  N_BezGetPowerConversionMatrix
#define B_reclen  N_BezCalcArcLength
#define B_repmat  N_BezGetReparamMatrix
#define B_sbepow  N_BezSrfToPower
#define B_sdegel  N_BezSrfElevateDegree
#define B_sdegre  N_BezSrfReduceDegree
#define B_sextsd  N_BezSrfExtend4D
#define B_sfndel  N_BezSrfFuncElevateDegree
#define B_sfnevn  N_BezSrfFuncEvalPt
#define B_sfnprt  N_BezSrfFuncMultiply
#define B_sfnsur  N_BezSrfMultiplySrfFunc
#define B_splcon  N_BezConicSplit
#define B_spobez  N_BezSrfPowerToBez
#define B_surcro  N_BezSrfCrossProduct
#define B_surevn  N_BezSrfEvalPt
#define B_surprt  N_BezSrfDotProduct
#define B_vdegel  N_BezVolumeDegreeElevate

/* Tessellate.h and Tessellate.c */
#define N_tessur  N_TessTrimmedSrf
#define N_tesbae  N_TessGetTriangleEdges
#define N_tesbap  N_TessGetTriangleVertices
#define N_tesbat  N_TessGetTriangles
#define N_tesesa  N_TessSrfArea
#define N_tesblt  N_TessIsOnEdge
#define N_tesbpl  N_TessEdgesFromPt
#define N_tesbpp  N_TessPtsAdjPt
#define N_tesbpt  N_TessTrianglesAdjPt
#define N_tesbtt  N_TessTrianglesAdjTriangle

/* Static function do not need to be mapped */
#define L_parbnd  ST_TessIsOnBoundary
#define N_tesbil  ST_TessIsInsideLoop
#define N_tesbip  ST_TessIsInsidePolygon
#define N_tesbit  ST_TessIsInsideTrim
#define N_tesbox  ST_TessFindBBoxIndices
#define N_tesdel  ST_TessRegionOfRectangles
#define L_initdl  ST_TessInitArray
#define L_sidets  ST_TessSideTest
#define L_poispn  ST_TessPtInSpan
#define L_cosine  ST_TessCosine
#define L_bndedg  ST_TessIsEdgeOnBoundary
#define L_edgtch  ST_TessEdgeTouch
#define L_linpol  ST_TessLineXPolygon
#define N_teslpi  ST_IsectLineWith2dPolygon
#define L_sitest  ST_TessSideTest2d
#define L_overlp  ST_TessOverlap
#define N_teslsi  ST_TessLineXLine2d
#define N_tespae  ST_TessCheckTrim
#define N_tespol  ST_TessBBoxXTrim
#define L_apppoi  ST_TessAppendPt
#define L_buffer  ST_TessBuffer
#define L_findip  ST_TessFindUnused
#define L_apppov  ST_TessAppendPolygonVertex
#define L_poibox  ST_TessIsPtInBBox
#define L_corner  ST_TessIsPtBBoxCorner
#define L_findcp  ST_TessFindCrossingPt
#define N_tesptc  ST_TessPolygonizeTrimCrv
#define N_tessub  ST_TessSubdivideSrf

/************************************************/
/* Old Nlib2 long names to New Nlib2 long names */
/* Just in case any users started using Nlib2   */
/************************************************/

#define A_Combine4CPts                            N_Combine4CPts
#define A_Combine4Pts                             N_Combine4Pts
#define A_TranslateSum2CPts                       N_TranslateSum2CPts
#define A_TranslateSum2Pts                        N_TranslateSum2Pts
#define A_Combine2CPts                            N_Combine2CPts
#define A_Combine2Pts                             N_Combine2Pts
#define A_CPtToPt                                 N_CPtToPt
#define A_Cross2CPts                              N_Cross2CPts
#define A_Diff2CPts                               N_Diff2CPts
#define A_DiffCPtPt                               N_DiffCPtPt
#define A_Diff2Pts                                N_Diff2Pts
#define A_Dot2CPts                                N_Dot2CPts
#define A_Dot2CPtsIn4D                            N_Dot2CPtsIn4D
#define A_Dot2Pts                                 N_Dot2Pts
#define A_CPtToPtNow                              N_CPtToPtNoW
#define A_CPtToPtEuclid                           N_CPtToPtEuclid
#define A_CPtToWzWyWz                             N_CPtToWxWyWz
#define A_CPtToXYZ                                N_CPtToXYZ
#define A_PtToXYZ                                 N_PtToXYZ
#define A_CPtGetW                                 N_CPtGetW
#define A_CPtGetZ                                 N_CPtGetZ
#define A_CPtFromWxWyWz                           N_CPtFromWxWyWz
#define A_PtFromXYZ                               N_PtFromXYZ
#define A_CopyCPt                                 N_CopyCPt
#define A_CopyPt                                  N_CopyPt
#define A_CPtMagnitude                            N_CPtMagnitude
#define A_PtMagnitude                             N_PtMagnitude
#define A_CPtToPtAndW                             N_CPtToPtAndW
#define A_PtToCPt                                 N_PtToCPt
#define A_CPtRationalDeriv                        N_CPtRatDeriv
#define A_CPtResetW                               N_CPtResetW
#define A_ScaleCPtXYZ                             N_ScaleCPtXYZ
#define A_ScaleCPt                                N_ScaleCPt
#define A_ScalePt                                 N_ScalePt
#define A_ScaleCPtWithPtandVector                 N_ScaleCPtWithPtAndVector
#define A_CPtSetW                                 N_CPtSetW
#define A_CPTSetX                                 N_CPtSetX
#define A_CPtSetY                                 N_CPtSetY
#define A_CPtSetZ                                 N_CPtSetZ
#define A_Sum2CPts                                N_Sum2CPts
#define A_SumCPtandPt                             N_SumCPtandPt
#define A_Sum2Pts                                 N_Sum2Pts
#define E_KnotVectorIsParamOutOfBounds            N_KnotVectorIsParamOutOfBounds
#define E_KnotVectorIsEndParam                    N_KnotVectorIsEndParam
#define E_KnotVectorIsValid                       N_KnotVectorIsValid

#define E_CurveIsSized                            N_CrvIsSized
#define E_CurveIsFunctionSized                    N_CrvIsFuncSized
#define E_CurveCountsValid                        N_CrvCountsAreValid
#define E_CurveWeightsValid                       N_CrvWeightsAreValid
#define E_CurveIsValid                            N_CrvIsValid
#define E_CurveIsNotReversed                      N_CrvIsNotReversed
#define E_CurveHasEqualCPoints                    N_CrvHasEqualCPts
#define E_CurveReplaceEqualCPoints                N_CrvReplaceEqualCPts
#define E_SurfaceIsSized                          N_SrfIsSized
#define E_SurfaceIsFunctionSized                  N_SrfIsFuncSized
#define E_SurfaceCountsValid                      N_SrfCountsAreValid
#define E_SurfaceWeightsValid                     N_SrfWeightsAreValid
#define E_SurfaceIsValid                          N_SrfIsValid
#define E_SurfaceHasEqualCPoints                  N_SrfHasEqualCPts
#define G_PointsAreInPolygonGravityField          N_PtsAreInPolygonGravityField
#define G_PointsAreInPolygon                      N_PtsAreInPolygon
#define G_EPolygonIsClosed                        N_EPolygonIsClosed
#define G_ENetIsClosed                            N_ENetIsClosed
#define G_PointIsContainedByEPolygon              N_PtIsContainedByEPolygon
#define G_Do2dLineSegsIsect                       N_LineSegs2dAreIntersecting
#define G_CPointsAreColinear                      N_CPtsAreColinear
#define G_PointsAreEqual                          N_PtsAreEqual
#define G_PointsAreColinear                       N_PtsAreColinear
#define G_ENetGetBBox                             N_ENetGetBBox
#define G_ENetMakeWithPoints                      N_ENetFromPts
#define G_EPolygonMakeWithPoints                  N_EPolygonFromPts
#define G_ENetGetPoints                           N_ENetGetPts
#define G_EPolygonGetPoints                       N_EPolygonGetPts

#define M_FloatOpIsBad                            N_FloatOpIsBad
#define M_CMatrixIsNULL                           N_CPtMatrixIsNULL
#define M_IMatrixIsNULL                           N_IntMatrixIsNULL
#define M_RMatrixIsNULL                           N_RealMatrixIsNULL
#define M_PMatrixIsNULL                           N_PtMatrixIsNULL

/* These have not changed from the original NLib2 */
/*#define N_BasisFindSpan                         */
/*#define N_BasisFindSpanAndMult                  */  
/*#define N_BasisGetSpanCount                     */  
/*#define N_BasisFindGlobalMax                    */  
/*#define N_BasisFindAllSpanMaxima                */  
/*#define N_BasisGetLongestAndShortestSpans       */  
/*#define N_BasisGetKnotsAndMults                 */  
/*#define N_BasisReparam                          */

#define N_BasisArrayGetCompatKnots                N_GetCompatibleKnotArray
#define N_BasisPairReparamAndGetCompatKnots       N_GetCompatibleKnotArrayMult
#define N_BasisArrayReparamAndGetCompatKnotsToTol N_GetCompatibleKnotVector
#define N_BasisArrayAdjustAndGetCompatKnotsToTol  N_GetCompatibleKnotVectorToTol

/* These have not changed from the original NLib2 */
/*#define N_BasisInsertKnots                      */
/*#define N_BasisSplitLongestSpan                 */
/*#define N_BasisSplitNLongestSpans               */
/*#define N_BasisIncreaseKnotMult                 */
/*#define N_BasisFindIndexNode                    */
/*#define N_BasisFindIndexNodeArray               */
/*#define N_BasisFindNodeSpan                     */
/*#define N_BasisFindKnotToTurnParamIntoNode      */
/*#define N_BasisEval                             */
/*#define N_BasisDerivs                           */
/*#define N_BasisEvalArray                        */
/*#define N_BasisDerivsArray                      */
/*#define N_BasisIEval                            */
/*#define N_BasisIDerivs                          */
/*#define N_BasisIKnotDeriv                       */
/*#define N_BasisKnotDerivs                       */
/*#define N_BiBasisKnotDeriv                      */

#define N_CurveBasisDerivs                        N_CrvBasisDerivs
#define N_CurveBasisIEval                         N_CrvBasisIEval
#define N_CurveRationalBasisDerivs                N_CrvRatBasisDerivs
#define N_CurveRationalBasisIEval                 N_CrvRatBasisIEval
#define N_CurveRationalBasisIDerivs               N_CrvRatBasisIDerivs
#define N_CurveRationalBasisKnotDeriv             N_CrvRatBasisKnotDeriv
#define N_CurveRationalBasisIKnotDeriv            N_CrvRatBasisIKnotDeriv
#define N_CurveGetBBox                            N_CrvGetBBox
#define N_SurfaceBasisDerivs                      N_SrfBasisDerivs
#define N_SurfaceBasisIEval                       N_SrfBasisIEval
#define N_SurfaceNonRationalBasisDerivs           N_SrfNonRatBasisDerivs
#define N_SurfaceRationalBasisDerivs              N_SrfRatBasisDerivs
#define N_SurfaceRationalBasisIEval               N_SrfRatBasisIEval
#define N_SurfaceRationalBasisIDerivs             N_SrfRatBasisIDerivs
#define N_SurfaceRationalBasisKnotDeriv           N_SrfRatBasisKnotDeriv
#define N_SurfaceRationalBasisIKnotDeriv          N_SrfRatBasisIKnotDeriv
#define N_SurfaceGetBBox                          N_SrfGetBBox
#define N_CurveEval                               N_CrvEval
#define N_CurveDerivs                             N_CrvDerivs
#define N_CurveTransform                          N_CrvTransform
#define N_CurveScale                              N_CrvScale
#define N_CurveTranslate                          N_CrvTranslate
#define N_CurveRotateAtPoint                      N_CrvRotateAboutAxis
#define N_CurveReparam                            N_CrvReparam
#define N_CurveInsertKnot                         N_CrvInsertKnot
#define N_CurveElevateDegree                      N_CrvElevateDegree
#define N_SurfaceEval                             N_SrfEvalPt
#define N_SurfaceDerivs                           N_SrfDerivs
#define N_SurfaceEvalGrid                         N_SrfEvalPtGrid
#define N_SFunEvalGrid                            N_SFuncEvalGrid
#define N_SurfaceTransform                        N_SrfTransform
#define N_SurfaceScale                            N_SrfScale
#define N_SurfaceTranslate                        N_SrfTranslate
#define N_SurfaceRotateAtPoint                    N_SrfRotateAtPt
#define N_SurfaceReparam                          N_SrfReparam
#define N_SurfaceInsertKnot                       N_SrfInsertKnot
#define N_SurfaceMakeIsoCurve                     N_SrfExtractIsoCrv
#define N_SurfaceElevateDegree                    N_SrfElevateDegree
#define N_SurfaceMakeBoundaryCurves               N_SrfExtractBoundaryCrvs
#define N_SFunEval                                N_SFuncEval
#define N_SFunDerivs                              N_SFuncDerivs
#define N_CFunEval                                N_CFuncEval
#define N_CFunDerivs                              N_CFuncDerivs
#define S_CNetAlloc                               N_AllocCNet
#define S_CNetAndArraysAlloc                      N_AllocCNetAndArrays
#define S_KnotVectorAlloc                         N_AllocKnotVector
#define S_KnotVectorAndArrayAlloc                 N_AllocKnotVectorAndArray
#define S_CPoint2dArrayAlloc                      N_AllocCPt2dArray
#define S_CPoint1dArrayAlloc                      N_AllocCPt1dArray
#define S_CPointPtr2dArrayAlloc                   N_AllocCPtPtr2dArray
#define S_CPointPtr1dArrayAlloc                   N_AllocCPtPtr1dArray
#define S_Point2dArrayAlloc                       N_AllocPt2dArray
#define S_Point1dArrayAlloc                       N_AllocPt1dArray
#define S_PointPtr2dArrayAlloc                    N_AllocPtPtr2dArray
#define S_PointPtr1dArrayAlloc                    N_AllocPtPtr1dArray
#define S_Real1dArrayAlloc                        N_AllocReal1dArray
#define S_Real2dArrayAlloc                        N_AllocReal2dArray
#define S_Real3dArrayAlloc                        N_AllocReal3dArray
#define S_RealPtr1dArrayAlloc                     N_AllocRealPtr1dArray
#define S_RealPtr2dArrayAlloc                     N_AllocRealPtr2dArray
#define S_SurfaceAlloc                            N_AllocSrf
#define S_SurfaceAndArraysAlloc                   N_AllocSrfAndArrays
#define S_CurveAlloc                              N_AllocCrv
#define S_CurveAndArraysAlloc                     N_AllocCrvAndArrays
#define S_CPolygonAlloc                           N_AllocCPolygon
#define S_CPolygonAndArrayAlloc                   N_AllocCPolygonAndArray
#define S_CValueAndArrayAlloc                     N_AllocCValueAndArray
#define S_CValueAlloc                             N_AllocCValue
#define S_SValueAndArrayAlloc                     N_AllocSValueAndArray
#define S_SValueAlloc                             N_AllocSValue
#define U_CurveMakeWithCPolygonAndKnotvector      N_CrvFromCPolygonAndKnotVector
#define U_CurveMakeWithCPointsAndKnots            N_CrvFromCPtsAndKnots
#define U_CurveMakeWithCPointCoordsAndKnots       N_CrvFromCPtCoordsAndKnots
#define U_KnotvectorMakeWithRealArray             N_KnotVectorFromRealArray
#define U_SurfaceMakeWithCNetAndKnotvectors       N_SrfFromCNetAndKnotVectors
#define U_SurfaceMakeWithCPointsAndKnots          N_SrfFromCPtsAndKnots
#define U_SurfaceMakeWithCPointCoordsAndKnots     N_SrfFromCPtCoordsAndKnots
#define U_CNetMakeWithCPoints                     N_CNetFromCPts
#define U_CNetMakeWithCPointCoords                N_CNetFromCPtCoords
#define U_CPolygonMakeWithCPoints                 N_CPolygonFromCPts
#define U_CPolygonMakeWithCPointCoords            N_CPolygonFromCPtCoords
#define U_SValueMakeWithArray                     N_SValueFromArray
#define U_CValueMakeWithArray                     N_CValueFromArray
#define U_SFunMakeWithKnotvectors                 N_SFuncFromKnotVectors
#define U_SFunMakeWithKnots                       N_SFuncFromKnots
#define U_CFunMakeWithKnotvector                  N_CFuncFromKnotVector
#define U_CFunMakeWithKnot                        N_CFuncFromKnots
#define U_SurfaceFree                             N_FreeSrf
#define U_CurveFree                               N_FreeCrv
#define U_SurfaceStructFree                       N_FreeSrfStruct
#define U_CurveStructFree                         N_FreeCrvStruct
#define U_CNetFree                                N_FreeCNet
#define U_CPoint2dArrayFree                       N_FreeCPt2dArray
#define U_CPoint1dArrayFree                       N_FreeCPt1dArray
#define U_KnotVectorFree                          N_FreeKnotVector
#define U_Real1dArrayFree                         N_FreeReal1dArray
#define U_Real2dArrayFree                         N_FreeReal2dArray
#define U_Real3dArrayFree                         N_FreeReal3dArray
#define U_SValueFree                              N_FreeSValue
#define U_CValueFree                              N_FreeCValue
#define U_SurfaceAreArraysNULL                    N_SrfAreArraysNULL
#define U_CurveAreArraysNULL                      N_CrvAreArraysNULL
#define U_SurfaceIsRational                       N_IsSrfRat
#define U_CurveIsRational                         N_IsCrvRat
#define U_CurveAreFunctionArraysNULL              N_CrvAreFuncArraysNULL
#define U_SurfaceAreFunctionArraysNULL            N_SrfAreFuncArraysNULL
#define U_SurfaceIsDegenerate                     N_SrfIsDegen
#define U_CurveIs3d                               N_CrvIs3d
#define U_CurveIsClosed                           N_CrvIsClosed
#define U_CurveIsLine                             N_CrvIsLine
#define U_SurfaceIsClosed                         N_SrfIsClosed
#define U_1dPointSetIsClosed                      N_1dPtSetIsClosed
#define U_2dPointSetIsClosed                      N_2dPtSetIsClosed
#define U_CurvesAreCoincident                     N_CrvsAreCoincident
#define U_SurfacesAreCoincident                   N_SrfsAreCoincident
#define U_CurvesAreCombatible                     N_CrvsAreCombatible
#define U_SurfaceIsSingular                       N_SrfIsSingular
#define U_CurveIsDegenerate                       N_CrvIsDegen
#define U_CPointsAreEqual                         N_CPtsAreEqual
#define U_CurveAreWeightsEqual                    N_CrvAreWeightsEqual
#define U_SurfaceAreWeightsEqual                  N_SrfAreWeightsEqual
#define U_Curve4dIsDegenerate                     N_Crv4dIsDegen
#define U_CurveIsInZ0Plane                        N_CrvIsInZ0Plane
#define U_CurveIsPlanar                           N_CrvIsPlanar
#define U_SurfaceIsFlatCheap                      N_SrfIsFlatCheap
#define U_SurfaceIsFlat                           N_SrfIsFlat
#define U_KnotvectorGetKnots                      N_KnotVectorGetKnots
#define U_CurveCopy                               N_CrvCopy
#define U_CurveInitArrays                         N_CrvInitArrays
#define U_CurveSizeArrays                         N_CrvSizeArrays
#define U_CurveGetCPointsDegreeAndKnots           N_CrvGetCPtsDegreeAndKnots
#define U_CurveGetDegree                          N_CrvGetDegree
#define U_CurveGetEPolygon                        N_CrvGetEPolygon
#define U_CurveGetKnotvector                      N_CrvGetKnotVector
#define U_CurveGetParameterBounds                 N_CrvGetParamBounds
#define U_CurveGetKnots                           N_CrvGetKnots
#define U_CurveGetCPoints                         N_CrvGetCPts
#define U_CurveGetCPointsAndKnots                 N_CrvGetCPtsAndKnots
#define U_CurveGetCPointsKnotVectorAndKnots       N_CrvGetCPtsKnotVectorAndKnots
#define U_CurveSetCPointsAndKnots                 N_CrvSetCPtsAndKnots
#define U_CurveAllocateArrays                     N_AllocCrvArrays
#define U_CurveGetArraySizes                      N_CrvGetArraySizes
#define U_CurveSetSizeIndices                     N_CrvSetSizeIndices
#define U_CurveReparam                            N_CrvReparam
#define U_CurveCompress                           N_CrvCompress
#define U_CurveWriteToFile                        N_CrvWriteToFile
#define U_CurveReadFromFile                       N_CrvReadFromFile
#define U_CurvePruneRational                      N_CrvPruneRat
#define U_CurveMakeNonRational                    N_CrvMakeNonRat
#define U_SurfaceGetNetAndKnotvectors             N_SrfGetNetAndKnotVectors
#define U_SurfaceGetCPointsAndKnots               N_SrfGetCPtsAndKnots
#define U_SurfaceGetCPointsDegreesAndKnots        N_SrfGetCPtsDegreesAndKnots
#define U_SurfaceGetDegrees                       N_SrfGetDegrees
#define U_SurfaceGetENet                          N_SrfGetENet
#define U_SurfaceGetKnotvectors                   N_SrfGetKnotVectors
#define U_SurfaceGetParameterBounds               N_SrfGetParameterBounds
#define U_SurfaceGetKnots                         N_SrfGetKnots
#define U_SurfaceGetCPoints                       N_SrfGetCPts
#define U_SurfaceGetCPointsKnotVectorAndKnots     N_SrfGetCPtsKnotVectorAndKnots
#define U_SurfaceSetCPointsAndKnots               N_SrfSetCPtsAndKnots
#define U_SurfaceCopy                             N_SrfCopy
#define U_SurfaceInitArrays                       N_SrfInitArrays
#define U_SurfaceSizeArrays                       N_SrfSizeArrays
#define U_SurfaceAllocateArrays                   N_AllocSrfArrays
#define U_SurfaceGetArraySizes                    N_SrfGetArraySizes
#define U_SurfaceSetSizeIndices                   N_SrfSetSizeIndices
#define U_SurfaceGetDenominatorFunction           N_SrfGetDenominatorFunc
#define U_SurfaceReparam                          U_SrfReparam
#define U_SurfaceCompress                         N_SrfCompress
#define U_SurfaceWriteToFile                      N_SrfWriteToFile
#define U_SurfaceReadFromFile                     N_SrfReadFromFile
#define U_SurfacePruneRational                    N_SrfPruneRat
#define U_SurfaceMakeNonRational                  N_SrfMakeNonRat
#define U_SFunGetCPoints                          N_SFuncGetCPts
#define U_SFunInitArrays                          N_SFuncInitArrays
#define U_SFunSizeArrays                          N_SFuncSizeArrays
#define U_SFunGetKnots                            N_SFuncGetKnots
#define U_SFunAllocateArrays                      N_AllocSFuncArrays
#define U_SFunGetArraySizes                       N_SFuncGetArraySizes
#define U_SFunSetSizeIndices                      N_SFuncSetSizeIndices
#define U_SFunGetDegrees                          N_SFuncGetDegrees
#define U_SFunGetKnotvectors                      N_SFuncGetKnotVectors
#define U_SFunGetArrayAndKnotvectors              N_SFuncGetArrayAndKnotVectors
#define U_CFunInitArrays                          N_CFuncInitArrays
#define U_CFunSizeArrays                          N_CFuncSizeArrays
#define U_CFunGetKnots                            N_CFuncGetKnots
#define U_CFunAllocateArrays                      N_AllocCFuncArrays
#define U_CFunGetArraySizes                       N_CFuncGetArraySizes
#define U_CFunSetSizeIndices                      N_CFuncSetSizeIndices
#define U_CFunGetDegree                           N_CFuncGetDegree
#define U_CFunGetKnotvector                       N_CFuncGetKnotVector
#define U_CFunGetArrayAndKnotvector               N_CFuncGetArrayAndKnotVector
#define U_CurveProjectionInitArrays               N_CrvProjectionInitArrays
#define U_CPolygonGetCPoints                      N_CPolygonGetCPts
#define U_CNetGetCPoints                          N_CNetGetCPts

#define S_CMeshAlloc                              N_AllocCMesh
#define S_CMeshAndArraysAlloc                     N_AllocCMeshAndArrays
#define U_CMeshMakeWithCPoints                    N_CMeshFromCPts
#define U_CMeshMakeWithCPointCoords               N_CMeshFromCPtCoords
#define U_CMeshGetCPoints                         N_CMeshGetCPts
#define U_CMeshFree                               N_FreeCMesh
#define G_MakeEMeshWithPoints                     N_EMeshFromPts
#define G_EMeshGetPoints                          N_EMeshGetPts
#define G_EMeshGetBBox                            N_EMeshGetBBox

#define E_VolumeIsFuncSized                       N_VolumeIsFuncSized
#define S_VValueAlloc                             N_AllocVValue
#define S_VValueAndArrayAlloc                     N_AllocVValueAndArray
#define U_VValueFree                              N_FreeVValue
#define U_VValueMakeWithArray                     N_VValueFromArray
#define U_VFunMakeWithKnotvectors                 N_VFuncFromKnotVectors
#define U_VFunMakeWithKnots                       N_VFuncFromKnots
#define U_VFunSizeArrays                          N_VFuncSizeArrays
#define U_VFunGetArraySizes                       N_VFuncGetArraySizes
#define U_VFunSetSizeIndices                      N_VFuncSetSizeIndices
#define U_VFunGetComponents                       N_VFuncGetComponents
#define U_VFunGetKnots                            N_VFuncGetKnots
#define U_VFunGetDegrees                          N_VFuncGetDegrees
#define U_VFunInitArrays                          N_VFuncInitArrays
#define U_VFunAreArraysNULL                       N_VFuncAreArraysNULL
#define U_VFunGetArrayAndKnotvectors              N_VFuncGetArrayAndKnotVectors
#define U_VFunAllocateArrays                      N_AllocVFuncArrays
#define N_VFunEval                                N_VFuncEval
#define N_VFunDerivs                              N_VFuncDerivs
#define U_VFunGetKnotvectors                      N_VFuncGetKnotVectors

#define U_FileOpen                                N_FileOpen
#define U_FileWrite                               N_FileWrite
#define U_FileClose                               N_FileClose
#define U_FileOffset                              N_FileOffset
#define U_FileReadIndex                           N_FileReadIndex
#define U_FileWriteIndex                          N_FileWriteIndex

#define E_VolumeCountsValid                  N_VolumeAreCountsValid
#define E_VolumeWeightsValid                 N_VolumeAreWeightsValid
#define E_VolumeIsValid                      N_VolumeIsValid
#define E_VolumeHasEqualCPoints              N_VolumeHasEqualCPts
#define E_VolumeIsSized                      N_VolumeIsSized
#define S_VolumeAlloc                        N_AllocVolume
#define S_VolumeAndArraysAlloc               N_AllocVolumeAndArrays
#define U_AreVolumeArraysNULL                N_AreVolumeArraysNULL
#define U_VolumeInitArrays                   N_VolumeInitArrays
#define U_VolumeAllocateArrays               N_AllocVolumeArrays
#define U_VolumeSetSizeIndices               N_VolumeSetSizeIndices
#define U_VolumeSizeArrays                   N_VolumeSizeArrays
#define U_VolumeCopy                         N_VolumeCopy
#define U_VolumeFree                         N_FreeVolume
#define U_VolumeMakeWithCMeshAndKnotvectors  N_VolumeFromCMeshAndKnotVectors
#define U_VolumeMakeWithCPointsAndKnots      N_VolumeFromCPtsAndKnots
#define U_VolumeReadFromFile                 N_VolumeReadFromFile
#define U_VolumeWriteToFile                  N_VolumeWriteToFile
#define U_VolumePruneRational                N_VolumePruneRat
#define U_VolumeMakeNonRational              N_VolumeMakeNonRat
#define U_VolumeGetDenominatorFunction       N_VolumeGetDenominatorFunc

#define U_VolumeGetCPointsAndKnots           N_VolumeGetCPtsAndKnots
#define U_VolumeGetMeshAndKnotvectors        N_VolumeGetMeshAndKnotVectors
#define U_VolumeGetCPointsDegreesAndKnots    N_VolumeGetCPtsDegreesAndKnots
#define U_VolumeGetArraySizes                N_VolumeGetArraySizes
#define U_VolumeGetDegrees                   N_VolumeGetDegrees
#define U_VolumeGetKnotvectors               N_VolumeGetKnotVectors
#define U_VolumeReparam                      N_VolumeReparam

#define U_VolumeGetParameterBounds           N_VolumeGetParameterBounds
#define U_VolumeGetKnots                     N_VolumeGetKnots
#define U_VolumeGetCPoints                   N_VolumeGetCPts
#define U_VolumeGetCPointsKnotVectorAndKnots N_VolumeGetCPtsKnotVectorAndKnots
#define U_VolumeGetEMesh                     N_VolumeGetEMesh
#define U_VolumeSetCPointsAndKnots           N_VolumeSetCPtsAndKnots
#define U_VolumeCompress                     N_VolumeCompress
#define U_VolumeIsRational                   N_VolumeIsRat
#define U_VolumeIsDegenerate                 N_VolumeIsDegen
#define U_VolumeAreWeightsEqual              N_VolumeAreWeightsEqual
#define N_VolumeRationalBasisDerivs          N_VolumeRatBasisDerivs
#define N_VolumeRationalBasisIDerivs         N_VolumeRatBasisIDerivs
#define N_VolumeRationalBasisIEval           N_VolumeRatBasisIEval
#define N_VolumeNonRationalBasisDerivs       N_VolumeNonRatBasisDerivs

#define U_GetCrvFuncData                     N_CFuncGetData
#define U_SFunGetComponents                  N_SFuncGetComponents

#define S_Malloc                             N_Malloc
#define S_Calloc                             N_Calloc
#define S_Realloc                            N_Realloc
#define S_Free                               N_Free

#define A_weight                             N_Weight

#define N_curxcpCMAX                         N_CrvExtendToPtLargeExtensions
#define N_curveThroughPoint                  N_CrvFitToPt
#define N_approxCurveFixedPoints             N_ApproxCrvToPts
#define N_multiCurveKnots                    N_CalcKnotVectorFromPtArrays
#define N_CurveSweepIntoSpiralSurface        N_CreateSpiralSrfTaper
#define N_CurveGetConicData                  N_CrvGetConicData

#define N_curveJetInit                       N_crvJetInit
#define N_curveJetUnset                      N_crvJetUnset
#define N_curveJetReset                      N_crvJetReset
#define N_curveJetSetParam                   N_crvJetSetParam
#define N_curveJetPos                        N_crvJetPos
#define N_curveJetDer1                       N_crvJetDer1
#define N_curveJetDer2                       N_crvJetDer2
#define N_curveJetPosCopy                    N_crvJetPosCopy
#define N_curveJetDer1Copy                   N_crvJetDer1Copy
#define N_curveJetDer2Copy                   N_crvJetDer2Copy
#define N_curveJetCurvature                  N_crvJetCurvature
#define N_curveJetRelax                      N_crvJetRelax

#endif /* _NLIB2DEFINES_H */
