// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*****************************************************************************/
/* NL_Geom.h: NLib Geometry Function Declarations                            */
/*****************************************************************************/

#ifndef _NL_GEOM_H
#define _NL_GEOM_H

/*********************/
/* Geometry routines */
/*********************/

GW_EXPORT NL_VOID N_VectorDot( NL_VECTOR, NL_VECTOR, NL_REAL * );
GW_EXPORT NL_VOID N_VectorDotRef( NL_VECTOR *, NL_VECTOR *, NL_REAL * );
GW_EXPORT NL_VOID N_VectorCross( NL_VECTOR, NL_VECTOR, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorCrossRef( NL_VECTOR *, NL_VECTOR *, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorScale( NL_VECTOR, NL_REAL, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorReverse( NL_VECTOR, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorReverseInPlace( NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorScaleRef( NL_VECTOR *, NL_REAL, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorSum( NL_VECTOR, NL_VECTOR, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorCombine( NL_REAL, NL_VECTOR, NL_REAL, NL_VECTOR, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorDiff( NL_VECTOR, NL_VECTOR, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorDiffCPts( NL_CPOINT, NL_CPOINT, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorDir( NL_POINT, NL_POINT, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorCreate( NL_REAL, NL_REAL, NL_REAL, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorCopy( NL_VECTOR, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorMixMultiply( NL_VECTOR, NL_VECTOR, NL_VECTOR, NL_REAL * );
GW_EXPORT NL_VOID N_VectorMagnitude( NL_VECTOR, NL_REAL * );
GW_EXPORT NL_VOID N_VectorMagnitudeRef( NL_VECTOR *, NL_REAL * );
GW_EXPORT NL_FLAG N_VectorNormalize( NL_VECTOR, NL_VECTOR *, NL_REAL * );
GW_EXPORT NL_FLAG N_VectorNormalizeRef( NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorPerpendicular( NL_VECTOR, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorPtAlongVector( NL_POINT, NL_REAL, NL_VECTOR, NL_POINT * );
GW_EXPORT NL_FLAG N_IsectLineLine( NL_LINESEG, NL_LINESEG, NL_POINT *, NL_REAL *, NL_REAL *, NL_FLAG * );
GW_EXPORT NL_FLAG N_IsectLineSegs( NL_POINT, NL_POINT, NL_POINT, NL_POINT, NL_POINT *, NL_FLAG * );
GW_EXPORT NL_FLAG N_IsectLinePlane( NL_LINESEG, NL_PLANE, NL_POINT *, NL_REAL *, NL_FLAG * );
GW_EXPORT NL_FLAG N_ProjectPtLine( NL_LINESEG, NL_POINT, NL_POINT *, NL_REAL *, NL_FLAG * );
GW_EXPORT NL_FLAG N_ProjectPtPlane( NL_PLANE, NL_POINT, NL_POINT * );
GW_EXPORT NL_VOID N_DistPtPt( NL_POINT, NL_POINT, NL_REAL * );
GW_EXPORT NL_FLAG N_DistPtLineSeg( NL_POINT, NL_POINT, NL_POINT, NL_REAL * );
GW_EXPORT NL_FLAG N_DistPerpPtLineSeg( NL_POINT, NL_POINT, NL_POINT, NL_REAL * );
GW_EXPORT NL_VOID N_DistPolygon( NL_POINT *, NL_INDEX, NL_REAL * );
GW_EXPORT NL_VOID N_DistCPolygon( NL_CPOINT *, NL_INDEX, NL_REAL * );
GW_EXPORT NL_VOID N_DistCptCpt( NL_CPOINT, NL_CPOINT, NL_REAL * );
GW_EXPORT NL_VOID N_DistCptCptHomo( NL_CPOINT, NL_CPOINT, NL_REAL * );
GW_EXPORT NL_FLAG N_DistPtInfLine( NL_LINESEG, NL_POINT, NL_REAL * );
GW_EXPORT NL_FLAG N_DistPtPlane( NL_PLANE, NL_POINT, NL_REAL * );
GW_EXPORT NL_VOID N_LineCalcBBox( NL_POINT, NL_POINT, NL_REAL, NL_MINMAXBOX * );
GW_EXPORT NL_VOID N_LineSetBoundingFlag( NL_LINESEG *, NL_FLAG );
GW_EXPORT NL_VOID N_LineGetDir( NL_LINESEG *, NL_VECTOR * );
GW_EXPORT NL_VOID N_Pts1dGetMaxExtent( NL_POINT *, NL_INDEX, NL_REAL * );
GW_EXPORT NL_VOID N_Pts2dGetMaxExtent( NL_POINT **, NL_INDEX, NL_INDEX, NL_REAL * );
GW_EXPORT NL_VOID N_BBoxGetDiagonal( NL_MINMAXBOX *, NL_REAL * );
GW_EXPORT NL_VOID N_BBoxGetCenter( NL_MINMAXBOX *, NL_POINT * );
GW_EXPORT NL_VOID N_BBox2dCalcOverlap( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL * );
GW_EXPORT NL_VOID N_CreateLinePtPt( NL_LINESEG *, NL_POINT, NL_POINT, NL_FLAG );
GW_EXPORT NL_VOID N_CreateLineStartDirVector( NL_LINESEG *, NL_POINT, NL_VECTOR, NL_FLAG );
GW_EXPORT NL_VOID N_CreatePlanePtNormal( NL_PLANE *, NL_POINT, NL_VECTOR );
GW_EXPORT NL_VOID N_CreateInterval( NL_INTERVAL *, NL_REAL, NL_REAL );
GW_EXPORT NL_VOID N_CreateRectangle( NL_RECTANGLE *, NL_REAL, NL_REAL, NL_REAL, NL_REAL );
GW_EXPORT NL_VOID N_RectangleGetData( NL_RECTANGLE *, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_IntervalGetData( NL_INTERVAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_GetBBoxData( NL_MINMAXBOX *, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_BBoxDefine( NL_MINMAXBOX *, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL );
GW_EXPORT NL_VOID N_LineGetData( NL_LINESEG *, NL_POINT *, NL_VECTOR *, NL_FLAG * );
GW_EXPORT NL_VOID N_PlaneGetData( NL_PLANE *, NL_POINT *, NL_VECTOR * );
GW_EXPORT NL_VOID N_PlaneGetNormal( NL_PLANE *, NL_VECTOR * );
GW_EXPORT NL_FLAG N_CreateRotationMatrixAboutAxis( NL_POINT, NL_VECTOR, NL_REAL, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateTransformMatrixFromAxes( NL_POINT, NL_VECTOR, NL_VECTOR, NL_VECTOR, NL_POINT, NL_VECTOR, NL_VECTOR, NL_VECTOR, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateTranslationMatrixFromPts( NL_POINT, NL_POINT, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_CreateTransformMatrixFromVectors( NL_POINT, NL_VECTOR, NL_POINT, NL_VECTOR, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_TransformPtWithShapeFuncAndScale( NL_POINT *, NL_CFUN *, NL_REAL, NL_FLAG, NL_FLAG, NL_FLAG );
GW_EXPORT NL_BOOLEAN N_VectorsAreParallel( NL_VECTOR, NL_VECTOR );
GW_EXPORT NL_BOOLEAN N_LineSegs2dAreIntersecting( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL );
GW_EXPORT NL_FLAG N_PtGetSideOfLine( NL_LINESEG *, NL_POINT );
GW_EXPORT NL_FLAG N_PtGetSideOfPlane( NL_PLANE *, NL_POINT );
GW_EXPORT NL_VOID N_RectToTwoIntervals( NL_RECTANGLE *, NL_INTERVAL *, NL_INTERVAL * );
GW_EXPORT NL_FLAG N_FitPlanePts( NL_POINT *, NL_INDEX, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_DistSignedPtPlane( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_POINT, NL_REAL * );
GW_EXPORT NL_FLAG N_VectorsCosAngle( NL_VECTOR, NL_VECTOR, NL_REAL * );
GW_EXPORT NL_FLAG N_VectorsAngle( NL_VECTOR, NL_VECTOR, NL_REAL * );
GW_EXPORT NL_VOID N_DistSqPtPt( NL_POINT, NL_POINT, NL_REAL * );
GW_EXPORT NL_FLAG N_CptReflect( NL_CPOINT, NL_PLANE, NL_CPOINT * );
GW_EXPORT NL_BOOLEAN N_CPtsAreColinear( NL_CPOINT, NL_CPOINT, NL_CPOINT, NL_FLAG );
GW_EXPORT NL_FLAG N_CPtCalcWeightColinear( NL_CPOINT, NL_CPOINT, NL_CPOINT, NL_REAL * );
GW_EXPORT NL_BOOLEAN N_PtsAreEqual( NL_POINT, NL_POINT );
GW_EXPORT NL_FLAG N_PlaneImplicitToPtNormal( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_POINT *, NL_VECTOR * );
GW_EXPORT NL_FLAG N_PlanePtNormalToImplicit( NL_POINT, NL_VECTOR, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_DistCPolygonHomo( NL_CPOINT *, NL_INDEX, NL_REAL * );
GW_EXPORT NL_FLAG N_DistPtArc( NL_POINT, NL_POINT, NL_REAL, NL_REAL, NL_REAL, NL_POINT, NL_POINT, NL_REAL * );
GW_EXPORT NL_FLAG N_VectorDirectedAngle( NL_VECTOR, NL_VECTOR, NL_REAL * );
GW_EXPORT NL_VOID N_DistSignedPtLine( NL_REAL, NL_REAL, NL_REAL, NL_POINT, NL_REAL * );
GW_EXPORT NL_FLAG N_IsectPlanePlane( NL_PLANE, NL_PLANE, NL_POINT *, NL_VECTOR *, NL_FLAG * );
GW_EXPORT NL_FLAG N_LineImplicitToPtVector( NL_REAL, NL_REAL, NL_REAL, NL_POINT *, NL_VECTOR * );
GW_EXPORT NL_FLAG N_LinePtVectorToImplicit( NL_POINT, NL_VECTOR, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_LineFit2dPts( NL_POINT *, NL_INDEX, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_LineFit3dPts( NL_POINT *, NL_INDEX, NL_POINT *, NL_VECTOR * );
GW_EXPORT NL_VOID N_DistPtPt2d( NL_POINT, NL_POINT, NL_REAL * );
GW_EXPORT NL_VOID N_DistSqPtPt2d( NL_POINT, NL_POINT, NL_REAL * );
GW_EXPORT NL_VOID N_Rotate2dPts( NL_POINT *, NL_INDEX, NL_POINT, NL_REAL, NL_POINT * );
GW_EXPORT NL_VOID N_Scale2dPts( NL_POINT *, NL_INDEX, NL_POINT, NL_VECTOR, NL_POINT * );
GW_EXPORT NL_VOID N_Shear2dPts( NL_POINT *, NL_INDEX, NL_VECTOR, NL_POINT * );
GW_EXPORT NL_VOID N_Translate2dPts( NL_POINT *, NL_INDEX, NL_VECTOR, NL_POINT * );
GW_EXPORT NL_FLAG N_TetraCalcMatrix( NL_POINT, NL_POINT, NL_POINT, NL_POINT, NL_POINT, NL_POINT, NL_POINT, NL_POINT, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_VOID N_VectorReverseVectorInPlace( NL_VECTOR, NL_VECTOR * );
GW_EXPORT NL_VOID N_VectorReverseVector( NL_VECTOR, NL_VECTOR, NL_VECTOR * );
GW_EXPORT NL_FLAG N_MaxAreaPlane3dPts( NL_POINT **, NL_INDEX, NL_INDEX, NL_REAL, NL_VECTOR * );
GW_EXPORT NL_FLAG N_PairSelected2dPts( NL_POINT *, NL_INDEX, NL_INDEX *, NL_INDEX, NL_INDEX, NL_REAL, NL_REAL, NL_INDEX ***, NL_REAL ***, NL_STACKS * );
GW_EXPORT NL_FLAG N_Order3dPts( NL_POINT *, NL_INDEX, NL_REAL, NL_POINT **, NL_INDEX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_ProjectPtQuad( NL_POINT, NL_POINT, NL_POINT, NL_POINT, NL_POINT, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_POINT *, NL_REAL *, NL_REAL *, NL_REAL *, NL_FLAG * );
GW_EXPORT NL_VOID N_BBoxGetDimensions( NL_MINMAXBOX *, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_Pts1dCalcBBox( NL_POINT *, NL_INDEX, NL_MINMAXBOX * );
GW_EXPORT NL_VOID N_Pts2dCalcBBox( NL_POINT **, NL_INDEX, NL_INDEX, NL_MINMAXBOX * );
GW_EXPORT NL_FLAG N_ProjectPtLineParam( NL_POINT, NL_POINT, NL_POINT, NL_POINT *, NL_REAL * );
GW_EXPORT NL_VOID N_CalcCircArcDerivs( NL_POINT, NL_VECTOR, NL_VECTOR, NL_REAL, NL_REAL, NL_INDEX, NL_VECTOR * );
GW_EXPORT NL_FLAG N_DistMaxLineArc( NL_POINT, NL_REAL, NL_REAL, NL_REAL, NL_POINT, NL_POINT, NL_POINT, NL_POINT, NL_REAL * );
GW_EXPORT NL_FLAG N_PlaneFitOrdered3dPts( NL_POINT *, NL_INDEX, NL_POINT *, NL_VECTOR * );
GW_EXPORT NL_FLAG N_AreaSpherePolygon( NL_REAL *, NL_REAL *, NL_INDEX, NL_REAL * );
GW_EXPORT NL_FLAG N_AreaSpherePatch( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL * );
GW_EXPORT NL_BOOLEAN N_PtsAreColinear( NL_POINT, NL_POINT, NL_POINT, NL_REAL );
GW_EXPORT NL_FLAG N_CalcCircCenterAndRadius( NL_POINT, NL_POINT, NL_POINT, NL_POINT *, NL_REAL *, NL_FLAG * );
GW_EXPORT NL_FLAG N_CreateCircFrom2dPts( NL_POINT *, NL_INDEX, NL_REAL, NL_FLAG, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL *, NL_FLAG * );
GW_EXPORT NL_FLAG N_LineFitPts( NL_POINT *, NL_INDEX, NL_POINT *, NL_VECTOR *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_PlaneFit3dPts( NL_POINT *, NL_INDEX, NL_POINT *, NL_VECTOR *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_SphereFit3dPts( NL_POINT *, NL_INDEX, NL_REAL, NL_FLAG, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL *, NL_FLAG * );
GW_EXPORT NL_FLAG N_BoundRect2dPts( NL_POINT *, NL_INDEX, NL_FLAG, NL_REAL, NL_POINT *, NL_POINT *, NL_POINT *, NL_POINT *, NL_REAL * );
GW_EXPORT NL_FLAG N_SphereCenterRadius( NL_POINT, NL_POINT, NL_POINT, NL_POINT, NL_POINT *, NL_REAL *, NL_FLAG * );
GW_EXPORT NL_FLAG N_CreateTransformMatrixFromVector( NL_VECTOR, NL_FLAG, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_ProjectPtClosePolyPt( NL_POINT *, NL_REAL *, NL_INDEX, NL_POINT, NL_POINT *, NL_REAL *, NL_REAL * );

#endif /* _NL_GEOM_H */
