// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/****************************************************************************/
/* NL_Iges.h: NLib Math Function Declarations                               */
/****************************************************************************/

#ifndef _NL_IGES_H
#define _NL_IGES_H

GW_EXPORT NL_FLAG N_Iges126Crv( NL_INDEX, NL_DEGREE, NL_REAL *, NL_REAL *, NL_POINT *, NL_PARAMETER[2], NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_IgesClampCrv( NL_CURVE *, NL_PARAMETER[2], NL_STACKS * );
GW_EXPORT NL_FLAG N_IgesCorrectCrvKnots( NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_IgesValidate( NL_REAL *, NL_INDEX, NL_DEGREE, NL_PARAMETER[2] );
GW_EXPORT NL_FLAG N_Iges128Srf( NL_INDEX, NL_INDEX, NL_DEGREE, NL_DEGREE, NL_REAL *, NL_REAL *, NL_REAL **, NL_POINT **, NL_PARAMETER[2], NL_PARAMETER[2], NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_IgesClampSrf( NL_SURFACE *, NL_PARAMETER[2], NL_PARAMETER[2], NL_STACKS * );
GW_EXPORT NL_FLAG N_IgesCorrectSrfKnots( NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges112CrvNonRat( NL_INDEX, NL_PARAMETER *, NL_REAL ***, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges100Arc( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_FLAG, NL_REAL, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges100Line( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges124Matrix( NL_REAL[3][3], NL_VECTOR, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges102CompositeCrv( NL_INDEX, NL_CURVE **, NL_FLAG, NL_REAL, NL_CURVE *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges108Plane( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_MINMAXBOX *, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges122ExtrudedSrf( NL_CURVE *, NL_POINT, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges118RuledSrf( NL_CURVE *, NL_CURVE *, NL_SURFACE *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges114NonRatSrf( NL_INDEX, NL_INDEX, NL_PARAMETER *, NL_PARAMETER *, NL_REAL ***, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges120RevolvedSrf( NL_POINT, NL_POINT, NL_CURVE *, NL_REAL, NL_REAL, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges106LinearCrv( NL_INDEX, NL_POINT *, NL_FLAG, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_Iges104ConicArc( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_FLAG, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_IgesNonPeriodicCPts( NL_INDEX, NL_DEGREE, NL_VOID *, NL_FLAG, NL_INDEX, NL_INDEX *, NL_VOID * );
GW_EXPORT NL_FLAG N_IgesNonPeriodicKnots( NL_INDEX, NL_DEGREE, NL_REAL *, NL_INDEX, NL_REAL *, NL_INDEX * );
GW_EXPORT NL_FLAG N_IgesNonPeriodicCrv( NL_INDEX, NL_DEGREE, NL_REAL *, NL_REAL *, NL_POINT *, NL_FLAG, NL_INDEX *, NL_REAL **, NL_REAL **, NL_POINT **, NL_STACKS * );
GW_EXPORT NL_FLAG N_IgesNonPeriodicSrf( NL_INDEX, NL_INDEX, NL_DEGREE, NL_DEGREE, NL_REAL *, NL_REAL *, NL_REAL **, NL_POINT **, NL_FLAG, NL_FLAG, NL_INDEX *, NL_INDEX *, NL_REAL **, NL_REAL **, NL_REAL ***, NL_POINT ***, NL_STACKS * );

#endif /* _NL_IGES_H */
