// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*****************************************************************************/
/* NL_math.h: NLib Math Function Declarations                               */
/*****************************************************************************/

#ifndef _NL_MATH_H
#define _NL_MATH_H

/***********************/
/* Arithmetic routines */
/***********************/

GW_EXPORT NL_VOID N_Combine2CPts( NL_REAL, NL_CPOINT, NL_REAL, NL_CPOINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_VectorCombineCPts( NL_VECTOR, NL_CPOINT, NL_VECTOR, NL_CPOINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_Combine2Pts( NL_REAL, NL_POINT, NL_REAL, NL_POINT, NL_POINT * );
GW_EXPORT NL_VOID N_VectorCombinePts( NL_VECTOR, NL_POINT, NL_VECTOR, NL_POINT, NL_POINT * );
GW_EXPORT NL_VOID N_TranslateSum2Pts( NL_POINT, NL_REAL, NL_POINT, NL_REAL, NL_POINT, NL_POINT * );
GW_EXPORT NL_VOID N_TranslateSum2CPts( NL_CPOINT, NL_REAL, NL_CPOINT, NL_REAL, NL_CPOINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_Combine4Pts( NL_REAL, NL_POINT, NL_REAL, NL_POINT, NL_REAL, NL_POINT, NL_REAL, NL_POINT, NL_POINT * );
GW_EXPORT NL_VOID N_Combine4CPts( NL_REAL, NL_CPOINT, NL_REAL, NL_CPOINT, NL_REAL, NL_CPOINT, NL_REAL, NL_CPOINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_CopyCPt( NL_CPOINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_CopyPt( NL_POINT , NL_POINT * );
GW_EXPORT NL_VOID N_CPtToPtEuclid( NL_CPOINT, NL_POINT * );
GW_EXPORT NL_VOID N_CPtToPtAndW( NL_CPOINT, NL_POINT *, NL_REAL * );
GW_EXPORT NL_VOID N_Weight( NL_POINT, NL_REAL, NL_CPOINT * );
GW_EXPORT NL_VOID N_VectorBlendCPt( NL_REAL, const NL_CPOINT&, NL_CPOINT * );
GW_EXPORT NL_VOID N_ScaleCPt( NL_REAL, NL_CPOINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_ScaleCPtXYZ( NL_REAL, NL_CPOINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_VectorBlendPt( NL_REAL, NL_POINT, NL_POINT * );
GW_EXPORT NL_VOID N_ScalePt( NL_REAL, NL_POINT, NL_POINT * );
GW_EXPORT NL_VOID N_TransformCPt( NL_CPOINT, NL_RMATRIX *, NL_CPOINT * );
GW_EXPORT NL_VOID N_TransformPt( NL_POINT, NL_RMATRIX *, NL_POINT * );
GW_EXPORT NL_VOID N_TranslateCPt( NL_CPOINT, NL_VECTOR, NL_CPOINT * );
GW_EXPORT NL_VOID N_ScaleCPtWithPtAndVector( NL_CPOINT, NL_POINT, NL_VECTOR, NL_CPOINT * );
GW_EXPORT NL_VOID N_PtToCPt( NL_POINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_CPtGetW( NL_CPOINT, NL_REAL * );
GW_EXPORT NL_VOID N_PtToXYZ( NL_POINT, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_PtFromXYZ( NL_REAL, NL_REAL, NL_REAL, NL_POINT * );
GW_EXPORT NL_VOID N_CPtToWxWyWz( NL_CPOINT, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_CPtFromWxWyWz( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_CPOINT * );
GW_EXPORT NL_VOID N_CPtSetX( NL_REAL, NL_CPOINT * );
GW_EXPORT NL_VOID N_CPtSetY( NL_REAL, NL_CPOINT * );
GW_EXPORT NL_VOID N_CPtSetZ( NL_REAL, NL_CPOINT * );
GW_EXPORT NL_VOID N_CPtSetW( NL_REAL, NL_CPOINT * );
GW_EXPORT NL_VOID N_Sum2Pts( NL_POINT, NL_POINT, NL_POINT * );                       
GW_EXPORT NL_VOID N_Sum2CPts( NL_CPOINT, NL_CPOINT, NL_CPOINT * );                   
GW_EXPORT NL_VOID N_SumCPtAndPt( NL_CPOINT, NL_POINT, NL_CPOINT * );                 
GW_EXPORT NL_VOID N_Diff2Pts( NL_POINT, NL_POINT, NL_POINT * );
GW_EXPORT NL_VOID N_Diff2CPts( NL_CPOINT, NL_CPOINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_DiffCPtPt( NL_CPOINT, NL_POINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_Dot2Pts( NL_POINT, NL_POINT, NL_REAL * );
GW_EXPORT NL_VOID N_Dot2CPtsIn4D( NL_CPOINT, NL_CPOINT, NL_REAL * );
GW_EXPORT NL_VOID N_Dot2CPts( NL_CPOINT, NL_CPOINT, NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_Cross2CPts( NL_CPOINT, NL_CPOINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_Cross2Pts( NL_POINT, NL_POINT, NL_POINT * );
GW_EXPORT NL_VOID N_PtMagnitude( NL_POINT, NL_REAL * );
GW_EXPORT NL_VOID N_CPtMagnitude( NL_CPOINT, NL_REAL * );
GW_EXPORT NL_VOID N_CPtRatDeriv( NL_CPOINT, NL_VECTOR, NL_REAL, NL_CVECTOR * );
GW_EXPORT NL_VOID N_CPtToXYZ( NL_CPOINT, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_CPtToPtNoW( NL_CPOINT, NL_CPOINT * );
GW_EXPORT NL_VOID N_CPtGetZ( NL_CPOINT, NL_REAL * );
GW_EXPORT NL_VOID N_CPtResetW( NL_CPOINT, NL_REAL, NL_CPOINT * );
GW_EXPORT NL_VOID N_CPtToPt( NL_CPOINT, NL_POINT * );

/*****************/
/* Math routines */
/*****************/

GW_EXPORT NL_FLAG N_SolveQuadraticEq( NL_REAL, NL_REAL, NL_REAL, NL_REAL *, NL_REAL *, NL_INTEGER * );
GW_EXPORT NL_BOOLEAN N_FloatOpIsBad( NL_REAL, NL_REAL, NL_FLAG );
GW_EXPORT NL_VOID N_SwapIntegers( NL_INTEGER *, NL_INTEGER * );
GW_EXPORT NL_VOID N_SwapReals( NL_REAL *, NL_REAL * );
GW_EXPORT NL_VOID N_ShellSortReal( NL_REAL *, NL_INDEX );
GW_EXPORT NL_VOID N_SearchInsertReal( NL_REAL *, NL_INDEX, NL_REAL, NL_INDEX * );
GW_EXPORT NL_INTEGER N_MinMax1dIntArray( NL_INTEGER *, NL_INDEX, NL_FLAG );
GW_EXPORT NL_INTEGER N_MinMax2dIntArray( NL_INTEGER **, NL_INDEX, NL_INDEX, NL_FLAG );
GW_EXPORT NL_REAL N_MinMax1dRealArray( NL_REAL *, NL_INDEX, NL_FLAG );
GW_EXPORT NL_REAL N_MinMax2dRealArray( NL_REAL **, NL_INDEX, NL_INDEX, NL_FLAG );
GW_EXPORT NL_VOID N_SwapPts( NL_POINT *, NL_POINT * );
GW_EXPORT NL_VOID N_SwapCPts( NL_CPOINT *, NL_CPOINT * );
GW_EXPORT NL_VOID N_PascalTriIndex( NL_INTEGER *, NL_INDEX );
GW_EXPORT NL_VOID N_PascalTriRow( NL_INTEGER **, NL_INDEX );
GW_EXPORT NL_VOID N_InitIntMatrix( NL_IMATRIX * );
GW_EXPORT NL_VOID N_InitRealMatrix( NL_RMATRIX * );
GW_EXPORT NL_VOID N_InitPtMatrix( NL_PMATRIX * );
GW_EXPORT NL_VOID N_InitCPtMatrix( NL_CMATRIX * );
GW_EXPORT NL_VOID N_CreateIntMatrix( NL_IMATRIX *, NL_INDEX, NL_INDEX, NL_INTEGER **, NL_MATRIXTYPE, NL_INDEX );
GW_EXPORT NL_VOID N_CreateRealMatrix( NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_REAL **, NL_MATRIXTYPE, NL_INDEX );
GW_EXPORT NL_VOID N_CreatePtMatrix( NL_PMATRIX *, NL_INDEX, NL_INDEX, NL_POINT **, NL_MATRIXTYPE, NL_INDEX );
GW_EXPORT NL_VOID N_CreateCPtMatrix( NL_CMATRIX *, NL_INDEX, NL_INDEX, NL_CPOINT **, NL_MATRIXTYPE, NL_INDEX );
GW_EXPORT NL_VOID N_IntMatrixDefine( NL_IMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX );
GW_EXPORT NL_VOID N_RealMatrixDefine( NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX );
GW_EXPORT NL_VOID N_PtMatrixDefine( NL_PMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX );
GW_EXPORT NL_VOID N_CPtMatrixDefine( NL_CMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX );
GW_EXPORT NL_VOID N_GetIntMatrixData( NL_IMATRIX *, NL_INDEX *, NL_INDEX *, NL_INTEGER ***, NL_MATRIXTYPE *, NL_INDEX * );
GW_EXPORT NL_VOID N_GetRealMatrixData( NL_RMATRIX *, NL_INDEX *, NL_INDEX *, NL_REAL ***, NL_MATRIXTYPE *, NL_INDEX * );
GW_EXPORT NL_VOID N_GetPtMatrixData( NL_PMATRIX *, NL_INDEX *, NL_INDEX *, NL_POINT ***, NL_MATRIXTYPE *, NL_INDEX * );
GW_EXPORT NL_VOID N_GetCPtMatrixData( NL_CMATRIX *, NL_INDEX *, NL_INDEX *, NL_CPOINT ***, NL_MATRIXTYPE *, NL_INDEX * );
GW_EXPORT NL_VOID N_GetMaxIndexIntMatrix( NL_IMATRIX *, NL_INDEX *, NL_INDEX * );
GW_EXPORT NL_VOID N_GetMaxIndexRealMatrix( NL_RMATRIX *, NL_INDEX *, NL_INDEX * );
GW_EXPORT NL_VOID N_GetMaxIndexPtMatrix( NL_PMATRIX *, NL_INDEX *, NL_INDEX * );
GW_EXPORT NL_VOID N_GetMaxIndexCPtMatrix( NL_CMATRIX *, NL_INDEX *, NL_INDEX * );
GW_EXPORT NL_VOID N_GetIntMatrixPtr( NL_IMATRIX *, NL_INTEGER *** );
GW_EXPORT NL_VOID N_GetRealMatrixPtr( NL_RMATRIX *, NL_REAL *** );
GW_EXPORT NL_VOID N_GetPtMatrixPtr( NL_PMATRIX *, NL_POINT *** );
GW_EXPORT NL_VOID N_GetCPtMatrixPtr( NL_CMATRIX *, NL_CPOINT *** );
GW_EXPORT NL_VOID N_PrintRealMatrix( NL_RMATRIX * );
GW_EXPORT NL_BOOLEAN N_IntMatrixIsNULL( NL_IMATRIX * );
GW_EXPORT NL_BOOLEAN N_RealMatrixIsNULL( NL_RMATRIX * );
GW_EXPORT NL_BOOLEAN N_PtMatrixIsNULL( NL_PMATRIX * );
GW_EXPORT NL_BOOLEAN N_CPtMatrixIsNULL( NL_CMATRIX * );
GW_EXPORT NL_FLAG N_InitRealHash( NL_REAL ***, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_UpdateRealHash( NL_REAL **, NL_INDEX, NL_REAL, NL_REAL, NL_REAL, NL_INDEX *, NL_STACKS * );
GW_EXPORT NL_VOID N_RetrieveRealHash( NL_REAL **, NL_INDEX, NL_REAL * );
GW_EXPORT NL_FLAG N_SetIntMatrix( NL_IMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_SetRealMatrix( NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_SetPtMatrix( NL_PMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_SetCPtMatrix( NL_CMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_CheckMemIntMatrix( NL_IMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STRING, NL_STACKS * );
GW_EXPORT NL_FLAG N_CheckMemRealMatrix( NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STRING, NL_STACKS * );
GW_EXPORT NL_FLAG N_CheckMemPtMatrix( NL_PMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STRING, NL_STACKS * );
GW_EXPORT NL_FLAG N_CheckMemCPtMatrix( NL_CMATRIX *, NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STRING, NL_STACKS * );
GW_EXPORT NL_FLAG N_RealMatrixMultiply( NL_RMATRIX *, NL_RMATRIX *, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_RealMatrixMultiplyTranspose( NL_RMATRIX *, NL_RMATRIX *, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_RealMatrixTransposeMultiply( NL_RMATRIX *, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_RealMatrixTranspose( NL_RMATRIX *, NL_RMATRIX *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_RealMatrixMultiplyPtArray( NL_RMATRIX *, NL_POINT *, NL_POINT * );
GW_EXPORT NL_FLAG N_RealMatrixMultiplyCPtArray( NL_RMATRIX *, NL_CPOINT *, NL_CPOINT * );
GW_EXPORT NL_FLAG N_RealMatrixMultiplyRealMatrixTranspose( NL_RMATRIX *, NL_CPOINT **, NL_RMATRIX *, NL_CPOINT ** );
GW_EXPORT NL_VOID N_PowerBasisCrvEvalPts( NL_CPOINT *, NL_INDEX, NL_PARAMETER, NL_POINT * );
GW_EXPORT NL_VOID N_PowerBasisSrfEvalPts( NL_CPOINT **, NL_INDEX, NL_INDEX, NL_PARAMETER, NL_PARAMETER, NL_POINT * );
GW_EXPORT NL_VOID N_PowerBasisEvalDerivs( NL_REAL *, NL_INDEX, NL_PARAMETER, NL_INDEX, NL_REAL * );
GW_EXPORT NL_FLAG N_PowerBasisRootNewton( NL_REAL *, NL_INDEX, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_REAL, NL_REAL * );
GW_EXPORT NL_FLAG N_RealMatrixLuDecompose( NL_RMATRIX * );
GW_EXPORT NL_FLAG N_RealMatrixLuDecomposePivot( NL_RMATRIX *, NL_INDEX * );
GW_EXPORT NL_FLAG N_RealMatrixForBack( NL_RMATRIX *, NL_VOID *, NL_FLAG, NL_CPOINT *, NL_STACKS * );
GW_EXPORT NL_FLAG N_RealMatrixRightForBack( NL_RMATRIX *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_RealMatrixForBackPivot( NL_RMATRIX *, NL_INDEX *, NL_REAL * );
GW_EXPORT NL_FLAG N_RealMatrixInverse( NL_RMATRIX *, NL_FLAG, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_RealMatrixInversePivot( NL_RMATRIX *, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_RealMatrixLstSqSolve( NL_RMATRIX *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_SingleValueDecomposeSolve( NL_REAL **, NL_REAL *, NL_REAL **, NL_INDEX, NL_INDEX, NL_VOID *, NL_FLAG, NL_FLAG, NL_VOID * );
GW_EXPORT NL_FLAG N_RealMatrixSingleValueDecompose( NL_REAL **, NL_REAL *, NL_REAL **, NL_INDEX, NL_INDEX );
GW_EXPORT NL_FLAG N_RealMatrixRightForBackPivot( NL_RMATRIX *, NL_INDEX *, NL_POINT *, NL_CPOINT * );
GW_EXPORT NL_VOID N_SortRealArray( NL_REAL *, NL_INDEX, NL_INDEX * );
GW_EXPORT NL_VOID N_SortIndexArrayMap( NL_INDEX *, NL_INDEX, NL_INDEX * );
GW_EXPORT NL_VOID N_SortIndexArray( NL_INDEX *a, NL_INDEX n );
GW_EXPORT NL_VOID N_FuncFindMinima( NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL( * )(NL_REAL), NL_REAL, NL_REAL, NL_REAL *, NL_REAL * );

GW_EXPORT
NL_FLAG
N_EvenSpacePtsSrf(NL_FLAG (*)(NL_REAL, NL_REAL, NL_POINT *), NL_PARAMETER ,
                                NL_PARAMETER , NL_PARAMETER , NL_PARAMETER , NL_INDEX ,
                                NL_INDEX , NL_REAL, NL_POINT **, NL_PARAMETER *, NL_PARAMETER *);

GW_EXPORT
NL_FLAG
N_EvenSpacePtsCrv(NL_FLAG (*)(NL_REAL, NL_POINT *), NL_PARAMETER , NL_PARAMETER ,
                                NL_INDEX , NL_REAL , NL_POINT *, NL_PARAMETER *);

GW_EXPORT NL_FLAG N_Real2dArrayInverseSVD( NL_REAL **, NL_INDEX, NL_REAL ** );
GW_EXPORT NL_INTEGER N_GenerateRandomNumber( NL_VOID );
GW_EXPORT NL_BOOLEAN N_RandomFlipsFlops( NL_VOID );
GW_EXPORT NL_VOID N_FindElemIntArray( NL_INDEX *, NL_INDEX, NL_INDEX, NL_INDEX * );
GW_EXPORT NL_FLAG N_FindIntervalIntArray( NL_INDEX *, NL_INDEX, NL_INDEX, NL_FLAG, NL_INDEX * );
GW_EXPORT NL_FLAG N_FindIntervalRealArray( NL_REAL *, NL_INDEX, NL_REAL, NL_FLAG, NL_INDEX * );
GW_EXPORT NL_FLAG N_TangentVectorBessel( NL_POINT *, NL_INDEX, NL_REAL *, NL_FLAG, NL_VECTOR * );
GW_EXPORT NL_FLAG N_TangentVectorAkima( NL_POINT *, NL_INDEX, NL_FLAG, NL_VECTOR * );
GW_EXPORT NL_FLAG N_RealMatrixEigenValuesVectors( NL_RMATRIX *, NL_REAL *, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_FindClustersRealArray( NL_REAL *, NL_INDEX, NL_REAL, NL_FLAG, NL_REAL **, NL_INDEX *, NL_REAL ***, NL_INDEX **, NL_STACKS * );
GW_EXPORT NL_VOID N_SortRealIndexArrays( NL_REAL *, NL_INDEX *, NL_INDEX );
GW_EXPORT NL_FLAG N_RealMatrixInverseSVD( NL_RMATRIX *, NL_RMATRIX *, NL_STACKS * );
GW_EXPORT NL_VOID N_SortRealRealArrays( NL_REAL *, NL_REAL *, NL_INDEX );
GW_EXPORT NL_FLAG M_TridiagonalSystem( NL_REAL *, NL_REAL *, NL_REAL *, NL_POINT *, NL_INDEX, NL_POINT * );
GW_EXPORT NL_FLAG M_CorneredTridiagonalSystem( NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL, NL_REAL, NL_POINT *, NL_INDEX, NL_POINT * );

GW_EXPORT NL_VOID M_NoErrChk( NL_INDEX onoff );

#endif /* _NL_MATH_H */
