// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*************************************************************************/
/* SrfTool.h: Tool Function Declarations that act on NL_SURFACE objects  */
/*************************************************************************/

#ifndef _SRFTOOL_H
#define _SRFTOOL_H

GW_EXPORT NL_FLAG N_SrfInsertKnot( NL_SURFACE *, NL_PARAMETER, NL_INDEX, NL_FLAG, NL_SURFACE *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfSplit( NL_SURFACE *, NL_PARAMETER, NL_FLAG, NL_SURFACE *, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfInsertKnotPt( NL_SURFACE *, NL_POINT, NL_SURFACE *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfDecomposeToBez( NL_SURFACE *, NL_SURFACE ****, NL_INDEX *, NL_INDEX *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfExtractIsoCrv( NL_SURFACE *, NL_PARAMETER, NL_FLAG, NL_CURVE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfInsertKnots( NL_SURFACE *, NL_KNOTVECTOR *, NL_FLAG, NL_SURFACE *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfExtractPatch( NL_SURFACE *, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_PARAMETER, NL_SURFACE *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfRemoveKnotConditional( NL_SURFACE *, NL_PARAMETER, NL_INDEX, NL_REAL, NL_FLAG, NL_INDEX *, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfRemoveOneKnot( NL_SURFACE *, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_FLAG, NL_REAL * );
GW_EXPORT NL_FLAG N_SrfRemoveAllKnots( NL_SURFACE *, NL_REAL, NL_FLAG, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfRemoveAllKnotsArcLen( NL_SURFACE *, NL_REAL, NL_FLAG, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfElevateDegree( NL_SURFACE *, NL_INDEX, NL_FLAG, NL_SURFACE *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfReduceDegree( NL_SURFACE *, NL_REAL, NL_FLAG, NL_FLAG *, NL_SURFACE *, NL_REAL *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfReduceDegreeToTol( NL_SURFACE *, NL_REAL, NL_SURFACE *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_MakeSrfsCompatibleUV( NL_SURFACE **, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_MakeSrfsCompatible( NL_SURFACE **, NL_INDEX, NL_FLAG, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfReparmAndRemoveKnotsKeepBoundaries( NL_SURFACE *, NL_FLAG, NL_FLAG, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, 
                                                           NL_FLAG, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfJoin( NL_SURFACE *, NL_SURFACE *, NL_FLAG, NL_REAL, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfRemoveDegenPatch( NL_SURFACE *, NL_REAL, NL_FLAG, NL_INDEX *, NL_INDEX *, NL_SURFACE *, NL_STACKS *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfExtractBoundaryCrvs( NL_SURFACE *, NL_CURVE *, NL_CURVE *, NL_CURVE *, NL_CURVE *, NL_STACKS * );

GW_EXPORT NL_FLAG N_SrfRemoveKnotMultiple( NL_SURFACE *, NL_PARAMETER, NL_INDEX, NL_FLAG, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfRemoveKnots( NL_SURFACE *, NL_REAL, NL_FLAG, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfRemoveKnot( NL_SURFACE *, NL_INDEX, NL_INDEX, NL_FLAG, NL_FLAG, NL_FLAG, NL_SURFACE * );
GW_EXPORT NL_FLAG N_SrfRemoveKnotsKeepBoundaries( NL_SURFACE *, NL_FLAG, NL_FLAG, NL_FLAG, NL_REAL, NL_REAL, NL_REAL, NL_REAL, NL_REAL, 
                                                  NL_FLAG, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfCrossBoundaryDerivErr( NL_SURFACE *, NL_SURFACE *, NL_INDEX, NL_INDEX, NL_FLAG, NL_FLAG, NL_FLAG, NL_REAL *, NL_REAL *, 
                                              NL_REAL *, NL_REAL *, NL_FLAG, NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL * );
GW_EXPORT NL_FLAG N_SrfRemoveKnotsConstraints( NL_SURFACE *, NL_PARAMETER *, NL_INDEX, NL_PARAMETER *, NL_INDEX, NL_REAL, NL_FLAG, NL_SURFACE *, NL_STACKS * );
GW_EXPORT NL_FLAG N_SrfNetworkTopology( NL_SURFACE **, NL_INDEX, NL_SURFACE ****, NL_INDEX *, NL_INDEX *, NL_INDEX ***, NL_INDEX *, NL_INDEX *, 
                                        NL_INDEX, NL_REAL ***, NL_STACKS * );

#endif /* _SRFTOOL_H */
