// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/**********************************************************************/
/* SrfLstSqFit.h: Surface Fitting related functions                   */
/**********************************************************************/

#ifndef _SRFLSTSQFIT_H
#define _SRFLSTSQFIT_H

/* fit a point cloud to an existing surface - optionally constrain surface's boundary shape, */
/*      and for bicubic surfaces only optionally smooth the surface with an alpha term.      */
/*      uv mapping is generated by projecting to the given surface.                          */
GW_EXPORT NL_FLAG N_FitSurfApproxPoints( NL_POINT *, NL_INDEX, NL_SURFACE *, NL_FLAG, NL_FLAG, NL_REAL, NL_REAL, NL_REAL * );

/* fit a point cloud with optional surface normal data - uv mapping is generated by projecting to a best fit plane */
GW_EXPORT NL_FLAG N_FitRandomPN( NL_POINT *, NL_VECTOR *, NL_INDEX,
                                 NL_INDEX, NL_INDEX, NL_DEGREE, NL_DEGREE, NL_SURFACE *, NL_STACKS * );

/* fit a point cloud with optional surface normal data - uv mapping is generated by projecting to a best fit plane */
/*  algorithm fails unless some data points map to the uv domain of every control point */
GW_EXPORT NL_FLAG N_FitRandomPNWithPlane( NL_POINT *, NL_VECTOR *, NL_INDEX, NL_POINT *, NL_VECTOR *, NL_VECTOR *,
                                          NL_INDEX, NL_INDEX, NL_DEGREE, NL_DEGREE, NL_SURFACE *, NL_STACKS * );

/* Iterate with N_FitRandomPNWithPlane() calls until given tolerance is achieved */
GW_EXPORT NL_FLAG N_FitRandomPNWithPlaneToTol( NL_POINT *, NL_VECTOR *, NL_INDEX, NL_REAL, NL_POINT *, NL_VECTOR *, NL_VECTOR *,
                                               NL_INDEX, NL_INDEX, NL_DEGREE, NL_DEGREE, NL_SURFACE *, NL_STACKS * );

/* fit a point cloud (with given uv Point map) with optional boundary position and cross-derivative constraints */
GW_EXPORT NL_FLAG N_FitSrfLstSqBoundary(NL_POINT *, NL_REAL *, NL_REAL *, NL_REAL *, NL_INDEX , NL_CURVE ** ,
                             NL_CURVE **, NL_INDEX , NL_INDEX , NL_DEGREE , NL_DEGREE , NL_REAL *,
                             NL_REAL *, NL_FLAG , NL_FLAG, NL_FLAG,
                             NL_FLAG (*)(NL_LLONG, NL_LLONG, NL_LLONG, NL_POINT *, NL_CPOINT *),
                             NL_SURFACE *,
                             NL_STACKS *);

/* fit a point cloud (with given uv Point map) with optional boundary position and cross-derivative constraints */
GW_EXPORT NL_FLAG N_FitSrfLstSqDeformablePeriodic(NL_POINT *, NL_REAL *, NL_REAL *, NL_REAL *, NL_INDEX , NL_CURVE ** ,
                             NL_INDEX , NL_INDEX , NL_DEGREE , NL_DEGREE , NL_REAL *,
                             NL_REAL *, NL_REAL, NL_REAL, NL_REAL,
                             NL_FLAG , NL_FLAG, NL_FLAG, NL_FLAG, NL_FLAG,
                             NL_FLAG (*)(NL_LLONG, NL_LLONG, NL_LLONG, NL_POINT *, NL_CPOINT *),
                             NL_SURFACE *,
                             NL_STACKS *);

/* fit a point cloud (with given uv Point map) with optional surface tangent data at each point */
GW_EXPORT NL_FLAG N_FitSrfLstSqDerivs( NL_POINT *, NL_REAL *, NL_REAL *, NL_REAL *, NL_INDEX, NL_VECTOR *, NL_REAL *, NL_INDEX, NL_INDEX *, NL_VECTOR *, NL_REAL *, NL_INDEX, NL_INDEX *, NL_INDEX, NL_INDEX, NL_DEGREE, NL_DEGREE, NL_REAL *, NL_REAL *, NL_SURFACE *, NL_STACKS * );

/* fit a point cloud (with given uv Point map) with optional surface tangent data with a periodic nurbs surface */
GW_EXPORT NL_FLAG N_FitSrfLstSqPeriodic( NL_POINT *, NL_REAL *, NL_REAL *, NL_REAL *, NL_INDEX, NL_FLAG, NL_FLAG, NL_VECTOR *, NL_REAL *, NL_INDEX, NL_INDEX *, NL_VECTOR *, NL_REAL *, NL_INDEX, NL_INDEX *, NL_INDEX, NL_INDEX, NL_DEGREE, NL_DEGREE, NL_REAL *, NL_REAL *, NL_FLAG, NL_SURFACE *r, NL_STACKS * );

#endif /* _SRFLSTSQFIT_H */
