// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/**************************************************************************/
/* NL_Util.h: Utility Function Declarations                               */
/**************************************************************************/

#ifndef _NL_UTILITY_H
#define _NL_UTILITY_H

/* NLib Function Declarations */

GW_EXPORT NL_VOID N_InitNurbs( NL_STACKS * );
GW_EXPORT NL_VOID N_EndNurbs( NL_STACKS * );

GW_EXPORT void *N_Malloc( NL_INTEGER size);
GW_EXPORT void *N_Calloc( NL_INTEGER num, NL_INTEGER size);
GW_EXPORT void *N_Realloc( void *MemPtr, NL_INTEGER size );
GW_EXPORT void N_Free( void *MemPtr );
GW_EXPORT void N_MemSet(void *ptr, NL_INTEGER val, NL_INTEGER sizeInByte);


GW_EXPORT NL_FLAG *N_AllocFlag1dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG ** N_AllocFlag2dArray( NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG ** N_AllocFlagPtr1dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_INTEGER *N_AllocInt1dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_INTEGER ** N_AllocInt2dArray( NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_INTEGER ** N_AllocIntPtr1dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_INTEGER *** N_AllocIntPtr2dArray( NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_REAL *N_AllocReal1dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_REAL ** N_AllocReal2dArray( NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_REAL *** N_AllocReal3dArray( NL_INDEX, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_REAL ** N_AllocRealPtr1dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_REAL *** N_AllocRealPtr2dArray( NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_REAL *** N_AllocRealPtr3dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_REAL **** N_AllocReal4dArray( NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_POINT *N_AllocPt1dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_POINT ** N_AllocPt2dArray( NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_POINT *** N_AllocPt3dArray( NL_INDEX, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_CPOINT *N_AllocCPt1dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_CPOINT ** N_AllocCPt2dArray( NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_CPOINT *** N_AllocCPt3dArray( NL_INDEX m, NL_INDEX n, NL_INDEX o, NL_STACKS *S );

GW_EXPORT NL_POINT *N_XYZToPtArray( NL_REAL *, NL_REAL *, NL_REAL *, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_POINT ** N_XYZTo2dPtArray( NL_REAL **, NL_REAL **, NL_REAL **, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_CPOINT *N_XYZToCPtArray( NL_REAL *, NL_REAL *, NL_REAL *, NL_REAL *, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_CPOINT ** N_XYZTo2dCPtArray( NL_REAL **, NL_REAL **, NL_REAL **, NL_REAL **, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_IMATRIX *N_AllocIntMatrix( NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_RMATRIX *N_AllocRealMatrix( NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_PMATRIX *N_AllocPtMatrix( NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_CMATRIX *N_AllocCPtMatrix( NL_INDEX, NL_INDEX, NL_MATRIXTYPE, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_CPOINT ** N_AllocCPtPtr1dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_CPOINT *** N_AllocCPtPtr2dArray( NL_INDEX, NL_INDEX, NL_STACKS * );

GW_EXPORT NL_POINT ** N_AllocPtPtr1dArray( NL_INDEX, NL_STACKS * );
GW_EXPORT NL_POINT *** N_AllocPtPtr2dArray( NL_INDEX, NL_INDEX, NL_STACKS * );

GW_EXPORT NL_POINT ** N_AllocVariable2dPtArray( NL_INDEX, NL_INDEX *, NL_STACKS * );

/********************/
/* Utility routines */
/********************/

GW_EXPORT FILE *N_FileOpen( const TCHAR* fname, const TCHAR* mode );
GW_EXPORT NL_VOID N_FileWrite( FILE *, NL_STRING string );
GW_EXPORT NL_VOID N_FileClose( FILE * );
GW_EXPORT NL_VOID N_FileOffset( FILE *, NL_INTEGER bytes );
GW_EXPORT NL_INDEX N_FileReadIndex( FILE * );
GW_EXPORT NL_VOID N_FileWriteIndex( FILE *, NL_INDEX );
GW_EXPORT NL_FLAG N_Read1dPtFromFile( NL_POINT **, NL_INDEX *, TCHAR*, NL_STACKS * );
GW_EXPORT NL_FLAG N_Write1dPtToFile( NL_POINT *, NL_INDEX, TCHAR* );
GW_EXPORT NL_FLAG N_Read2dPtFromFile( NL_POINT ***, NL_INDEX *, NL_INDEX *, TCHAR*, NL_STACKS * );
GW_EXPORT NL_FLAG N_Write2dPtToFile( NL_POINT **, NL_INDEX, NL_INDEX, TCHAR* );
GW_EXPORT NL_VOID N_FreeFlag2dArray( NL_FLAG **, NL_STACKS * );
GW_EXPORT NL_VOID N_FreeFlag1dArray( NL_FLAG *, NL_STACKS * );
GW_EXPORT NL_VOID N_FreeInt1dArray( NL_INTEGER *, NL_STACKS * );
GW_EXPORT NL_VOID N_FreeInt2dArray( NL_INTEGER **, NL_STACKS * );
GW_EXPORT NL_VOID N_FreeIntPtr1dArray( NL_INTEGER **, NL_STACKS * );
GW_EXPORT NL_VOID N_FreeIntPtr2dArray( NL_INTEGER ***, NL_STACKS * );
GW_EXPORT NL_VOID N_FreeReal1dArray( NL_REAL *, NL_STACKS * );
GW_EXPORT NL_VOID N_FreeReal2dArray( NL_REAL **, NL_STACKS * );
GW_EXPORT NL_VOID N_FreeReal3dArray( NL_REAL ***, NL_STACKS * );
GW_EXPORT NL_VOID N_FreePt1dArray( NL_POINT *, NL_STACKS * );
GW_EXPORT NL_VOID N_FreePt2dArray( NL_POINT **, NL_STACKS * );
GW_EXPORT NL_VOID N_FreeCPt1dArray( NL_CPOINT *, NL_STACKS * );
GW_EXPORT NL_VOID N_FreeCPt2dArray( NL_CPOINT **, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc1dFlagArray( NL_FLAG **, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc2dFlagArray( NL_FLAG ***, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc1dIntArray( NL_INTEGER **, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc1dIntPtrArray( NL_INTEGER ***, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc2dIntArray( NL_INTEGER ***, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc2dIntPtrArray( NL_INTEGER ****, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc1dRealArray( NL_REAL **, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc2dRealArray( NL_REAL ***, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc1dPtArray( NL_POINT **, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc2dPtArray( NL_POINT ***, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc1dCPtArray( NL_CPOINT **, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_FLAG N_Realloc2dCPtArray( NL_CPOINT ***, NL_INDEX, NL_INDEX, NL_INDEX, NL_INDEX, NL_STACKS * );
GW_EXPORT NL_VOID N_PrintStack( NL_STACKS * );
GW_EXPORT NL_VOID N_CrvProjectionInitArrays( NL_GCPTEMP * );
GW_EXPORT NL_BOOLEAN N_CPtsAreEqual( NL_CPOINT, NL_CPOINT );
GW_EXPORT NL_FLAG N_WriteLineCrvSrfIges( NL_POINT **, NL_INDEX, NL_INDEX *, NL_CURVE **, NL_INDEX, NL_INDEX *, NL_SURFACE **, NL_INDEX, NL_REAL, TCHAR* );
GW_EXPORT NL_FLAG N_WritePtsIges( NL_POINT *, NL_INDEX, NL_REAL, NL_INDEX, NL_INDEX, NL_REAL, TCHAR* );
GW_EXPORT NL_FLAG N_WriteSrfIges( NL_SURFACE **, NL_INDEX, NL_REAL, NL_FLAG, NL_FLAG, NL_INDEX, TCHAR* );
GW_EXPORT NL_FLAG N_IsPtSet1dCircular( NL_POINT *, NL_INDEX, NL_REAL, NL_FLAG, NL_POINT *, NL_REAL *, NL_FLAG * );
GW_EXPORT NL_FLAG N_IsPtSet1dColinear( NL_POINT *, NL_INDEX, NL_REAL, NL_FLAG, NL_POINT *, NL_VECTOR *, NL_FLAG * );
GW_EXPORT NL_FLAG N_IsPtSet1dCoplanar( NL_POINT *, NL_INDEX, NL_REAL, NL_FLAG, NL_POINT *, NL_VECTOR *, NL_FLAG * );
GW_EXPORT NL_FLAG N_IsPtSet1dSpherical( NL_POINT *, NL_INDEX, NL_REAL, NL_FLAG, NL_POINT *, NL_REAL *, NL_FLAG * );
GW_EXPORT NL_VOID N_FreeCPt3dArray( NL_CPOINT *** c3d, NL_STACKS *S );

/******************/
/* Error routines */
/******************/

GW_EXPORT NL_VOID N_ErrSet( NL_INTEGER, const TCHAR * );
GW_EXPORT NL_VOID N_ErrClear( NL_VOID );
GW_EXPORT NL_FLAG N_CheckIntMatStorage( NL_IMATRIX *, NL_INDEX, NL_INDEX, NL_STRING );
GW_EXPORT NL_FLAG N_CheckRealMatStorage( NL_RMATRIX *, NL_INDEX, NL_INDEX, NL_STRING );
GW_EXPORT NL_FLAG N_CheckPtMatStorage( NL_PMATRIX *, NL_INDEX, NL_INDEX, NL_STRING );
GW_EXPORT NL_FLAG N_CheckCPtMatStorage( NL_CMATRIX *, NL_INDEX, NL_INDEX, NL_STRING );
GW_EXPORT NL_INTEGER N_ErrGetType( NL_VOID );
GW_EXPORT NL_STRING N_errRoutineName( NL_VOID );

#endif /* _NL_UTILITY_H */
