# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""SMLib Python GUI package."""

from .app import MainWindow, main
from .headless import (
    DEFAULT_VIEW_NAMES,
    HeadlessRenderResult,
    HeadlessRenderSession,
    HeadlessRenderSettings,
    SUPPORTED_VIEW_NAMES,
    discover_model_files,
    output_directory_for,
    write_contact_sheet,
)
from .history import SourceHistory
from .inspection import object_summary_text
from .model import ActiveObject
from .operations.booleans import apply_boolean_operation, boolean_source_line
from .operations.file_io import (
    LOAD_FILE_FILTER,
    SAVE_FILE_FILTER,
    SUPPORTED_LOAD_EXTENSIONS,
    occt_brep_io_available,
    brep_usd_io_available,
    ensure_extension_for_filter,
    export_native_brep,
    export_occt_brep,
    export_usd_objects,
    extension_for_filter,
    file_kind_for_path,
    import_file_objects,
    import_native_brep_object,
    import_occt_brep_objects,
    import_usd_objects,
    native_brep_file_is_ascii,
    native_brep_load_unavailable_reason,
)
from .operations.modify import ModifyResult, apply_modify_operation
from .operations.overlays import (
    BoxOverlay,
    CurveSampleOverlay,
    DrawBatchOverlay,
    LineOverlay,
    NormalOverlay,
    PickOverlay,
    PointOverlay,
    PolylineOverlay,
    SectionOverlay,
    SurfaceSampleOverlay,
    TopologyOverlay,
    brep_edge_highlight,
    brep_edge_polylines,
    brep_face_highlight,
    brep_face_normals,
    brep_vertex_highlight,
    make_overlay_object,
    sample_curve_overlay,
    sample_surface_overlay,
    section_overlay,
)
from .operations.test_runner import (
    DEBUG_GUIDANCE,
    PROG_TEST_SUITES,
    SMLIB_TESTS_UNAVAILABLE_HINT,
    draw_events_to_overlays,
    list_prog_test_suites,
    run_prog_test_suite,
    tests_available,
    unavailable_reason,
)
from .runtime import QtCore, QtGui, QtWidgets, REPO, np, pv, sm, smdev
from .scripting import execute_script
from .settings import (
    DISPLAY_MODE_MESH_WIREFRAME,
    DISPLAY_MODE_OPTIONS,
    DISPLAY_MODE_SHADED,
    DISPLAY_MODE_SHADED_MESH_WIREFRAME,
    DISPLAY_MODE_SHADED_WIREFRAME,
    DISPLAY_MODE_WIREFRAME,
    DisplaySettings,
    TessellationSettings,
)
from .tessellation import (
    objects_to_pyvista,
    objects_to_pyvista_batches,
    tessellate_objects,
)
from .viewport import CameraState, ViewportController

__all__ = [
    "ActiveObject",
    "BoxOverlay",
    "CameraState",
    "CurveSampleOverlay",
    "DEFAULT_VIEW_NAMES",
    "DEBUG_GUIDANCE",
    "DISPLAY_MODE_MESH_WIREFRAME",
    "DISPLAY_MODE_OPTIONS",
    "DISPLAY_MODE_SHADED",
    "DISPLAY_MODE_SHADED_MESH_WIREFRAME",
    "DISPLAY_MODE_SHADED_WIREFRAME",
    "DISPLAY_MODE_WIREFRAME",
    "DisplaySettings",
    "DrawBatchOverlay",
    "HeadlessRenderResult",
    "HeadlessRenderSession",
    "HeadlessRenderSettings",
    "LOAD_FILE_FILTER",
    "LineOverlay",
    "MainWindow",
    "ModifyResult",
    "NormalOverlay",
    "PROG_TEST_SUITES",
    "PickOverlay",
    "PointOverlay",
    "PolylineOverlay",
    "QtCore",
    "QtGui",
    "QtWidgets",
    "REPO",
    "SAVE_FILE_FILTER",
    "SMLIB_TESTS_UNAVAILABLE_HINT",
    "SectionOverlay",
    "SourceHistory",
    "SUPPORTED_LOAD_EXTENSIONS",
    "SUPPORTED_VIEW_NAMES",
    "SurfaceSampleOverlay",
    "TessellationSettings",
    "TopologyOverlay",
    "ViewportController",
    "apply_boolean_operation",
    "apply_modify_operation",
    "boolean_source_line",
    "brep_edge_highlight",
    "brep_edge_polylines",
    "brep_face_highlight",
    "brep_face_normals",
    "brep_usd_io_available",
    "brep_vertex_highlight",
    "discover_model_files",
    "draw_events_to_overlays",
    "ensure_extension_for_filter",
    "execute_script",
    "export_native_brep",
    "export_occt_brep",
    "export_usd_objects",
    "extension_for_filter",
    "file_kind_for_path",
    "import_file_objects",
    "import_native_brep_object",
    "import_occt_brep_objects",
    "import_usd_objects",
    "list_prog_test_suites",
    "main",
    "make_overlay_object",
    "native_brep_file_is_ascii",
    "native_brep_load_unavailable_reason",
    "occt_brep_io_available",
    "np",
    "object_summary_text",
    "objects_to_pyvista",
    "objects_to_pyvista_batches",
    "output_directory_for",
    "pv",
    "run_prog_test_suite",
    "sample_curve_overlay",
    "sample_surface_overlay",
    "section_overlay",
    "sm",
    "smdev",
    "tessellate_objects",
    "tests_available",
    "unavailable_reason",
    "write_contact_sheet",
]
